-- Mise en Dice - initial per-participant ingredient availability
-- Requires: db/migrations/001_catalog_schema.sql
-- Requires: db/seeds/001_reference_data.sql
-- Requires: db/seeds/002_ingredient_catalog.sql
--
-- The baseline is EASY for the explicitly listed initial draw pool. Selected
-- specialty items are then downgraded only when the row was inserted by this
-- seed run, so later manual tuning survives re-runs.

WITH initial_concepts(code) AS (
    VALUES
        ('ALMOND'),
        ('APPLE'),
        ('APRICOT'),
        ('ARTICHOKE'),
        ('ASPARAGUS'),
        ('BACON'),
        ('BALSAMIC_VINEGAR'),
        ('BAMBOO_SHOOTS'),
        ('BANANA'),
        ('BASIL'),
        ('BEEF_GOULASH'),
        ('BEEF_MINCE'),
        ('BEEF_STEAK'),
        ('BEETROOT'),
        ('BELL_PEPPER'),
        ('BERRIES'),
        ('BLACK_GARLIC'),
        ('BLUEBERRY'),
        ('BLUE_CHEESE'),
        ('BROCCOLI'),
        ('BRUSSELS_SPROUTS'),
        ('BULGUR'),
        ('CABBAGE_VEGETABLES'),
        ('CAPERS'),
        ('CARROT'),
        ('CASHEW'),
        ('CAULIFLOWER'),
        ('CELERIAC'),
        ('CHAMPIGNON'),
        ('CHEESE'),
        ('CHICKEN'),
        ('CHICKEN_BREAST'),
        ('CHICKEN_THIGH'),
        ('CHICKPEAS'),
        ('CHILI'),
        ('CILANTRO'),
        ('CITRUS_FRUIT'),
        ('COCONUT_MILK'),
        ('COD'),
        ('CORN'),
        ('COUSCOUS'),
        ('CREAM'),
        ('CUCUMBER'),
        ('DILL'),
        ('DUCK_BREAST'),
        ('EDAMAME'),
        ('EGG'),
        ('EGGPLANT'),
        ('ESCARGOT'),
        ('FENNEL'),
        ('FETA'),
        ('FISH'),
        ('FISH_SAUCE'),
        ('FRESH_HERBS'),
        ('GARLIC'),
        ('GINGER'),
        ('GOCHUJANG'),
        ('GRAPE'),
        ('GRAPEFRUIT'),
        ('GREEN_BEANS'),
        ('HABANERO'),
        ('HONEY'),
        ('HORSERADISH'),
        ('JALAPENO'),
        ('KALE'),
        ('KIDNEY_BEANS'),
        ('KIMCHI'),
        ('LAMB'),
        ('LEAFY_GREENS'),
        ('LEEK'),
        ('LEGUMES'),
        ('LEMON'),
        ('LEMONGRASS'),
        ('LENTILS'),
        ('LIME'),
        ('MACKEREL'),
        ('MANGO'),
        ('MINT'),
        ('MISO'),
        ('MUSHROOMS'),
        ('MUSSELS'),
        ('MUSTARD'),
        ('NAPA_CABBAGE'),
        ('NOODLES'),
        ('NORI'),
        ('NUTS'),
        ('OILY_FISH'),
        ('OKRA'),
        ('OLIVES'),
        ('ONION'),
        ('ORANGE'),
        ('OYSTER_MUSHROOM'),
        ('OYSTER_SAUCE'),
        ('PAK_CHOI'),
        ('PARMESAN'),
        ('PARSLEY'),
        ('PARSNIP'),
        ('PASSION_FRUIT'),
        ('PEACH'),
        ('PEANUT'),
        ('PEANUT_BUTTER'),
        ('PEAR'),
        ('PINEAPPLE'),
        ('PLUM'),
        ('POINTED_CABBAGE'),
        ('POLENTA'),
        ('POLLOCK'),
        ('POMEGRANATE'),
        ('PORK_BELLY'),
        ('PORK_TENDERLOIN'),
        ('POTATO'),
        ('POULTRY'),
        ('PUMPKIN'),
        ('RADISH'),
        ('RASPBERRY'),
        ('RED_CABBAGE'),
        ('RICE'),
        ('RICE_NOODLES'),
        ('RICE_VINEGAR'),
        ('ROOT_VEGETABLES'),
        ('SALMON'),
        ('SAMBAL'),
        ('SAUERKRAUT'),
        ('SAVOY_CABBAGE'),
        ('SCALLOPS'),
        ('SEAWEED'),
        ('SEITAN'),
        ('SHELLFISH'),
        ('SHIITAKE'),
        ('SHRIMP'),
        ('SOBA'),
        ('SOY_SAUCE'),
        ('SPINACH'),
        ('SPRING_ONION'),
        ('SQUID'),
        ('STONE_FRUIT'),
        ('STRAWBERRY'),
        ('SWEET_POTATO'),
        ('TAHINI'),
        ('TAMARIND'),
        ('TEMPEH'),
        ('TOFU'),
        ('TOMATO'),
        ('TOMATO_PASTE'),
        ('TROUT'),
        ('TUNA'),
        ('UDON'),
        ('WAKAME'),
        ('WALNUT'),
        ('WHITE_BEANS'),
        ('WHITE_FISH'),
        ('YOGURT'),
        ('ZUCCHINI')
),
inserted AS (
    INSERT INTO ingredient_availability (
        ingredient_concept_id,
        participant_id,
        availability_level
    )
    SELECT ic.id, p.id, 'EASY'
    FROM initial_concepts source
    JOIN ingredient_concept ic ON ic.code = source.code
    CROSS JOIN participant p
    WHERE p.code IN ('TOBIAS', 'GEORGIA')
    ON CONFLICT (ingredient_concept_id, participant_id) DO NOTHING
    RETURNING ingredient_concept_id, participant_id
),
overrides(concept_code, participant_code, availability_level) AS (
    VALUES
        ('BAMBOO_SHOOTS', 'TOBIAS', 'PLANNED'),
        ('BAMBOO_SHOOTS', 'GEORGIA', 'PLANNED'),
        ('BLACK_GARLIC', 'TOBIAS', 'PLANNED'),
        ('BLACK_GARLIC', 'GEORGIA', 'PLANNED'),
        ('CILANTRO', 'TOBIAS', 'PLANNED'),
        ('DUCK_BREAST', 'TOBIAS', 'PLANNED'),
        ('DUCK_BREAST', 'GEORGIA', 'PLANNED'),
        ('EDAMAME', 'TOBIAS', 'PLANNED'),
        ('ESCARGOT', 'TOBIAS', 'DIFFICULT'),
        ('ESCARGOT', 'GEORGIA', 'DIFFICULT'),
        ('FISH_SAUCE', 'TOBIAS', 'PLANNED'),
        ('GOCHUJANG', 'TOBIAS', 'PLANNED'),
        ('HABANERO', 'TOBIAS', 'PLANNED'),
        ('HABANERO', 'GEORGIA', 'PLANNED'),
        ('JALAPENO', 'TOBIAS', 'PLANNED'),
        ('JALAPENO', 'GEORGIA', 'PLANNED'),
        ('KIMCHI', 'TOBIAS', 'PLANNED'),
        ('LAMB', 'TOBIAS', 'PLANNED'),
        ('LAMB', 'GEORGIA', 'PLANNED'),
        ('LEMONGRASS', 'TOBIAS', 'PLANNED'),
        ('MISO', 'TOBIAS', 'PLANNED'),
        ('MUSSELS', 'TOBIAS', 'PLANNED'),
        ('MUSSELS', 'GEORGIA', 'PLANNED'),
        ('NORI', 'TOBIAS', 'PLANNED'),
        ('OKRA', 'TOBIAS', 'DIFFICULT'),
        ('OKRA', 'GEORGIA', 'PLANNED'),
        ('OYSTER_MUSHROOM', 'TOBIAS', 'PLANNED'),
        ('OYSTER_SAUCE', 'TOBIAS', 'PLANNED'),
        ('PAK_CHOI', 'TOBIAS', 'PLANNED'),
        ('PASSION_FRUIT', 'TOBIAS', 'PLANNED'),
        ('PASSION_FRUIT', 'GEORGIA', 'PLANNED'),
        ('RICE_NOODLES', 'TOBIAS', 'PLANNED'),
        ('RICE_VINEGAR', 'TOBIAS', 'PLANNED'),
        ('SCALLOPS', 'TOBIAS', 'DIFFICULT'),
        ('SCALLOPS', 'GEORGIA', 'PLANNED'),
        ('SEAWEED', 'TOBIAS', 'PLANNED'),
        ('SEAWEED', 'GEORGIA', 'PLANNED'),
        ('SEITAN', 'TOBIAS', 'PLANNED'),
        ('SEITAN', 'GEORGIA', 'PLANNED'),
        ('SHELLFISH', 'TOBIAS', 'PLANNED'),
        ('SHELLFISH', 'GEORGIA', 'PLANNED'),
        ('SHIITAKE', 'TOBIAS', 'PLANNED'),
        ('SOBA', 'TOBIAS', 'PLANNED'),
        ('SOBA', 'GEORGIA', 'PLANNED'),
        ('SQUID', 'TOBIAS', 'PLANNED'),
        ('SQUID', 'GEORGIA', 'PLANNED'),
        ('TAHINI', 'TOBIAS', 'PLANNED'),
        ('TAMARIND', 'TOBIAS', 'DIFFICULT'),
        ('TAMARIND', 'GEORGIA', 'PLANNED'),
        ('TEMPEH', 'TOBIAS', 'PLANNED'),
        ('TEMPEH', 'GEORGIA', 'PLANNED'),
        ('TUNA', 'TOBIAS', 'PLANNED'),
        ('TUNA', 'GEORGIA', 'PLANNED'),
        ('UDON', 'TOBIAS', 'PLANNED'),
        ('WAKAME', 'TOBIAS', 'PLANNED')
)
UPDATE ingredient_availability ia
SET availability_level = overrides.availability_level,
    updated_at = now()
FROM inserted
JOIN ingredient_concept ic
  ON ic.id = inserted.ingredient_concept_id
JOIN participant p
  ON p.id = inserted.participant_id
JOIN overrides
  ON overrides.concept_code = ic.code
 AND overrides.participant_code = p.code
WHERE ia.ingredient_concept_id = inserted.ingredient_concept_id
  AND ia.participant_id = inserted.participant_id;
