-- Mise en Dice - challenge generation and audit schema
-- Target: PostgreSQL 14+
-- Depends on: 001_catalog_schema.sql
--
-- This migration models generation attempts, curator rounds, candidates,
-- manual overrides and visible challenge history.

-- ---------------------------------------------------------------------------
-- Challenge generation and audit history
-- ---------------------------------------------------------------------------

CREATE TABLE challenge_session (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE generation_attempt (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_session_id bigint NOT NULL REFERENCES challenge_session(id) ON DELETE RESTRICT,
    attempt_type        text NOT NULL,
    status              text NOT NULL DEFAULT 'PENDING',
    generator_version   text NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    completed_at        timestamptz,

    CONSTRAINT uq_generation_attempt_type_per_session
        UNIQUE (challenge_session_id, attempt_type),
    CONSTRAINT ck_generation_attempt_type
        CHECK (attempt_type IN ('INITIAL', 'REROLL')),
    CONSTRAINT ck_generation_attempt_status
        CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT ck_generation_attempt_completion
        CHECK (
            (status = 'PENDING' AND completed_at IS NULL)
            OR (status IN ('SUCCEEDED', 'FAILED') AND completed_at IS NOT NULL)
        )
);

CREATE INDEX ix_generation_attempt_session_created
    ON generation_attempt (challenge_session_id, created_at);

CREATE OR REPLACE FUNCTION validate_generation_attempt_order()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.attempt_type = 'REROLL' AND NOT EXISTS (
        SELECT 1
        FROM generation_attempt ga
        WHERE ga.challenge_session_id = NEW.challenge_session_id
          AND ga.attempt_type = 'INITIAL'
          AND ga.id <> COALESCE(NEW.id, -1)
    ) THEN
        RAISE EXCEPTION 'reroll attempt requires an initial attempt in challenge session %',
            NEW.challenge_session_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_generation_attempt_validate_order
BEFORE INSERT OR UPDATE OF challenge_session_id, attempt_type
ON generation_attempt
FOR EACH ROW
EXECUTE FUNCTION validate_generation_attempt_order();

CREATE TABLE generation_manual_requirement (
    id                              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_attempt_id           bigint NOT NULL REFERENCES generation_attempt(id) ON DELETE CASCADE,
    position                        smallint NOT NULL,
    display_text                    text NOT NULL,
    matched_ingredient_concept_id   bigint REFERENCES ingredient_concept(id) ON DELETE RESTRICT,
    created_at                      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_generation_manual_requirement_position
        UNIQUE (generation_attempt_id, position),
    CONSTRAINT ck_generation_manual_requirement_position
        CHECK (position BETWEEN 1 AND 2),
    CONSTRAINT ck_generation_manual_requirement_text
        CHECK (btrim(display_text) <> '')
);

CREATE TABLE curation_round (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_attempt_id   bigint NOT NULL REFERENCES generation_attempt(id) ON DELETE CASCADE,
    round_number            smallint NOT NULL,
    curator_model           text NOT NULL,
    prompt_version          text NOT NULL,
    status                  text NOT NULL DEFAULT 'PENDING',
    request_payload         jsonb,
    response_payload        jsonb,
    created_at              timestamptz NOT NULL DEFAULT now(),
    completed_at            timestamptz,

    CONSTRAINT uq_curation_round_number
        UNIQUE (generation_attempt_id, round_number),
    CONSTRAINT ck_curation_round_number
        CHECK (round_number > 0),
    CONSTRAINT ck_curation_round_status
        CHECK (status IN ('PENDING', 'SELECTED', 'REJECTED_ALL', 'ERROR')),
    CONSTRAINT ck_curation_round_completion
        CHECK (
            (status = 'PENDING' AND completed_at IS NULL)
            OR (status IN ('SELECTED', 'REJECTED_ALL', 'ERROR') AND completed_at IS NOT NULL)
        )
);

CREATE INDEX ix_curation_round_attempt_created
    ON curation_round (generation_attempt_id, created_at);

CREATE TABLE challenge_candidate (
    id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curation_round_id           bigint NOT NULL REFERENCES curation_round(id) ON DELETE CASCADE,
    candidate_number            smallint NOT NULL,
    exclusion_rule_id           bigint REFERENCES exclusion_rule(id) ON DELETE RESTRICT,
    exclusion_text_snapshot     text,
    curator_evaluation          jsonb,
    is_selected                 boolean NOT NULL DEFAULT false,
    created_at                  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_challenge_candidate_number
        UNIQUE (curation_round_id, candidate_number),
    CONSTRAINT ck_challenge_candidate_number
        CHECK (candidate_number > 0),
    CONSTRAINT ck_challenge_candidate_exclusion_snapshot
        CHECK (
            (exclusion_rule_id IS NULL AND exclusion_text_snapshot IS NULL)
            OR (exclusion_rule_id IS NOT NULL AND exclusion_text_snapshot IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_challenge_candidate_selected_per_round
    ON challenge_candidate (curation_round_id)
    WHERE is_selected;

CREATE TABLE candidate_requirement (
    candidate_id                   bigint NOT NULL REFERENCES challenge_candidate(id) ON DELETE CASCADE,
    position                       smallint NOT NULL,
    source                         text NOT NULL,
    ingredient_concept_id          bigint REFERENCES ingredient_concept(id) ON DELETE RESTRICT,
    manual_requirement_id          bigint REFERENCES generation_manual_requirement(id) ON DELETE RESTRICT,
    challenge_specificity_snapshot text,
    display_text_snapshot          text NOT NULL,

    PRIMARY KEY (candidate_id, position),
    CONSTRAINT ck_candidate_requirement_position
        CHECK (position BETWEEN 1 AND 4),
    CONSTRAINT ck_candidate_requirement_text
        CHECK (btrim(display_text_snapshot) <> ''),
    CONSTRAINT ck_candidate_requirement_source
        CHECK (source IN ('RANDOM', 'MANUAL')),
    CONSTRAINT ck_candidate_requirement_specificity_snapshot
        CHECK (
            challenge_specificity_snapshot IS NULL
            OR challenge_specificity_snapshot IN ('SPECIFIC', 'OPEN')
        ),
    CONSTRAINT ck_candidate_requirement_source_reference
        CHECK (
            (
                source = 'RANDOM'
                AND ingredient_concept_id IS NOT NULL
                AND manual_requirement_id IS NULL
                AND challenge_specificity_snapshot IS NOT NULL
            )
            OR
            (source = 'MANUAL' AND ingredient_concept_id IS NULL AND manual_requirement_id IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uq_candidate_requirement_random_concept
    ON candidate_requirement (candidate_id, ingredient_concept_id)
    WHERE source = 'RANDOM';

CREATE INDEX ix_candidate_requirement_concept
    ON candidate_requirement (ingredient_concept_id)
    WHERE ingredient_concept_id IS NOT NULL;

CREATE INDEX ix_candidate_requirement_manual
    ON candidate_requirement (manual_requirement_id)
    WHERE manual_requirement_id IS NOT NULL;

CREATE OR REPLACE FUNCTION validate_candidate_requirement_context()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    candidate_attempt_id bigint;
    manual_attempt_id bigint;
BEGIN
    SELECT cr.generation_attempt_id
      INTO candidate_attempt_id
      FROM challenge_candidate cc
      JOIN curation_round cr ON cr.id = cc.curation_round_id
     WHERE cc.id = NEW.candidate_id;

    IF candidate_attempt_id IS NULL THEN
        RAISE EXCEPTION 'candidate % does not exist', NEW.candidate_id;
    END IF;

    IF NEW.source = 'MANUAL' THEN
        SELECT gmr.generation_attempt_id
          INTO manual_attempt_id
          FROM generation_manual_requirement gmr
         WHERE gmr.id = NEW.manual_requirement_id;

        IF manual_attempt_id IS NULL THEN
            RAISE EXCEPTION 'manual requirement % does not exist', NEW.manual_requirement_id;
        END IF;

        IF manual_attempt_id <> candidate_attempt_id THEN
            RAISE EXCEPTION 'manual requirement % does not belong to candidate generation attempt %',
                NEW.manual_requirement_id, candidate_attempt_id;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_candidate_requirement_validate_context
BEFORE INSERT OR UPDATE OF candidate_id, source, manual_requirement_id
ON candidate_requirement
FOR EACH ROW
EXECUTE FUNCTION validate_candidate_requirement_context();

CREATE TABLE challenge (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_attempt_id   bigint NOT NULL UNIQUE REFERENCES generation_attempt(id) ON DELETE RESTRICT,
    selected_candidate_id   bigint NOT NULL UNIQUE REFERENCES challenge_candidate(id) ON DELETE RESTRICT,
    status                  text NOT NULL DEFAULT 'ACTIVE',
    shown_at                timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_challenge_status
        CHECK (status IN ('ACTIVE', 'REROLLED', 'COMPLETED', 'ABANDONED'))
);

CREATE OR REPLACE FUNCTION validate_challenge_selected_candidate()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    candidate_attempt_id bigint;
    candidate_is_selected boolean;
BEGIN
    SELECT cr.generation_attempt_id, cc.is_selected
      INTO candidate_attempt_id, candidate_is_selected
      FROM challenge_candidate cc
      JOIN curation_round cr ON cr.id = cc.curation_round_id
     WHERE cc.id = NEW.selected_candidate_id;

    IF candidate_attempt_id IS NULL THEN
        RAISE EXCEPTION 'selected challenge candidate % does not exist', NEW.selected_candidate_id;
    END IF;

    IF candidate_attempt_id <> NEW.generation_attempt_id THEN
        RAISE EXCEPTION 'selected candidate % does not belong to generation attempt %',
            NEW.selected_candidate_id, NEW.generation_attempt_id;
    END IF;

    IF NOT candidate_is_selected THEN
        RAISE EXCEPTION 'candidate % is not marked as selected', NEW.selected_candidate_id;
    END IF;

    IF (
        SELECT count(*)
        FROM candidate_requirement cr
        WHERE cr.candidate_id = NEW.selected_candidate_id
    ) <> 4 THEN
        RAISE EXCEPTION 'selected candidate % must contain exactly four requirements',
            NEW.selected_candidate_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_challenge_validate_selected_candidate
BEFORE INSERT OR UPDATE OF generation_attempt_id, selected_candidate_id
ON challenge
FOR EACH ROW
EXECUTE FUNCTION validate_challenge_selected_candidate();