--liquibase formatted sql
--changeset venomenon328:002-ingredient-catalog splitStatements:false

-- Mise en Dice - initial curated ingredient catalog
-- Requires: schema/001-catalog-schema.sql
-- Requires: reference/001-reference-data.sql
--
-- The catalog is intentionally curated and incomplete. Missing refinements are
-- not forbidden cooking choices; they are simply not system knowledge yet.

INSERT INTO ingredient_concept (
    code,
    display_name,
    active,
    random_draw_enabled,
    challenge_specificity,
    base_draw_weight,
    novelty_level,
    curator_note
)
VALUES
    ('FISH', 'Fisch', true, true, 'OPEN', 0.8000, 1, NULL),
    ('WHITE_FISH', 'weißfleischiger Fisch', true, true, 'OPEN', 0.7000, 1, NULL),
    ('OILY_FISH', 'fettreicher Fisch', true, true, 'OPEN', 0.6500, 2, NULL),
    ('SHELLFISH', 'Schalen- und Krustentiere', true, true, 'OPEN', 0.6500, 2, NULL),
    ('POULTRY', 'Geflügel', true, true, 'OPEN', 0.7500, 1, NULL),
    ('LEGUMES', 'Hülsenfrüchte', true, true, 'OPEN', 0.8000, 1, NULL),
    ('CABBAGE_VEGETABLES', 'Kohlgemüse', true, true, 'OPEN', 0.8000, 1, NULL),
    ('ROOT_VEGETABLES', 'Wurzelgemüse', true, true, 'OPEN', 0.8000, 1, NULL),
    ('LEAFY_GREENS', 'Blattgemüse', true, true, 'OPEN', 0.7500, 1, NULL),
    ('MUSHROOMS', 'Pilze', true, true, 'OPEN', 0.7500, 1, NULL),
    ('CITRUS_FRUIT', 'Zitrusfrucht', true, true, 'OPEN', 0.8000, 1, NULL),
    ('STONE_FRUIT', 'Steinobst', true, true, 'OPEN', 0.6500, 1, NULL),
    ('BERRIES', 'Beeren', true, true, 'OPEN', 0.6500, 1, NULL),
    ('FRESH_HERBS', 'frische Kräuter', true, true, 'OPEN', 0.6500, 1, NULL),
    ('CHEESE', 'Käse', true, true, 'OPEN', 0.6500, 1, NULL),
    ('NOODLES', 'Nudeln', true, true, 'OPEN', 0.7500, 1, NULL),
    ('NUTS', 'Nüsse', true, true, 'OPEN', 0.6500, 1, NULL),
    ('SEAWEED', 'Algen', true, true, 'OPEN', 0.5000, 3, 'Essbare Meeresalgen; konkrete Arten und Produkte können geschmacklich stark variieren.'),
    ('DAIRY_PRODUCTS', 'Milchprodukte', true, false, 'OPEN', 1.0000, 1, 'Interner Gruppenknoten für kuratierte Ausschlussregeln.'),
    ('READY_CURRY_PASTE', 'fertige Currypaste', true, false, 'OPEN', 1.0000, 2, 'Interner Gruppenknoten für kuratierte Ausschlussregeln.'),
    ('COD', 'Kabeljau', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('POLLOCK', 'Seelachs', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('SALMON', 'Lachs', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('MACKEREL', 'Makrele', true, true, 'SPECIFIC', 0.8500, 2, NULL),
    ('TROUT', 'Forelle', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('TUNA', 'Thunfisch', true, true, 'SPECIFIC', 0.7500, 2, 'Gemeint ist Thunfisch als eigenständige Kochzutat, nicht zwingend Dosenware.'),
    ('SHRIMP', 'Garnelen', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('MUSSELS', 'Miesmuscheln', true, true, 'SPECIFIC', 0.7500, 2, NULL),
    ('SQUID', 'Tintenfisch', true, true, 'SPECIFIC', 0.6500, 3, NULL),
    ('SCALLOPS', 'Jakobsmuscheln', true, true, 'SPECIFIC', 0.4500, 4, NULL),
    ('CHICKEN', 'Hähnchen', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('CHICKEN_BREAST', 'Hähnchenbrust', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('CHICKEN_THIGH', 'Hähnchenschenkel', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('DUCK_BREAST', 'Entenbrust', true, true, 'SPECIFIC', 0.7000, 2, NULL),
    ('PORK_BELLY', 'Schweinebauch', true, true, 'SPECIFIC', 0.8000, 2, NULL),
    ('PORK_TENDERLOIN', 'Schweinefilet', true, true, 'SPECIFIC', 0.8500, 1, NULL),
    ('BEEF_MINCE', 'Rinderhack', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('BEEF_GOULASH', 'Rindergulasch', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('BEEF_STEAK', 'Rindersteak', true, true, 'SPECIFIC', 0.7500, 1, NULL),
    ('LAMB', 'Lamm', true, true, 'SPECIFIC', 0.6500, 2, NULL),
    ('EGG', 'Ei', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('BACON', 'Bacon', true, true, 'SPECIFIC', 0.6500, 2, NULL),
    ('ESCARGOT', 'Weinbergschnecken', true, true, 'SPECIFIC', 0.2000, 5, 'In Deutschland typischerweise als konservierte oder tiefgekühlte Spezialzutat beschaffbar.'),
    ('TOFU', 'Tofu', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('TEMPEH', 'Tempeh', true, true, 'SPECIFIC', 0.7500, 2, 'Fermentiertes Sojaprodukt mit festem Biss und nussigem Aroma.'),
    ('CHICKPEAS', 'Kichererbsen', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('LENTILS', 'Linsen', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('KIDNEY_BEANS', 'Kidneybohnen', true, true, 'SPECIFIC', 0.8500, 1, NULL),
    ('WHITE_BEANS', 'weiße Bohnen', true, true, 'SPECIFIC', 0.8500, 1, NULL),
    ('EDAMAME', 'Edamame', true, true, 'SPECIFIC', 0.7500, 2, NULL),
    ('SEITAN', 'Seitan', true, true, 'SPECIFIC', 0.5500, 3, 'Proteinreiches Produkt auf Basis von Weizengluten.'),
    ('POINTED_CABBAGE', 'Spitzkohl', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('SAVOY_CABBAGE', 'Wirsing', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('RED_CABBAGE', 'Rotkohl', true, true, 'SPECIFIC', 0.8500, 1, NULL),
    ('PAK_CHOI', 'Pak Choi', true, true, 'SPECIFIC', 0.9500, 2, NULL),
    ('NAPA_CABBAGE', 'Chinakohl', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('BROCCOLI', 'Brokkoli', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('CAULIFLOWER', 'Blumenkohl', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('BRUSSELS_SPROUTS', 'Rosenkohl', true, true, 'SPECIFIC', 0.8000, 1, NULL),
    ('KALE', 'Grünkohl', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('CARROT', 'Karotte', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('BEETROOT', 'Rote Bete', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('PARSNIP', 'Pastinake', true, true, 'SPECIFIC', 0.7500, 2, NULL),
    ('CELERIAC', 'Knollensellerie', true, true, 'SPECIFIC', 0.8000, 1, NULL),
    ('RADISH', 'Rettich', true, true, 'SPECIFIC', 0.7500, 2, NULL),
    ('SPINACH', 'Spinat', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('LEEK', 'Lauch', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('FENNEL', 'Fenchel', true, true, 'SPECIFIC', 0.8000, 2, NULL),
    ('ASPARAGUS', 'Spargel', true, true, 'SPECIFIC', 0.6000, 1, NULL),
    ('EGGPLANT', 'Aubergine', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('ZUCCHINI', 'Zucchini', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('BELL_PEPPER', 'Paprika', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('CUCUMBER', 'Gurke', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('TOMATO', 'Tomate', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('CORN', 'Mais', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('GREEN_BEANS', 'grüne Bohnen', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('OKRA', 'Okra', true, true, 'SPECIFIC', 0.5000, 3, 'Die Schoten entwickeln beim Garen eine charakteristische Bindung.'),
    ('PUMPKIN', 'Kürbis', true, true, 'SPECIFIC', 0.7500, 1, NULL),
    ('CHAMPIGNON', 'frische Champignons', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('OYSTER_MUSHROOM', 'Austernpilze', true, true, 'SPECIFIC', 0.8000, 2, NULL),
    ('SHIITAKE', 'Shiitake', true, true, 'SPECIFIC', 0.8000, 2, NULL),
    ('BAMBOO_SHOOTS', 'Bambussprossen', true, true, 'SPECIFIC', 0.5500, 3, 'Als Kochzutat in Deutschland meist konserviert erhältlich.'),
    ('ARTICHOKE', 'Artischocke', true, true, 'SPECIFIC', 0.6000, 2, NULL),
    ('APPLE', 'Apfel', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('PEAR', 'Birne', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('LEMON', 'Zitrone', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('LIME', 'Limette', true, true, 'SPECIFIC', 0.9500, 1, NULL),
    ('ORANGE', 'Orange', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('GRAPEFRUIT', 'Grapefruit', true, true, 'SPECIFIC', 0.7000, 2, NULL),
    ('MANGO', 'Mango', true, true, 'SPECIFIC', 0.9000, 2, NULL),
    ('PINEAPPLE', 'Ananas', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('BANANA', 'Banane', true, true, 'SPECIFIC', 0.7500, 1, NULL),
    ('PEACH', 'Pfirsich', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('PLUM', 'Pflaume', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('APRICOT', 'Aprikose', true, true, 'SPECIFIC', 0.5500, 2, NULL),
    ('STRAWBERRY', 'Erdbeere', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('RASPBERRY', 'Himbeere', true, true, 'SPECIFIC', 0.5500, 2, NULL),
    ('BLUEBERRY', 'Heidelbeere', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('GRAPE', 'Weintrauben', true, true, 'SPECIFIC', 0.7500, 1, NULL),
    ('POMEGRANATE', 'Granatapfel', true, true, 'SPECIFIC', 0.6000, 2, NULL),
    ('PASSION_FRUIT', 'Passionsfrucht', true, true, 'SPECIFIC', 0.5000, 3, NULL),
    ('POTATO', 'Kartoffel', true, true, 'SPECIFIC', 1.0000, 1, NULL),
    ('SWEET_POTATO', 'Süßkartoffel', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('RICE', 'Reis', true, true, 'SPECIFIC', 0.9000, 1, NULL),
    ('RICE_NOODLES', 'Reisnudeln', true, true, 'SPECIFIC', 0.8000, 2, NULL),
    ('UDON', 'Udon', true, true, 'SPECIFIC', 0.6500, 2, NULL),
    ('SOBA', 'Soba', true, true, 'SPECIFIC', 0.5500, 3, 'Japanische Nudeln, typischerweise ganz oder teilweise aus Buchweizen.'),
    ('COUSCOUS', 'Couscous', true, true, 'SPECIFIC', 0.8000, 1, NULL),
    ('BULGUR', 'Bulgur', true, true, 'SPECIFIC', 0.7000, 1, NULL),
    ('POLENTA', 'Polenta', true, true, 'SPECIFIC', 0.6500, 2, NULL),
    ('ONION', 'Zwiebel', true, true, 'SPECIFIC', 0.7500, 1, NULL),
    ('GARLIC', 'Knoblauch', true, true, 'SPECIFIC', 0.7500, 1, NULL),
    ('GINGER', 'Ingwer', true, true, 'SPECIFIC', 0.8500, 1, NULL),
    ('LEMONGRASS', 'Zitronengras', true, true, 'SPECIFIC', 0.6500, 2, NULL),
    ('CHILI', 'Chili', true, true, 'SPECIFIC', 0.8500, 1, NULL),
    ('JALAPENO', 'Jalapeño', true, true, 'SPECIFIC', 0.6500, 2, NULL),
    ('HABANERO', 'Habanero', true, true, 'SPECIFIC', 0.4500, 3, NULL),
    ('SPRING_ONION', 'Frühlingszwiebel', true, true, 'SPECIFIC', 0.8500, 1, NULL),
    ('CILANTRO', 'Koriandergrün', true, true, 'SPECIFIC', 0.7000, 2, NULL),
    ('PARSLEY', 'Petersilie', true, true, 'SPECIFIC', 0.7000, 1, NULL),
    ('BASIL', 'Basilikum', true, true, 'SPECIFIC', 0.7000, 1, NULL),
    ('MINT', 'Minze', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('DILL', 'Dill', true, true, 'SPECIFIC', 0.6000, 1, NULL),
    ('MISO', 'Miso', true, true, 'SPECIFIC', 0.7500, 2, 'Fermentierte Würzpaste; konkrete Miso-Sorten werden für die Challenge nicht getrennt modelliert.'),
    ('SOY_SAUCE', 'Sojasauce', true, true, 'SPECIFIC', 0.7000, 1, NULL),
    ('FISH_SAUCE', 'Fischsauce', true, true, 'SPECIFIC', 0.6000, 2, NULL),
    ('OYSTER_SAUCE', 'Austernsauce', true, true, 'SPECIFIC', 0.6000, 2, NULL),
    ('GOCHUJANG', 'Gochujang', true, true, 'SPECIFIC', 0.6500, 2, 'Fermentierte koreanische Chilipaste.'),
    ('SAMBAL', 'Sambal', true, true, 'SPECIFIC', 0.6500, 2, 'Chilipaste beziehungsweise Chilisauce; konkrete Sambal-Varianten werden nicht getrennt modelliert.'),
    ('COCONUT_MILK', 'Kokosmilch', true, true, 'SPECIFIC', 0.7500, 1, NULL),
    ('TAHINI', 'Tahini', true, true, 'SPECIFIC', 0.6500, 2, NULL),
    ('PEANUT_BUTTER', 'Erdnussbutter', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('MUSTARD', 'Senf', true, true, 'SPECIFIC', 0.7000, 1, NULL),
    ('HORSERADISH', 'Meerrettich', true, true, 'SPECIFIC', 0.5500, 2, NULL),
    ('TOMATO_PASTE', 'Tomatenmark', true, true, 'SPECIFIC', 0.7000, 1, NULL),
    ('HONEY', 'Honig', true, true, 'SPECIFIC', 0.6000, 1, NULL),
    ('RICE_VINEGAR', 'Reisessig', true, true, 'SPECIFIC', 0.5500, 2, NULL),
    ('BALSAMIC_VINEGAR', 'Balsamico', true, true, 'SPECIFIC', 0.5500, 1, NULL),
    ('TAMARIND', 'Tamarinde', true, true, 'SPECIFIC', 0.4000, 4, 'Säuerliche Frucht, in Deutschland für die Küche meist als Paste, Block oder Konzentrat erhältlich.'),
    ('CAPERS', 'Kapern', true, true, 'SPECIFIC', 0.5500, 2, NULL),
    ('OLIVES', 'Oliven', true, true, 'SPECIFIC', 0.6000, 1, NULL),
    ('BLACK_GARLIC', 'schwarzer Knoblauch', true, true, 'SPECIFIC', 0.3500, 4, 'Fermentativ gereifter Knoblauch mit süßlich-würzigem, deutlich umamireichem Profil.'),
    ('KIMCHI', 'Kimchi', true, true, 'SPECIFIC', 0.5500, 3, NULL),
    ('SAUERKRAUT', 'Sauerkraut', true, true, 'SPECIFIC', 0.5500, 1, NULL),
    ('YOGURT', 'Joghurt', true, true, 'SPECIFIC', 0.7500, 1, NULL),
    ('CREAM', 'Sahne', true, true, 'SPECIFIC', 0.7000, 1, NULL),
    ('FETA', 'Feta', true, true, 'SPECIFIC', 0.7000, 1, NULL),
    ('PARMESAN', 'Parmesan', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('BLUE_CHEESE', 'Blauschimmelkäse', true, true, 'SPECIFIC', 0.4500, 2, NULL),
    ('PEANUT', 'Erdnüsse', true, true, 'SPECIFIC', 0.7000, 1, NULL),
    ('CASHEW', 'Cashewkerne', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('ALMOND', 'Mandeln', true, true, 'SPECIFIC', 0.6500, 1, NULL),
    ('WALNUT', 'Walnüsse', true, true, 'SPECIFIC', 0.6000, 1, NULL),
    ('NORI', 'Nori', true, true, 'SPECIFIC', 0.5000, 3, NULL),
    ('WAKAME', 'Wakame', true, true, 'SPECIFIC', 0.4500, 3, NULL)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ingredient_refinement (parent_concept_id, child_concept_id)
SELECT parent.id, child.id
FROM (
    VALUES
        ('FISH', 'WHITE_FISH'),
        ('FISH', 'OILY_FISH'),
        ('WHITE_FISH', 'COD'),
        ('WHITE_FISH', 'POLLOCK'),
        ('OILY_FISH', 'SALMON'),
        ('OILY_FISH', 'MACKEREL'),
        ('OILY_FISH', 'TROUT'),
        ('FISH', 'TUNA'),
        ('SHELLFISH', 'SHRIMP'),
        ('SHELLFISH', 'MUSSELS'),
        ('SHELLFISH', 'SCALLOPS'),
        ('POULTRY', 'CHICKEN'),
        ('POULTRY', 'DUCK_BREAST'),
        ('CHICKEN', 'CHICKEN_BREAST'),
        ('CHICKEN', 'CHICKEN_THIGH'),
        ('LEGUMES', 'CHICKPEAS'),
        ('LEGUMES', 'LENTILS'),
        ('LEGUMES', 'KIDNEY_BEANS'),
        ('LEGUMES', 'WHITE_BEANS'),
        ('LEGUMES', 'EDAMAME'),
        ('CABBAGE_VEGETABLES', 'POINTED_CABBAGE'),
        ('CABBAGE_VEGETABLES', 'SAVOY_CABBAGE'),
        ('CABBAGE_VEGETABLES', 'RED_CABBAGE'),
        ('CABBAGE_VEGETABLES', 'PAK_CHOI'),
        ('CABBAGE_VEGETABLES', 'NAPA_CABBAGE'),
        ('CABBAGE_VEGETABLES', 'BROCCOLI'),
        ('CABBAGE_VEGETABLES', 'CAULIFLOWER'),
        ('CABBAGE_VEGETABLES', 'BRUSSELS_SPROUTS'),
        ('CABBAGE_VEGETABLES', 'KALE'),
        ('ROOT_VEGETABLES', 'CARROT'),
        ('ROOT_VEGETABLES', 'BEETROOT'),
        ('ROOT_VEGETABLES', 'PARSNIP'),
        ('ROOT_VEGETABLES', 'CELERIAC'),
        ('ROOT_VEGETABLES', 'RADISH'),
        ('LEAFY_GREENS', 'SPINACH'),
        ('LEAFY_GREENS', 'KALE'),
        ('LEAFY_GREENS', 'PAK_CHOI'),
        ('MUSHROOMS', 'CHAMPIGNON'),
        ('MUSHROOMS', 'OYSTER_MUSHROOM'),
        ('MUSHROOMS', 'SHIITAKE'),
        ('CITRUS_FRUIT', 'LEMON'),
        ('CITRUS_FRUIT', 'LIME'),
        ('CITRUS_FRUIT', 'ORANGE'),
        ('CITRUS_FRUIT', 'GRAPEFRUIT'),
        ('STONE_FRUIT', 'PEACH'),
        ('STONE_FRUIT', 'PLUM'),
        ('STONE_FRUIT', 'APRICOT'),
        ('BERRIES', 'STRAWBERRY'),
        ('BERRIES', 'RASPBERRY'),
        ('BERRIES', 'BLUEBERRY'),
        ('FRESH_HERBS', 'CILANTRO'),
        ('FRESH_HERBS', 'PARSLEY'),
        ('FRESH_HERBS', 'BASIL'),
        ('FRESH_HERBS', 'MINT'),
        ('FRESH_HERBS', 'DILL'),
        ('NOODLES', 'RICE_NOODLES'),
        ('NOODLES', 'UDON'),
        ('NOODLES', 'SOBA'),
        ('CHEESE', 'FETA'),
        ('CHEESE', 'PARMESAN'),
        ('CHEESE', 'BLUE_CHEESE'),
        ('DAIRY_PRODUCTS', 'YOGURT'),
        ('DAIRY_PRODUCTS', 'CREAM'),
        ('DAIRY_PRODUCTS', 'CHEESE'),
        ('NUTS', 'PEANUT'),
        ('NUTS', 'CASHEW'),
        ('NUTS', 'ALMOND'),
        ('NUTS', 'WALNUT'),
        ('SEAWEED', 'NORI'),
        ('SEAWEED', 'WAKAME'),
        ('CHILI', 'JALAPENO'),
        ('CHILI', 'HABANERO')
) AS relation(parent_code, child_code)
JOIN ingredient_concept parent ON parent.code = relation.parent_code
JOIN ingredient_concept child ON child.code = relation.child_code
ON CONFLICT (parent_concept_id, child_concept_id) DO NOTHING;
