--liquibase formatted sql
--changeset venomenon328:005-culinary-properties splitStatements:false

-- Mise en Dice - initial culinary metadata
-- Requires: schema/001-catalog-schema.sql
-- Requires: reference/001-reference-data.sql
-- Requires: catalog/002-ingredient-catalog.sql
--
-- Culinary metadata is intentionally sparse. Missing values mean "not curated
-- yet / not relevant", not the lowest level.

INSERT INTO ingredient_culinary_flag (ingredient_concept_id, culinary_flag_id)
SELECT ic.id, cf.id
FROM (
    VALUES
        ('BACON', 'CURED'),
        ('BLACK_GARLIC', 'FERMENTED'),
        ('BLUE_CHEESE', 'FERMENTED'),
        ('CAPERS', 'PICKLED'),
        ('FISH_SAUCE', 'FERMENTED'),
        ('GOCHUJANG', 'FERMENTED'),
        ('KIMCHI', 'FERMENTED'),
        ('KIMCHI', 'PICKLED'),
        ('MISO', 'FERMENTED'),
        ('NORI', 'DRIED'),
        ('OLIVES', 'PICKLED'),
        ('PARMESAN', 'CURED'),
        ('PARMESAN', 'FERMENTED'),
        ('SAUERKRAUT', 'FERMENTED'),
        ('SAUERKRAUT', 'PICKLED'),
        ('SOY_SAUCE', 'FERMENTED'),
        ('TEMPEH', 'FERMENTED'),
        ('WAKAME', 'DRIED'),
        ('YOGURT', 'FERMENTED')
) AS assignment(concept_code, flag_code)
JOIN ingredient_concept ic ON ic.code = assignment.concept_code
JOIN culinary_flag cf ON cf.code = assignment.flag_code
ON CONFLICT (ingredient_concept_id, culinary_flag_id) DO NOTHING;

INSERT INTO ingredient_culinary_dimension (
    ingredient_concept_id,
    culinary_dimension_id,
    level
)
SELECT ic.id, cd.id, assignment.level
FROM (
    VALUES
        ('ALMOND', 'FATTINESS', 4),
        ('APPLE', 'ACIDITY', 2),
        ('APPLE', 'SWEETNESS', 3),
        ('BACON', 'DOMINANCE', 4),
        ('BACON', 'FATTINESS', 5),
        ('BACON', 'UMAMI', 4),
        ('BALSAMIC_VINEGAR', 'ACIDITY', 4),
        ('BALSAMIC_VINEGAR', 'DOMINANCE', 4),
        ('BALSAMIC_VINEGAR', 'SWEETNESS', 3),
        ('BANANA', 'DOMINANCE', 4),
        ('BANANA', 'SWEETNESS', 4),
        ('BEETROOT', 'DOMINANCE', 3),
        ('BEETROOT', 'SWEETNESS', 3),
        ('BLACK_GARLIC', 'DOMINANCE', 4),
        ('BLACK_GARLIC', 'SWEETNESS', 3),
        ('BLACK_GARLIC', 'UMAMI', 5),
        ('BLUE_CHEESE', 'DOMINANCE', 5),
        ('BLUE_CHEESE', 'FATTINESS', 4),
        ('BLUE_CHEESE', 'UMAMI', 5),
        ('CAPERS', 'ACIDITY', 3),
        ('CAPERS', 'DOMINANCE', 4),
        ('CAPERS', 'UMAMI', 3),
        ('CASHEW', 'FATTINESS', 4),
        ('CASHEW', 'SWEETNESS', 2),
        ('CHILI', 'DOMINANCE', 3),
        ('CHILI', 'HEAT', 3),
        ('CILANTRO', 'DOMINANCE', 4),
        ('COCONUT_MILK', 'DOMINANCE', 3),
        ('COCONUT_MILK', 'FATTINESS', 4),
        ('COCONUT_MILK', 'SWEETNESS', 2),
        ('CREAM', 'DOMINANCE', 2),
        ('CREAM', 'FATTINESS', 5),
        ('DILL', 'DOMINANCE', 4),
        ('ESCARGOT', 'DOMINANCE', 2),
        ('ESCARGOT', 'UMAMI', 3),
        ('FENNEL', 'DOMINANCE', 4),
        ('FENNEL', 'SWEETNESS', 2),
        ('FETA', 'ACIDITY', 2),
        ('FETA', 'DOMINANCE', 4),
        ('FETA', 'FATTINESS', 3),
        ('FETA', 'UMAMI', 4),
        ('FISH_SAUCE', 'DOMINANCE', 5),
        ('FISH_SAUCE', 'UMAMI', 5),
        ('GARLIC', 'DOMINANCE', 4),
        ('GARLIC', 'UMAMI', 2),
        ('GINGER', 'DOMINANCE', 4),
        ('GINGER', 'HEAT', 2),
        ('GOCHUJANG', 'DOMINANCE', 4),
        ('GOCHUJANG', 'HEAT', 3),
        ('GOCHUJANG', 'SWEETNESS', 3),
        ('GOCHUJANG', 'UMAMI', 4),
        ('GRAPEFRUIT', 'ACIDITY', 4),
        ('GRAPEFRUIT', 'BITTERNESS', 4),
        ('GRAPEFRUIT', 'DOMINANCE', 4),
        ('HABANERO', 'DOMINANCE', 5),
        ('HABANERO', 'HEAT', 5),
        ('HONEY', 'DOMINANCE', 3),
        ('HONEY', 'SWEETNESS', 5),
        ('HORSERADISH', 'DOMINANCE', 5),
        ('HORSERADISH', 'HEAT', 4),
        ('JALAPENO', 'DOMINANCE', 3),
        ('JALAPENO', 'HEAT', 2),
        ('KALE', 'BITTERNESS', 2),
        ('KIMCHI', 'ACIDITY', 3),
        ('KIMCHI', 'DOMINANCE', 5),
        ('KIMCHI', 'HEAT', 3),
        ('KIMCHI', 'UMAMI', 4),
        ('LEMON', 'ACIDITY', 5),
        ('LEMON', 'DOMINANCE', 4),
        ('LEMONGRASS', 'DOMINANCE', 4),
        ('LIME', 'ACIDITY', 5),
        ('LIME', 'DOMINANCE', 4),
        ('MACKEREL', 'DOMINANCE', 4),
        ('MACKEREL', 'FATTINESS', 4),
        ('MACKEREL', 'UMAMI', 4),
        ('MANGO', 'DOMINANCE', 3),
        ('MANGO', 'SWEETNESS', 4),
        ('MINT', 'DOMINANCE', 4),
        ('MISO', 'DOMINANCE', 4),
        ('MISO', 'SWEETNESS', 2),
        ('MISO', 'UMAMI', 5),
        ('MUSSELS', 'DOMINANCE', 3),
        ('MUSSELS', 'UMAMI', 4),
        ('MUSTARD', 'ACIDITY', 2),
        ('MUSTARD', 'DOMINANCE', 4),
        ('MUSTARD', 'HEAT', 2),
        ('NORI', 'DOMINANCE', 4),
        ('NORI', 'UMAMI', 5),
        ('OLIVES', 'BITTERNESS', 2),
        ('OLIVES', 'DOMINANCE', 4),
        ('OLIVES', 'UMAMI', 3),
        ('ORANGE', 'ACIDITY', 3),
        ('ORANGE', 'SWEETNESS', 3),
        ('OYSTER_SAUCE', 'DOMINANCE', 4),
        ('OYSTER_SAUCE', 'SWEETNESS', 2),
        ('OYSTER_SAUCE', 'UMAMI', 5),
        ('PARMESAN', 'DOMINANCE', 4),
        ('PARMESAN', 'FATTINESS', 3),
        ('PARMESAN', 'UMAMI', 5),
        ('PASSION_FRUIT', 'ACIDITY', 4),
        ('PASSION_FRUIT', 'DOMINANCE', 4),
        ('PASSION_FRUIT', 'SWEETNESS', 3),
        ('PEANUT', 'FATTINESS', 4),
        ('PEANUT', 'UMAMI', 2),
        ('PEANUT_BUTTER', 'DOMINANCE', 4),
        ('PEANUT_BUTTER', 'FATTINESS', 5),
        ('PEANUT_BUTTER', 'SWEETNESS', 2),
        ('PEAR', 'SWEETNESS', 3),
        ('PINEAPPLE', 'ACIDITY', 3),
        ('PINEAPPLE', 'DOMINANCE', 3),
        ('PINEAPPLE', 'SWEETNESS', 4),
        ('POMEGRANATE', 'ACIDITY', 3),
        ('POMEGRANATE', 'SWEETNESS', 3),
        ('PORK_BELLY', 'FATTINESS', 5),
        ('PORK_BELLY', 'UMAMI', 3),
        ('RADISH', 'DOMINANCE', 3),
        ('RADISH', 'HEAT', 2),
        ('RICE_VINEGAR', 'ACIDITY', 5),
        ('RICE_VINEGAR', 'DOMINANCE', 3),
        ('SALMON', 'FATTINESS', 4),
        ('SALMON', 'UMAMI', 3),
        ('SAMBAL', 'DOMINANCE', 4),
        ('SAMBAL', 'HEAT', 4),
        ('SAUERKRAUT', 'ACIDITY', 4),
        ('SAUERKRAUT', 'DOMINANCE', 4),
        ('SAUERKRAUT', 'UMAMI', 2),
        ('SCALLOPS', 'SWEETNESS', 3),
        ('SCALLOPS', 'UMAMI', 3),
        ('SHRIMP', 'SWEETNESS', 2),
        ('SHRIMP', 'UMAMI', 4),
        ('SOY_SAUCE', 'DOMINANCE', 4),
        ('SOY_SAUCE', 'UMAMI', 5),
        ('SQUID', 'DOMINANCE', 2),
        ('SQUID', 'UMAMI', 3),
        ('TAHINI', 'BITTERNESS', 2),
        ('TAHINI', 'DOMINANCE', 4),
        ('TAHINI', 'FATTINESS', 5),
        ('TAMARIND', 'ACIDITY', 5),
        ('TAMARIND', 'DOMINANCE', 4),
        ('TAMARIND', 'SWEETNESS', 2),
        ('TEMPEH', 'DOMINANCE', 3),
        ('TEMPEH', 'UMAMI', 3),
        ('TOMATO_PASTE', 'ACIDITY', 2),
        ('TOMATO_PASTE', 'DOMINANCE', 4),
        ('TOMATO_PASTE', 'SWEETNESS', 2),
        ('TOMATO_PASTE', 'UMAMI', 4),
        ('TUNA', 'DOMINANCE', 3),
        ('TUNA', 'UMAMI', 3),
        ('WAKAME', 'DOMINANCE', 3),
        ('WAKAME', 'UMAMI', 5),
        ('WALNUT', 'BITTERNESS', 2),
        ('WALNUT', 'DOMINANCE', 3),
        ('WALNUT', 'FATTINESS', 4),
        ('YOGURT', 'ACIDITY', 3),
        ('YOGURT', 'FATTINESS', 2)
) AS assignment(concept_code, dimension_code, level)
JOIN ingredient_concept ic ON ic.code = assignment.concept_code
JOIN culinary_dimension cd ON cd.code = assignment.dimension_code
ON CONFLICT (ingredient_concept_id, culinary_dimension_id) DO NOTHING;
