--liquibase formatted sql
--changeset venomenon328:011-ingredient-refinements-expansion splitStatements:false

-- Mise en Dice - refinement graph for the expanded ingredient catalog
-- Requires: catalog/010-ingredient-catalog-expansion-3.sql
--
-- Relations are inserted only after all new concepts exist. Each manifest line
-- maps one parent to its comma-separated children. This includes links between
-- new concepts and links from new parents to baseline concepts.

INSERT INTO ingredient_refinement (parent_concept_id, child_concept_id)
SELECT parent.id, child.id
FROM regexp_split_to_table($relations$
ALLIUM_VEGETABLES|CHIVES,GARLIC,GARLIC_CHIVES,LEEK,ONION,RED_ONION,SHALLOT,SPRING_ONION
ALMOND|ALMOND_BUTTER
APRICOT|DRIED_APRICOT
ASPARAGUS|GREEN_ASPARAGUS,WHITE_ASPARAGUS
BARLEY|PEARL_BARLEY
BASIL|THAI_BASIL
BEANS|ADZUKI_BEANS,BLACK_BEANS,BLACK_EYED_PEAS,BROAD_BEANS,BUTTER_BEANS,CANNELLINI_BEANS,KIDNEY_BEANS,MUNG_BEANS,PINTO_BEANS,SOYBEANS,WHITE_BEANS
BEEF|BEEF_BRISKET,BEEF_CHEEK,BEEF_GOULASH,BEEF_HEART,BEEF_LIVER,BEEF_MINCE,BEEF_ROAST,BEEF_ROULADE,BEEF_RUMP,BEEF_SHIN,BEEF_SHORT_RIBS,BEEF_STEAK,BEEF_TENDERLOIN,BEEF_TONGUE,BONE_MARROW,OXTAIL,TRIPE
BELL_PEPPER|AJVAR,ROASTED_RED_PEPPER
BERRIES|BLACKBERRY,BLACK_CURRANT,CRANBERRY,ELDERBERRY,GOOSEBERRY,MULBERRY,RED_CURRANT
BIVALVES|CLAMS,MUSSELS,OYSTER,RAZOR_CLAMS,SCALLOPS
BLACK_BEANS|FERMENTED_BLACK_BEANS
BREAD|BAGUETTE,BREADCRUMBS,FLATBREAD,PITA,SOURDOUGH_BREAD,TORTILLA
CABBAGE_VEGETABLES|KOHLRABI,ROMANESCO,WHITE_CABBAGE
CASHEW|CASHEW_BUTTER
CHEESE|CAMEMBERT,CHEDDAR,CREAM_CHEESE,GOAT_CHEESE,GOUDA,GRUYERE,HALLOUMI,MASCARPONE,MOZZARELLA,PANEER,PECORINO,RICOTTA
CHERRY|SOUR_CHERRY
CHICKEN|CHICKEN_DRUMSTICKS,CHICKEN_LIVER,CHICKEN_WINGS
CHICKPEAS|CHICKPEA_FLOUR
CHILI|ANCHO_CHILI,BIRDS_EYE_CHILI,CHILI_FLAKES,CHIPOTLE,GOCHUGARU,POBLANO,SERRANO_CHILI
CHILI_CONDIMENTS|CHILI_CRISP,DOUBANJIANG,GOCHUJANG,HARISSA,LAKSA_PASTE,MOLE_PASTE,SAMBAL,SAMBAL_BRANDAL,SAMBAL_OELEK,SRIRACHA,THAI_GREEN_CURRY_PASTE,THAI_RED_CURRY_PASTE
CITRUS_FRUIT|BLOOD_ORANGE,CALAMANSI,MANDARIN,POMELO,YUZU
COCOA_PRODUCTS|COCOA_POWDER,DARK_CHOCOLATE
COCONUT_PRODUCTS|COCONUT,COCONUT_CREAM,COCONUT_FLAKES,COCONUT_MILK,COCONUT_OIL,COCONUT_WATER
COD|STOCKFISH
COOKING_ALCOHOL|BEER,CIDER,MIRIN,RED_WINE,SAKE,SHAOXING_WINE,SHERRY,WHITE_WINE
COOKING_FATS|BUTTER,DUCK_FAT,GHEE,LARD,OILS
CORN|CORNMEAL,MASA_HARINA
CRAB|ALIGUE
CRUSTACEANS|CRAB,CRAYFISH,LOBSTER,SHRIMP
CUCUMBER|PICKLED_CUCUMBER
CULTURED_DAIRY|BUTTERMILK,CHEESE,CREME_FRAICHE,GREEK_YOGURT,KEFIR,QUARK,SOUR_CREAM,YOGURT
CURED_MEAT|BACON,CHORIZO,COOKED_HAM,NDUJA,PANCETTA,PROSCIUTTO,SALAMI,SERRANO_HAM
DAIRY_PRODUCTS|BUTTER,CONDENSED_MILK,CULTURED_DAIRY,FRESH_DAIRY_PRODUCTS,GHEE
DRIED_FRUIT|DRIED_APRICOT,PRUNE,RAISIN
DUCK|DUCK_BREAST,DUCK_LEG
DUMPLING_WRAPPERS|DUMPLING_DOUGH,RICE_PAPER,WONTON_WRAPPERS
EGGS|DUCK_EGG,EGG,QUAIL_EGG
FERMENTED_SEASONINGS|BAGOONG,BELACAN,DARK_SOY_SAUCE,DOENJANG,DOUBANJIANG,FERMENTED_BLACK_BEANS,FERMENTED_TOFU,FISH_SAUCE,GOCHUJANG,HOISIN_SAUCE,KECAP_MANIS,LIGHT_SOY_SAUCE,MAM_RUOC,MISO,SHRIMP_PASTE,SOY_SAUCE,TAMARI,WORCESTERSHIRE_SAUCE,YEAST_EXTRACT
FERMENTED_TOFU|STINKY_TOFU
FISH|FISH_ROE,PRESERVED_FISH,SWORDFISH
FISH_ROE|SALMON_ROE,TROUT_ROE
FLOUR|CHICKPEA_FLOUR,RICE_FLOUR,RYE_FLOUR,WHEAT_FLOUR
FRESH_DAIRY_PRODUCTS|CREAM,CREAM_CHEESE,EVAPORATED_MILK,MILK,YOGURT
FRESH_HERBS|CHIVES,CURRY_LEAVES,GARLIC_CHIVES,KAFFIR_LIME_LEAVES,LOVAGE,MARJORAM,OREGANO,ROSEMARY,SAGE,TARRAGON,THAI_BASIL,THYME,VIETNAMESE_CORIANDER
FRUIT|BERRIES,CITRUS_FRUIT,DATE,DRIED_FRUIT,FIG,KIWI,MELONS,POME_FRUIT,STONE_FRUIT,TROPICAL_FRUIT
FRUIT_VEGETABLES|BELL_PEPPER,BUTTERNUT_SQUASH,CHERRY_TOMATO,CUCUMBER,EGGPLANT,HOKKAIDO_SQUASH,OKRA,PUMPKIN,SPAGHETTI_SQUASH,TOMATILLO,TOMATO,ZUCCHINI
GAME_MEAT|RABBIT,VENISON,WILD_BOAR
GINGER|PICKLED_GINGER
GRAINS|AMARANTH,BARLEY,BASMATI_RICE,BROWN_RICE,BUCKWHEAT,BULGUR,CORNMEAL,COUSCOUS,FARRO,FLOUR,FREEKEH,JASMINE_RICE,MASA_HARINA,MILLET,OATS,PEARL_BARLEY,POLENTA,QUINOA,RICE,RISOTTO_RICE,SEMOLINA,SPELT,STICKY_RICE,WILD_RICE
GRAPE|RAISIN
GREEN_TEA|MATCHA
LEAFY_GREENS|CHARD,PURSLANE,SALAD_GREENS,WATERCRESS
LEGUMES|BEANS,LUPIN,PEAS,SOY_PRODUCTS
LEMON|PRESERVED_LEMON
LENTILS|BELUGA_LENTILS,RED_LENTILS,YELLOW_LENTILS
MEAT|BEEF,CURED_MEAT,FROG_LEGS,GAME_MEAT,GOAT,LAMB,MINCED_MEAT,OFFAL,PORK,POULTRY,SAUSAGE,VEAL
MELONS|CANTALOUPE,HONEYDEW_MELON,WATERMELON
MINCED_MEAT|BEEF_MINCE,PORK_MINCE,TURKEY_MINCE
MOLLUSCS|BIVALVES,CUTTLEFISH,OCTOPUS,SQUID
MUNG_BEANS|BEAN_SPROUTS
MUSHROOMS|CHANTERELLE,ENOKI,KING_OYSTER_MUSHROOM,MAITAKE,MOREL,PORCINI,SHIMEJI,TRUFFLE,WOOD_EAR
MUSTARD|DIJON_MUSTARD,HOT_MUSTARD,WHOLEGRAIN_MUSTARD
NOODLES|EGG_NOODLES,GLASS_NOODLES,RAMEN_NOODLES,SHIRATAKI,SPAETZLE,WHEAT_NOODLES,WHEAT_PASTA
NUTS|BRAZIL_NUT,CHESTNUT,HAZELNUT,MACADAMIA,PECAN,PINE_NUT,PISTACHIO
NUT_AND_SEED_PASTES|ALMOND_BUTTER,CASHEW_BUTTER,PEANUT_BUTTER,TAHINI
OFFAL|BEEF_HEART,BEEF_LIVER,BEEF_TONGUE,BLOOD_SAUSAGE,BONE_MARROW,CHICKEN_LIVER,PORK_LIVER,PORK_TONGUE,TRIPE,VEAL_LIVER
OILS|COCONUT_OIL,NEUTRAL_OIL,OLIVE_OIL,SESAME_OIL
OILY_FISH|ANCHOVIES,EEL,HERRING,SARDINES
OLIVES|TAPENADE
ONION|RED_ONION
ORANGE|BLOOD_ORANGE
PAPRIKA_POWDER|SMOKED_PAPRIKA
PEAS|EDAMAME,GREEN_PEAS,SPLIT_PEAS,SUGAR_SNAP_PEAS
PLANT_PROTEIN_PRODUCTS|FIRM_TOFU,MYCOPROTEIN,NATTO,NUTRITIONAL_YEAST,SEITAN,SILKEN_TOFU,SMOKED_TOFU,TEMPEH,TOFU,TVP
PLUM|PRUNE
POD_VEGETABLES|BROAD_BEANS,EDAMAME,GREEN_BEANS,GREEN_PEAS,OKRA,SUGAR_SNAP_PEAS
POME_FRUIT|APPLE,PEAR,QUINCE
PORK|BACON,BRATWURST,CHORIZO,COOKED_HAM,NDUJA,PANCETTA,PORK_BELLY,PORK_CHEEK,PORK_CHOP,PORK_CUTLET,PORK_KNUCKLE,PORK_LIVER,PORK_LOIN,PORK_MINCE,PORK_NECK,PORK_RIBS,PORK_SHOULDER,PORK_TENDERLOIN,PORK_TONGUE,PROSCIUTTO,SALAMI,SERRANO_HAM,WHITE_SAUSAGE
PORK_BELLY|PANCETTA
POULTRY|DUCK,GOOSE,QUAIL,TURKEY
PRESERVED_FISH|BONITO_FLAKES,CANNED_SARDINES,CANNED_TUNA,SMOKED_SALMON,SMOKED_TROUT,STOCKFISH,SURIMI
PRESERVED_PRODUCE|AJVAR,KIMCHI,PICKLED_CUCUMBER,PICKLED_GINGER,PRESERVED_LEMON,ROASTED_RED_PEPPER,SAUERKRAUT
PUMPKIN|BUTTERNUT_SQUASH,HOKKAIDO_SQUASH,SPAGHETTI_SQUASH
READY_CURRY_PASTE|LAKSA_PASTE,MASSAMAN_CURRY_PASTE,RENDANG_PASTE,THAI_GREEN_CURRY_PASTE,THAI_RED_CURRY_PASTE,THAI_YELLOW_CURRY_PASTE
RICE|BASMATI_RICE,BROWN_RICE,JASMINE_RICE,RISOTTO_RICE,STICKY_RICE
RICE_PRODUCTS|RICE_CAKES,RICE_FLOUR,RICE_NOODLES,RICE_PAPER,WILD_RICE
ROOT_VEGETABLES|CASSAVA,JERUSALEM_ARTICHOKE,LOTUS_ROOT,RUTABAGA,TARO,TURNIP,UBE,WATER_CHESTNUT,YAM
SALAD_GREENS|ARUGULA,CHICORY,ENDIVE,LAMBS_LETTUCE,LETTUCE,RADICCHIO,ROMAINE_LETTUCE,SPINACH
SALMON|SMOKED_SALMON
SAMBAL|SAMBAL_BRANDAL,SAMBAL_OELEK
SARDINES|CANNED_SARDINES
SAUCES_AND_PASTES|AJVAR,BANANA_KETCHUP,BARBECUE_SAUCE,CHILI_CONDIMENTS,CHILI_CRISP,FERMENTED_SEASONINGS,FISH_SAUCE,HARISSA,HOISIN_SAUCE,KETCHUP,MAYONNAISE,MISO,MOLE_PASTE,MUSTARD,NUT_AND_SEED_PASTES,OYSTER_SAUCE,PEANUT_BUTTER,PESTO,PONZU,READY_CURRY_PASTE,SALSA,SOY_SAUCE,SRIRACHA,TAHINI,TAPENADE,TERIYAKI_SAUCE,TOMATO_PASTE,TOMATO_PRODUCTS,WORCESTERSHIRE_SAUCE,XO_SAUCE
SAUSAGE|BLOOD_SAUSAGE,BRATWURST,CHORIZO,MERGUEZ,NDUJA,SALAMI,WHITE_SAUSAGE
SEAFOOD|CRUSTACEANS,FISH,MOLLUSCS,SHELLFISH
SEAWEED|DULSE,HIJIKI,KOMBU
SEEDS|CHIA_SEEDS,EGUSI_SEEDS,FLAXSEED,HEMP_SEEDS,PINE_NUT,POPPY_SEEDS,PUMPKIN_SEEDS,SESAME_SEEDS,SUNFLOWER_SEEDS
SHELLFISH|BIVALVES,CRUSTACEANS
SHRIMP|SHRIMP_PASTE
SHRIMP_PASTE|BAGOONG,BELACAN,MAM_RUOC
SOY_PRODUCTS|EDAMAME,FERMENTED_TOFU,FIRM_TOFU,NATTO,SILKEN_TOFU,SMOKED_TOFU,SOYBEANS,TEMPEH,TOFU,TVP
SOY_SAUCE|DARK_SOY_SAUCE,KECAP_MANIS,LIGHT_SOY_SAUCE,TAMARI
SPICES|AJWAIN,ALLSPICE,ANNATTO,BLACK_PEPPER,CARAWAY,CARDAMOM,CINNAMON,CLOVES,CORIANDER_SEED,CUMIN,FENNEL_SEED,FENUGREEK,FRESH_TURMERIC,GALANGAL,MUSTARD_SEED,NUTMEG,PAPRIKA_POWDER,SAFFRON,SICHUAN_PEPPER,SMOKED_PAPRIKA,SPICE_BLENDS,STAR_ANISE,SUMAC,TURMERIC,VANILLA,WHITE_PEPPER
SPICE_BLENDS|BERBERE,CURRY_POWDER,FIVE_SPICE,GARAM_MASALA,JERK_SEASONING,RAS_EL_HANOUT,ZAATAR
SPROUTS|ALFALFA_SPROUTS,BEAN_SPROUTS
STARCHES|BREAD,BULGUR,CASSAVA,CHESTNUT,COUSCOUS,DUMPLING_WRAPPERS,GNOCCHI,GRAINS,JERUSALEM_ARTICHOKE,NOODLES,PLANTAIN,POLENTA,POTATO,RICE,RICE_CAKES,RICE_PRODUCTS,STARCH_BINDERS,SWEET_POTATO,TARO,UBE,YAM
STARCH_BINDERS|CORNSTARCH,POTATO_STARCH,TAPIOCA_STARCH
STEM_VEGETABLES|ASPARAGUS,CELERY_STALK,FENNEL,GREEN_ASPARAGUS,RHUBARB,WHITE_ASPARAGUS
STOCKS|BEEF_STOCK,CHICKEN_STOCK,DASHI,FISH_STOCK,VEGETABLE_STOCK
STONE_FRUIT|CHERRY,MIRABELLE,NECTARINE,SOUR_CHERRY
SWEETENERS|AGAVE_SYRUP,BROWN_SUGAR,CONDENSED_MILK,DATE_SYRUP,HONEY,KECAP_MANIS,MAPLE_SYRUP,MIRIN,MOLASSES,PALM_SUGAR,POMEGRANATE_MOLASSES,WHITE_SUGAR
TEA|BLACK_TEA,GREEN_TEA,MATCHA
TOFU|FERMENTED_TOFU,FIRM_TOFU,SILKEN_TOFU,SMOKED_TOFU
TOMATO|CANNED_TOMATOES,CHERRY_TOMATO,SUN_DRIED_TOMATO,TOMATO_PASSATA
TOMATO_PRODUCTS|CANNED_TOMATOES,KETCHUP,SUN_DRIED_TOMATO,TOMATO_PASSATA,TOMATO_PASTE
TROPICAL_FRUIT|AVOCADO,BANANA,CALAMANSI,COCONUT,DRAGON_FRUIT,GUAVA,JACKFRUIT,LYCHEE,MANGO,PAPAYA,PASSION_FRUIT,PINEAPPLE,PLANTAIN
TROUT|SMOKED_TROUT
TUNA|CANNED_TUNA
TURKEY|TURKEY_BREAST,TURKEY_MINCE
VEAL|VEAL_CUTLET,VEAL_LIVER,VEAL_SHANK,WHITE_SAUSAGE
VEGETABLES|ALLIUM_VEGETABLES,CABBAGE_VEGETABLES,FRUIT_VEGETABLES,LEAFY_GREENS,MUSHROOMS,POD_VEGETABLES,ROOT_VEGETABLES,SPROUTS,STEM_VEGETABLES
VINEGAR|APPLE_CIDER_VINEGAR,BALSAMIC_VINEGAR,BLACK_VINEGAR,MALT_VINEGAR,RED_WINE_VINEGAR,RICE_VINEGAR,SHERRY_VINEGAR,WHITE_WINE_VINEGAR
WHEAT_PASTA|LASAGNE_SHEETS,ORZO,PENNE,SPAGHETTI
WHITE_FISH|CATFISH,HADDOCK,HAKE,HALIBUT,MONKFISH,PANGASIUS,PIKEPERCH,PLAICE,REDFISH,SEA_BASS,SEA_BREAM,SOLE
YAM|UBE
YOGURT|GREEK_YOGURT
$relations$, E'\n') AS source(line)
CROSS JOIN LATERAL unnest(
    string_to_array(split_part(source.line, '|', 2), ',')
) AS child_code(code)
JOIN ingredient_concept parent
  ON parent.code = split_part(source.line, '|', 1)
JOIN ingredient_concept child
  ON child.code = child_code.code
WHERE source.line <> ''
ON CONFLICT (parent_concept_id, child_concept_id) DO NOTHING;
