--liquibase formatted sql

--changeset venomenon328:028-curator-note-completeness splitStatements:false
-- Issue #178: backfill concise editorial notes for every ingredient concept that
-- still lacks one, then make the completeness invariant permanent.

CREATE TEMP TABLE _ingredient_curator_note_backfill (
    code text PRIMARY KEY,
    curator_note text NOT NULL CHECK (btrim(curator_note) <> '')
) ON COMMIT DROP;

INSERT INTO _ingredient_curator_note_backfill (code, curator_note)
VALUES
    ('ADZUKI_BEANS', 'Kleine rote Bohnen mit mild-nussigem, leicht süßlichem Geschmack; getrocknet oder vorgegart verwendbar.'),
    ('AGAVE_SYRUP', 'Konzentrierter Sirup aus Agaven; süßt neutraler als Honig und bleibt auch kalt gut löslich.'),
    ('AJVAR', 'Balkanische Paprikazubereitung aus gerösteter Paprika, häufig mit Aubergine; als fertige Würzpaste oder Beilage gemeint.'),
    ('AJWAIN', 'Kräftig thymianartig schmeckende Samenfrucht, die meist sparsam und häufig angeröstet als Gewürz verwendet wird.'),
    ('ALFALFA_SPROUTS', 'Zarte Luzernensprossen mit mild-grünem Geschmack; vor allem roh oder nur sehr kurz erhitzt verwendbar.'),
    ('ALLIUM_VEGETABLES', 'Offene Vorgabe für Zwiebel-, Lauch- und verwandte Gemüsearten mit schwefelig-aromatischer Würzwirkung.'),
    ('ALLSPICE', 'Getrocknete Pimentbeeren mit Aromen, die an Nelke, Zimt und Muskat erinnern; nicht mit einer Gewürzmischung verwechseln.'),
    ('ALMOND', 'Mandeln mit mild-nussigem Geschmack; ganz, gehackt, gemahlen oder blanchiert einsetzbar.'),
    ('ALMOND_BUTTER', 'Fein vermahlene Mandelpaste, ungesüßt oder leicht gesüßt; nicht Marzipan oder bloßes Mandelaroma.'),
    ('ALMOND_DRINK', 'Flüssiger Pflanzendrink auf Mandelbasis; gesüßte und ungesüßte Varianten sind umfasst.'),
    ('AMARANTH', 'Kleine glutenfreie Pseudogetreidekörner mit leicht nussigem Geschmack; ganz gekocht oder gepufft verwendbar.'),
    ('ANCHOVIES', 'Kleine fettreiche Fische, als Kochzutat meist gesalzen und in Öl oder Lake konserviert; lösen sich beim Garen oft würzend auf.'),
    ('ANCHO_CHILI', 'Getrocknete reife Poblano-Chili mit milder Schärfe und fruchtig-rosinigem Aroma; nicht die frische grüne Poblano.'),
    ('ANNATTO', 'Samen des Achiote-Strauchs, die Speisen orange-rot färben und mild erdig-pfeffrig würzen; ganz oder gemahlen verwendbar.'),
    ('APPLE', 'Apfel als frische Frucht; Sorte und Verhältnis von Süße, Säure und Festigkeit bleiben offen.'),
    ('APPLE_CIDER_VINEGAR', 'Aus Apfelwein vergorener Essig mit fruchtiger Säure; nicht Apfelsaft oder Cider.'),
    ('APRICOT', 'Aprikose als frische oder ungesüßt tiefgekühlte Steinfrucht mit süß-säuerlichem, aromatischem Fruchtfleisch.'),
    ('ARTICHOKE', 'Essbare Blütenknospe mit fleischigem Boden und herb-nussigem Geschmack; frisch oder schlicht konserviert verwendbar.'),
    ('ARUGULA', 'Pfeffrig-scharfer Blattsalat, auch Rauke genannt; roh oder kurz zusammenfallend einsetzbar.'),
    ('ASPARAGUS', 'Spargel als offene Farb- und Sortenwahl; grüner und weißer Spargel sind bekannte Ausprägungen mit unterschiedlicher Zubereitung.'),
    ('AVOCADO', 'Cremige, fettreiche Frucht mit mild-nussigem Geschmack; gemeint ist das Fruchtfleisch, nicht Avocadoöl.'),
    ('BACON', 'Gepökelter, meist geräucherter Schweinebauch nach Bacon-Art; Scheibendicke und Räucherung können variieren.'),
    ('BAGOONG', 'Offene philippinische Familie salzig-fermentierter Fisch- oder Garnelenwürzen; die konkrete tierische Basis bleibt wählbar.'),
    ('BAGUETTE', 'Langes französisches Weizenbrot mit kräftiger Kruste und luftiger Krume; nicht beliebiges Weißbrot.'),
    ('BALSAMIC_VINEGAR', 'Dunkler, süß-säuerlicher Essig nach Balsamico-Art auf Traubenbasis; Reifegrad und Dichte können variieren.'),
    ('BANANA', 'Reife Dessertbanane mit weichem, süßem Fruchtfleisch; nicht stärkehaltige Kochbanane.'),
    ('BANANA_KETCHUP', 'Filipinische süß-säuerliche Würzsauce auf Bananenbasis, typischerweise tomatenketchupähnlich gewürzt und gefärbt.'),
    ('BARBECUE_SAUCE', 'Fertige kräftig gewürzte Sauce nach Barbecue-Art; Süße, Rauchigkeit, Säure und Schärfe können deutlich variieren.'),
    ('BARLEY', 'Gerstenkorn als Kochzutat, etwa geschält oder als Rollgerste; Graupen sind eine stärker verarbeitete Form.'),
    ('BASIL', 'Frisches Basilikum mit süßlich-pfeffrigem Aroma; Thai-Basilikum bleibt als eigenständige Ausprägung getrennt.'),
    ('BASMATI_RICE', 'Langkornreis mit charakteristisch duftigem Aroma und lockerem Korn; weiß oder als Vollkornvariante verwendbar.'),
    ('BEANS', 'Offene Vorgabe für trockene oder vorgegarte Bohnenkerne; frische grüne Bohnen und andere Schotengemüse sind nicht gemeint.'),
    ('BEAN_SPROUTS', 'Knackige Sprossen der Mungbohne, im Handel oft als Sojasprossen bezeichnet; nicht mit Keimlingen der Sojabohne gleichsetzen.'),
    ('BEEF', 'Offene Vorgabe für Rindfleisch; Zuschnitt, Fettanteil und geeignete Garmethode werden bewusst nicht festgelegt.'),
    ('BEEF_BRISKET', 'Bindegewebsreiche Rinderbrust, besonders für langsames Schmoren, Kochen oder Barbecue geeignet.'),
    ('BEEF_CHEEK', 'Stark beanspruchtes, kollagenreiches Muskelfleisch aus der Rinderbacke; wird durch langes Schmoren zart.'),
    ('BEEF_GOULASH', 'Würfel oder grobe Stücke vom Rind für Schmorgerichte; gemeint ist der rohe Zuschnitt, nicht das fertige Gulasch.'),
    ('BEEF_HEART', 'Mageres, festes Muskelfleisch vom Rinderherz mit kräftigem Eigengeschmack; nicht mit Lebertextur gleichsetzen.'),
    ('BEEF_LIVER', 'Rinderleber mit kräftigem, mineralischem Geschmack und weicher Textur; kurze Garung verhindert unnötige Trockenheit.'),
    ('BEEF_MINCE', 'Zerkleinertes Rindfleisch mit variablem Fettanteil; nicht gemischtes Hackfleisch.'),
    ('BEEF_ROAST', 'Größeres Rindfleischstück zum Braten oder Schmoren; der konkrete Teilzuschnitt bleibt offen.'),
    ('BEEF_ROULADE', 'Dünne große Rindfleischscheibe zum Füllen und Schmoren; gemeint ist der Zuschnitt, nicht eine festgelegte Füllung.'),
    ('BEEF_RUMP', 'Rinderhüfte als relativ magerer, kurzbrat- oder bratentauglicher Zuschnitt; nicht das stärker marmorierte Roastbeef.'),
    ('BEEF_SHIN', 'Quergeschnittene Rinderhaxe mit Knochen und viel Kollagen; besonders für langsames Schmoren oder Brühen geeignet.'),
    ('BEEF_SHORT_RIBS', 'Fleischige kurze Rinderrippen mit Fett und Bindegewebe; für langsames Garen oder Barbecue geeignet.'),
    ('BEEF_STEAK', 'Zum Kurzbraten geeignete Rindfleischscheibe; der konkrete Steakzuschnitt und Reifegrad bleiben offen.'),
    ('BEEF_STOCK', 'Kräftiger Fond auf Basis von Rindfleisch und/oder Rinderknochen; selbst gekocht oder als hochwertiges Fertigprodukt verwendbar.'),
    ('BEEF_TENDERLOIN', 'Sehr zartes und mageres Rinderfilet für kurze Garung; nicht mit Schweinefilet oder Roastbeef gleichsetzen.'),
    ('BEEF_TONGUE', 'Rinderzunge als festes, nach langem Garen zartes Muskelfleisch; üblicherweise vor dem Servieren gehäutet.'),
    ('BEER', 'Vergorenes Getreidegetränk als Kochzutat; Bierstil, Malzigkeit und Hopfenbittere bleiben bewusst wählbar.'),
    ('BEETROOT', 'Rote Bete mit erdig-süßlichem Geschmack; frisch, vorgegart oder schlicht konserviert verwendbar.'),
    ('BELACAN', 'Malaysische feste fermentierte Garnelenpaste mit sehr intensivem Aroma; meist geröstet und sparsam dosiert verwendet.'),
    ('BELL_PEPPER', 'Milde Gemüsepaprika ohne Festlegung auf eine Farbe; rote, gelbe und grüne Paprika sind bekannte Ausprägungen.'),
    ('BELUGA_LENTILS', 'Kleine schwarze Linsen, die beim Garen vergleichsweise formstabil bleiben; nicht Beluga-Kaviar.'),
    ('BERBERE', 'Äthiopisch-eritreische Gewürzmischung mit Chili und warmen Gewürzen; Zusammensetzung und Schärfe variieren.'),
    ('BERRIES', 'Offene Vorgabe für kulinarisch als Beeren verwendete kleine Früchte; Sorte und frisch oder tiefgekühlt bleiben offen.'),
    ('BIRDS_EYE_CHILI', 'Kleine, sehr scharfe frische Chili der Bird’s-Eye-Familie; nicht getrocknete Flocken oder Pulver.'),
    ('BITTER_MELON', 'Herb-bitteres Fruchtgemüse mit warziger Oberfläche; auch Bittergurke oder Ampalaya genannt.'),
    ('BIVALVES', 'Offene Vorgabe für zweischalige Weichtiere wie Mies-, Venus- oder Jakobsmuscheln; nicht Krebstiere.'),
    ('BLACKBERRY', 'Brombeere als frische oder ungesüßt tiefgekühlte Beere mit süß-säuerlichem, dunklem Fruchtaroma.'),
    ('BLACK_BEANS', 'Schwarze Bohnen mit cremigem Inneren und mild-erdigem Geschmack; getrocknet oder vorgegart verwendbar.'),
    ('BLACK_CURRANT', 'Schwarze Johannisbeere mit intensiver Säure und herb-aromatischem Geschmack; frisch oder ungesüßt tiefgekühlt gemeint.'),
    ('BLACK_EYED_PEAS', 'Helle Augenbohnen mit dunklem Keimfleck und mild-nussigem Geschmack; botanisch eine Form der Kuhbohne.'),
    ('BLACK_PEPPER', 'Reif geerntete und getrocknete Pfefferfrüchte mit kräftiger Schärfe und warmem Aroma; ganz oder gemahlen verwendbar.'),
    ('BLACK_TEA', 'Vollständig oxidierter Tee mit kräftigem, oft malzigem oder herbem Profil; Sorte und Blattgrad bleiben offen.'),
    ('BLACK_VINEGAR', 'Dunkler chinesischer Getreideessig mit malziger, röstiger Säure; nicht Balsamico oder bloß gefärbter Tafelessig.'),
    ('BLOOD_ORANGE', 'Orange mit rot pigmentiertem Fruchtfleisch und häufig beerig-herber Note; nicht Grapefruit.'),
    ('BLOOD_SAUSAGE', 'Wurstfamilie mit Blut als prägendem Bestandteil; Gewürzung, Getreideanteil und Konsistenz können regional variieren.'),
    ('BLUEBERRY', 'Heidelbeere als frische oder ungesüßt tiefgekühlte Beere; Kultur- und Waldheidelbeeren sind umfasst.'),
    ('BLUE_CHEESE', 'Offene Käsefamilie mit Blauschimmelkulturen und ausgeprägt würzigem Aroma; Milchart und Reifegrad bleiben offen.'),
    ('BONE_MARROW', 'Fettreiches Mark aus großen Rinderknochen; zum Rösten, Auslassen oder Aromatisieren von Saucen und Brühen.'),
    ('BONITO_FLAKES', 'Dünn gehobelte Flocken aus getrocknetem und meist geräuchertem Bonito nach Katsuobushi-Art; stark umamireich.'),
    ('BRATWURST', 'Zum Braten oder Grillen bestimmte Wurst; Fleischmischung, Körnung und regionale Würzung bleiben offen.'),
    ('BRAZIL_NUT', 'Große, fettreiche Paranusskerne mit cremigem Biss; ganz, gehackt oder gemahlen verwendbar.'),
    ('BREAD', 'Offene Vorgabe für gebackenes Brot oder Fladenbrot; Getreide, Triebmittel, Form und Krustenanteil bleiben wählbar.'),
    ('BREADCRUMBS', 'Trockene gemahlene Brot- oder Brötchenkrume zum Panieren, Binden oder Bestreuen; Panko ist eine eigene Ausprägung.'),
    ('BROAD_BEANS', 'Dicke Bohnen beziehungsweise Ackerbohnen; frisch, tiefgekühlt oder getrocknet verwendbar und nicht mit grünen Bohnen gleichzusetzen.'),
    ('BROCCOLI', 'Grünes Kohlgemüse mit essbaren Blütenknospen und Stielen; nicht mit Romanesco oder Blumenkohl gleichsetzen.'),
    ('BROWN_CHAMPIGNON', 'Frische braune Zuchtchampignons mit etwas kräftigerem Aroma als weiße Champignons.'),
    ('BROWN_RICE', 'Reis mit erhaltenen Randschichten und dadurch nussigerem Geschmack sowie festerem Biss; Sorte bleibt offen.'),
    ('BROWN_SUGAR', 'Brauner Zucker mit Melasseanteil beziehungsweise karamelligem Aroma; feucht oder trocken verwendbar.'),
    ('BRUSSELS_SPROUTS', 'Kleine feste Blattachselknospen des Kohls mit herb-nussigem Geschmack; frisch oder tiefgekühlt verwendbar.'),
    ('BUCKWHEAT', 'Glutenfreies Pseudogetreide mit kräftig-nussigem Geschmack; gemeint sind ganze Körner oder Grütze, nicht Mehl.'),
    ('BULGUR', 'Vorgegarter, getrockneter und gebrochener Hartweizen mit nussigem Biss; Körnung kann variieren.'),
    ('BUTTER', 'Streich- und Kochfett aus Milchrahm; gesalzene, ungesalzene und mildgesäuerte Butter sind umfasst.'),
    ('BUTTERMILK', 'Fettarmes säuerliches Milchprodukt aus der Butterherstellung beziehungsweise entsprechender Kultivierung; nicht Kefir.'),
    ('BUTTERNUT_SQUASH', 'Birnenförmiger Moschuskürbis mit dichtem, süßlich-nussigem Fruchtfleisch und kleiner Samenhöhle.'),
    ('BUTTER_BEANS', 'Große helle Limabohnen mit weicher, cremiger Textur; getrocknet oder vorgegart verwendbar.'),
    ('CABBAGE_VEGETABLES', 'Offene Vorgabe für Blatt-, Kopf-, Knospen- und Blütenformen der Kohlgemüsefamilie.'),
    ('CALAMANSI', 'Kleine südostasiatische Zitrusfrucht mit aromatischem, deutlich saurem Saft; frisch oder als ungesüßter Saft verwendbar.'),
    ('CAMEMBERT', 'Weicher Kuhmilchkäse mit Weißschimmelrinde und cremiger bis reifer, kräftiger Textur; nicht Brie.'),
    ('CANNED_CHAMPIGNONS', 'Gegarte Champignons aus Dose oder Glas in schlichter Lake; nicht eingelegte oder frische Champignons.'),
    ('CANNED_SARDINES', 'Gegarte Sardinen als Konserve in Öl, Wasser oder einfacher Sauce; Flüssigkeit und Würzung können variieren.'),
    ('CANNED_TOMATOES', 'Geschälte oder stückige Tomaten als unkonzentrierte Konserve; nicht passierte Tomaten oder Tomatenmark.'),
    ('CANNED_TUNA', 'Gegarter Thunfisch als Konserve in Öl oder eigenem Saft; nicht frisches Thunfischsteak.'),
    ('CANNELLINI_BEANS', 'Mittelgroße weiße Bohnen italienischer Art mit mildem Geschmack und cremiger Textur.'),
    ('CANTALOUPE', 'Orangefleischige, aromatisch süße Melone mit typischer netzartiger oder gerippter Schale.'),
    ('CAPERS', 'Eingelegte Blütenknospen des Kapernstrauchs mit salzig-säuerlichem, pikantem Geschmack; nicht Kapernäpfel.'),
    ('CARAWAY', 'Echter Kümmel mit warmem, anisartigem Aroma; nicht Kreuzkümmel.'),
    ('CARDAMOM', 'Aromatische Kardamomkapseln oder -samen; grüner Kardamom ist üblich, schwarzer Kardamom nur bei bewusster Wahl.'),
    ('CARP', 'Karpfen als frischer oder tiefgekühlter Süßwasserfisch; Zuschnitt und Zubereitungsform bleiben offen.'),
    ('CARROT', 'Karotte als süßlich-erdiges Wurzelgemüse; Farbe und Größe bleiben offen.'),
    ('CASHEW', 'Cremig-milde Cashewkerne; roh, geröstet oder ungesalzen verwendbar.'),
    ('CASHEW_BUTTER', 'Fein vermahlene Cashewpaste mit cremiger Textur; ungesüßte und leicht gesüßte Varianten sind umfasst.'),
    ('CASSAVA', 'Stärkereiche Maniokwurzel, die nur geschält und ausreichend gegart verwendet wird; nicht Tapiokastärke.'),
    ('CATFISH', 'Wels als festfleischiger Süßwasserfisch; Art und Zuschnitt bleiben offen.'),
    ('CAULIFLOWER', 'Kohlgemüse mit dichtem, hellem Blütenstand; Blätter und Strunk können kulinarisch mitverwendet werden.'),
    ('CAYENNE_PEPPER', 'Fein gemahlenes scharfes Chilipulver nach Cayenne-Art; trotz des Namens kein echter Pfeffer.'),
    ('CELERIAC', 'Knollensellerie mit festem, intensiv sellerieartigem Fleisch; nicht Staudensellerie.'),
    ('CELERY_STALK', 'Staudensellerie mit knackigen Blattstielen und frischem Selleriearoma; nicht Knollensellerie.'),
    ('CHAMPIGNONS', 'Offene Champignonfamilie einschließlich frischer und konservierter Produktformen; nicht sämtliche Speisepilze.'),
    ('CHANTERELLE', 'Pfifferlinge mit festem Biss und pfeffrig-fruchtigem Waldpilzaroma; frisch, tiefgekühlt oder getrocknet verwendbar.'),
    ('CHARD', 'Mangold mit fleischigen Stielen und großen Blättern; beide Teile sind essbar und benötigen oft unterschiedliche Garzeiten.'),
    ('CHEDDAR', 'Fester bis halbfester Kuhmilchkäse nach Cheddar-Art; Reifegrad reicht von mild-cremig bis kräftig-würzig.'),
    ('CHEESE', 'Offene Vorgabe für Käse; Milchart, Textur, Reife und Intensität bleiben als echte Auswahlentscheidung offen.'),
    ('CHERRY', 'Süßkirsche als frische oder ungesüßt tiefgekühlte Steinfrucht; Sauerkirsche bleibt getrennt.'),
    ('CHERRY_TOMATO', 'Kleine süße Tomaten mit hohem Schalenanteil; Farbe und konkrete Sorte bleiben offen.'),
    ('CHESTNUT', 'Stärkereiche Esskastanien mit süßlich-nussigem Geschmack; gegart, vakuumiert oder als ungesüßtes Püree verwendbar.'),
    ('CHIA_SEEDS', 'Kleine quellfähige Samen, die Flüssigkeit gelartig binden; hell oder dunkel verwendbar.'),
    ('CHICKEN', 'Hähnchenfleisch ohne Festlegung auf einen Zuschnitt; ganzes Tier und unterschiedliche Teilstücke sind umfasst.'),
    ('CHICKEN_BREAST', 'Mageres helles Brustfleisch vom Hähnchen; mit oder ohne Haut und Knochen verwendbar.'),
    ('CHICKEN_DRUMSTICKS', 'Unterer Teil der Hähnchenkeule mit Knochen und dunklem Fleisch; nicht die vollständige Keule.'),
    ('CHICKEN_LIVER', 'Kleine zarte Geflügelleber mit kräftigem, aber milderem Aroma als Rinderleber.'),
    ('CHICKEN_STOCK', 'Brühe oder Fond auf Hühnerbasis; selbst gekocht oder als schlichtes Fertigprodukt verwendbar.'),
    ('CHICKEN_THIGH', 'Saftiges dunkles Fleisch vom Hähnchenschenkel; ausgelöst oder mit Knochen und Haut verwendbar.'),
    ('CHICKEN_WINGS', 'Hähnchenflügel mit Haut, Knochen und hohem Kollagenanteil; ganz oder in Gelenkstücke geteilt.'),
    ('CHICKPEAS', 'Kichererbsen mit nussigem Geschmack und mehlig-cremiger Textur; getrocknet oder vorgegart verwendbar.'),
    ('CHICKPEA_FLOUR', 'Fein gemahlene trockene Kichererbsen mit nussigem Geschmack und guter Bindewirkung; nicht Weizenmehl.'),
    ('CHICORY', 'Chicorée als kompakter, blass getriebener Blattsalat mit charakteristischer Bitterkeit; roh und gegart verwendbar.'),
    ('CHILI_CONDIMENTS', 'Offene Vorgabe für verzehrfertige Chilisaucen oder -pasten; Stil, Fermentation und Schärfe bleiben wählbar.'),
    ('CHILI_CRISP', 'Ölbasierte Chiliwürze mit knusprigen Chili-, Zwiebel- oder Gewürzbestandteilen; nicht bloß Chiliöl.'),
    ('CHILI_OIL', 'Mit Chili aromatisiertes Speiseöl, klar oder mit Sediment; nicht automatisch knuspriges Chili-Crisp.'),
    ('CHIPOTLE', 'Geräucherte und getrocknete reife Jalapeño mit mittlerer Schärfe; ganz, gemahlen oder in schlichter Adobo-Konserve verwendbar.'),
    ('CHIVES', 'Feine hohle Schnittlauchröhrchen mit mildem Zwiebelaroma; nicht Knoblauch-Schnittlauch.'),
    ('CHORIZO', 'Kräftig gewürzte Wurst der Chorizo-Familie; frische mexikanische und gereifte iberische Formen sind mögliche Ausprägungen.'),
    ('CIDER', 'Vergorener Apfelwein, still oder perlend und trocken bis süß; nicht Apfelsaft oder Apfelessig.'),
    ('CILANTRO', 'Frisches Blattgrün des Korianders mit markant zitrisch-würzigem Aroma; nicht Koriandersaat.'),
    ('CINNAMON', 'Getrocknete Zimtrinde als Stange oder gemahlen; Ceylon- und Cassia-Typen sind umfasst.'),
    ('CITRUS_FRUIT', 'Offene Vorgabe für Zitrusfrüchte; Saft, Fruchtfleisch und unbehandelte Schale können je nach Wahl genutzt werden.'),
    ('CLAMS', 'Venusmuscheln beziehungsweise vergleichbare kleine essbare Muscheln; frisch, tiefgekühlt oder ausgelöst verwendbar.'),
    ('CLOVES', 'Getrocknete Blütenknospen mit sehr intensivem warm-süßlichem Aroma; ganz oder gemahlen sparsam verwenden.'),
    ('COCOA_POWDER', 'Entfettetes oder teilentfettetes Kakaopulver, ungesüßt und zum Backen oder Würzen geeignet; kein kakaohaltiges Getränkepulver.'),
    ('COCOA_PRODUCTS', 'Offene Familie für Kakaoerzeugnisse von Kakaopulver bis Schokoladenprodukten; konkrete Form und Süße bleiben offen.'),
    ('COCONUT', 'Kokosnuss beziehungsweise frisches Kokosfleisch; Kokosmilch, -wasser und -öl sind getrennte Produktformen.'),
    ('COCONUT_CREAM', 'Dickflüssige, fettreiche Kokosextraktion mit höherem Fettanteil als Kokosmilch; nicht gesüßte Cream of Coconut.'),
    ('COCONUT_FLAKES', 'Getrocknete Kokosraspeln oder -chips, bevorzugt ungesüßt; nicht frisches Kokosfleisch.'),
    ('COCONUT_MILK', 'Weiße Emulsion aus zerkleinertem Kokosfleisch und Wasser; nicht Kokosdrink oder Kokoswasser.'),
    ('COCONUT_OIL', 'Bei Raumtemperatur häufig festes Kokosfett; raffiniert neutral oder nativ kokosaromatisch verwendbar.'),
    ('COCONUT_WATER', 'Klare Flüssigkeit aus dem Inneren junger Kokosnüsse; nicht Kokosmilch oder gesüßter Kokosdrink.'),
    ('COD', 'Kabeljau als mildes, blättriges Weißfischfleisch; frisch oder tiefgekühlt, nicht gesalzen und getrocknet.'),
    ('COFFEE', 'Gebrühter Kaffee oder gemahlene beziehungsweise ganze geröstete Kaffeebohnen als bitter-röstige Kochzutat.'),
    ('CONDENSED_MILK', 'Stark eingedickte und gezuckerte Kuhmilch mit sirupartiger Konsistenz; nicht ungesüßte Kondensmilch.'),
    ('COOKED_HAM', 'Gepökelter und gegarter Schinken mit saftiger Textur; nicht luftgetrockneter Rohschinken.'),
    ('COOKING_ALCOHOL', 'Offene Vorgabe für alkoholische Getränke, deren Aroma beim Kochen genutzt wird; Bier, Wein und Spirituosen sind mögliche Wege.'),
    ('COOKING_FATS', 'Offene Vorgabe für zum Braten, Garen oder Verfeinern geeignete Fette und Öle; tierische und pflanzliche Formen sind umfasst.'),
    ('CORIANDER_SEED', 'Getrocknete Korianderfrüchte mit warmem, zitrisch-nussigem Aroma; ganz oder gemahlen, nicht Koriandergrün.'),
    ('CORN', 'Mais als Körnerprodukt, frisch, tiefgekühlt oder schlicht konserviert; Mehl, Stärke und Polenta sind getrennte Formen.'),
    ('CORNMEAL', 'Gemahlener Mais mit feiner bis grober Körnung; nicht reine Maisstärke und nicht zwingend vorgekochte Polenta.'),
    ('CORNSTARCH', 'Feine geschmacksneutrale Stärke aus Mais zum Binden und für Teige; nicht Maismehl.'),
    ('COUSCOUS', 'Kleine angefeuchtete und gerollte Hartweizengrießkörner; gemeint ist das trockene Grundprodukt, nicht das fertige Gericht.'),
    ('CRAB', 'Essbares Fleisch von Krabben oder Krebsen; ganzes Tier, Scheren- oder ausgelöstes Fleisch sind möglich.'),
    ('CRANBERRY', 'Herb-saure Cranberry; frisch, ungesüßt tiefgekühlt oder getrocknet verwendbar, wobei Trockenware oft gesüßt ist.'),
    ('CRAYFISH', 'Kleine Süßwasserkrebse mit festem, süßlichem Fleisch; ganz oder als ausgelöstes Schwanzfleisch verwendbar.'),
    ('CREAM', 'Flüssiger Milchrahm zum Kochen oder Schlagen; Fettstufe bleibt offen, gesäuerte Produkte sind getrennt.'),
    ('CREAM_CHEESE', 'Ungereifter streichfähiger Frischkäse mit mild-säuerlichem Geschmack; natur oder neutral gewürzt verwendbar.'),
    ('CREME_FRAICHE', 'Fettreicher gesäuerter Rahm mit cremiger Konsistenz und guter Kochstabilität; nicht saure Sahne.'),
    ('CRISPBREAD', 'Trockenes, knuspriges Dauerbrot mit dünner oder luftiger Struktur; Getreidemischung bleibt offen.'),
    ('CRUSTACEANS', 'Offene Vorgabe für Krebstiere wie Garnelen, Krabben, Hummer oder Flusskrebse; nicht Muscheln oder Tintenfische.'),
    ('CUCUMBER', 'Frische Salatgurke mit hohem Wassergehalt und knackiger Textur; Einlege- und fermentierte Gurken sind getrennt.'),
    ('CULTURED_DAIRY', 'Offene Vorgabe für durch Milchsäurekulturen gesäuerte Milchprodukte; Fettgehalt und Konsistenz bleiben wählbar.'),
    ('CUMIN', 'Kreuzkümmelsamen mit warm-erdigem, intensiv würzigem Aroma; nicht echter Kümmel.'),
    ('CURED_MEAT', 'Offene Familie gepökelter, getrockneter oder vergleichbar gereifter Fleischprodukte; Tierart und Produktform bleiben offen.'),
    ('CURRY_LEAVES', 'Aromatische Blätter des Currybaums mit zitrisch-röstigem Aroma; frisch oder tiefgekühlt bevorzugt, nicht Currypulver.'),
    ('CURRY_POWDER', 'Zusammengesetzte Gewürzmischung nach Currypulver-Art; Zusammensetzung, Farbe und Schärfe können variieren.'),
    ('CUTTLEFISH', 'Sepia beziehungsweise echter Tintenfisch mit festem Fleisch und essbarer Tinte; nicht Kalmar oder Oktopus.'),
    ('DAIKON', 'Großer milder weißer Rettich ostasiatischer Sorten; roh, gegart oder eingelegt verwendbar.'),
    ('DARK_CHOCOLATE', 'Schokolade mit hohem Kakaoanteil und ohne prägende Milchkomponente; Kakaoanteil und Süße bleiben offen.'),
    ('DARK_SOY_SAUCE', 'Dunkle, häufig dickere und leicht süßliche Sojasauce vor allem für Farbe und Tiefe; nicht helle Sojasauce.'),
    ('DASHI', 'Japanischer klarer Würzfond, typischerweise auf Kombu und/oder Bonitoflocken; Instant- und frisch angesetzte Varianten sind umfasst.'),
    ('DATE', 'Dattel mit dichtem, karamellig-süßem Fruchtfleisch; frisch oder getrocknet verwendbar.'),
    ('DATE_SYRUP', 'Dunkler konzentrierter Sirup aus Datteln mit fruchtig-karamelligem Geschmack; nicht Melasse.'),
    ('DIJON_MUSTARD', 'Feiner bis glatter, deutlich scharfer Senf nach Dijon-Art; nicht körniger Senf und nicht zwingend AOP-Herkunft.'),
    ('DILL', 'Frische Dillspitzen mit anisartig-grünem Aroma; Stiele können mitverwendet werden, Dillsaat ist nicht gemeint.'),
    ('DOENJANG', 'Koreanische fermentierte Sojabohnenpaste mit kräftigem, salzig-erdigem Umami; nicht Miso oder Gochujang.'),
    ('DOUBANJIANG', 'Chinesische fermentierte Bohnen-Chili-Paste, häufig auf Saubohnenbasis; salzig, scharf und ausgeprägt umamireich.'),
    ('DRAGON_FRUIT', 'Mild-süße Pitahaya mit saftigem, samenreichem Fruchtfleisch; rote und weiße Sorten sind umfasst.'),
    ('DRIED_APRICOT', 'Getrocknete Aprikosen mit konzentrierter Süße und zäher Textur; geschwefelte und ungeschwefelte Ware ist möglich.'),
    ('DRIED_FRUIT', 'Offene Vorgabe für durch Trocknung konzentriertes Obst; Sorte, Stückgröße und eventuelle Süßung bleiben wählbar.'),
    ('DUCK', 'Entenfleisch ohne Festlegung auf Brust, Keule oder ganzes Tier; Haut und Fett können prägende Bestandteile sein.'),
    ('DUCK_BREAST', 'Entenbrust mit dunklem Fleisch und typischer Fettschicht unter der Haut; mit oder ohne Haut verwendbar.'),
    ('DUCK_EGG', 'Größeres, fettreicheres Ei der Ente; frisch zu garen, nicht bereits gesalzen oder fermentiert.'),
    ('DUCK_FAT', 'Ausgelassenes Entenfett mit charakteristischem Geflügelaroma zum Braten, Confieren oder Verfeinern.'),
    ('DUCK_LEG', 'Entenkeule mit dunklem, bindegewebsreichem Fleisch; für Braten, Schmoren oder Confieren geeignet.'),
    ('DULSE', 'Essbare rote Meeresalge mit salzigem, leicht rauchig-umamireichem Geschmack; meist getrocknet erhältlich.'),
    ('DUMPLING_DOUGH', 'Ungeschnittener Teig zur Herstellung von Dumpling-Hüllen; Zusammensetzung und Dicke bleiben offen.'),
    ('DUMPLING_WRAPPERS', 'Offene Vorgabe für dünne Teigblätter zum Füllen und Falten; Weizen-, Reis- und andere geeignete Hüllen sind möglich.'),
    ('EDAMAME', 'Unreif geerntete grüne Sojabohnen, meist in der Schote blanchiert oder ausgelöst; nicht reife trockene Sojabohnen.'),
    ('EEL', 'Aal als fettreicher Fisch mit festem Fleisch; frisch, geräuchert oder anderweitig verarbeitet nur bei entsprechender Produktwahl.'),
    ('EGG', 'Ein einzelnes Hühnerei als allgemein verfügbare Kochzutat; Eier anderer Tierarten sind damit nicht gemeint.'),
    ('EGGPLANT', 'Aubergine mit schwammigem, beim Garen cremig werdendem Fruchtfleisch; Sorte und Farbe bleiben offen.'),
    ('EGGS', 'Offene Vorgabe für Vogeleier; Art, Größe und Zubereitungsfunktion werden bewusst nicht festgelegt.'),
    ('EGG_NOODLES', 'Nudeln mit Ei als prägendem Teigbestandteil; Form und Dicke bleiben offen.'),
    ('EGUSI_SEEDS', 'Ölreiche Samen bestimmter westafrikanischer Melonenarten, meist gemahlen zum Binden und Aromatisieren; nicht Kürbiskerne.'),
    ('ELDERBERRY', 'Reife Holunderbeeren mit herb-säuerlichem Aroma; nur gegart verwenden, nicht rohe unreife Beeren.'),
    ('ENDIVE', 'Endivienblätter mit knackiger Textur und deutlicher Bitterkeit; glatte und krause Formen sind umfasst.'),
    ('ENOKI', 'Langstielige, kleinhütige Enoki-Pilze mit zartem Biss und mildem Geschmack; kultivierte helle Ware ist üblich.'),
    ('EVAPORATED_MILK', 'Ungesüßte, durch Wasserentzug konzentrierte Milch; nicht gezuckerte Kondensmilch.'),
    ('FARRO', 'Emmer beziehungsweise als Farro verkauftes geschältes Weizenkorn mit nussigem Geschmack und festem Biss.'),
    ('FENNEL', 'Fenchelknolle mit knackiger bis zarter Textur und mildem Anisaroma; Grün kann mitverwendet werden.'),
    ('FENNEL_SEED', 'Getrocknete Fenchelfrüchte mit süßlich-anisartigem Aroma; ganz oder gemahlen, nicht Fenchelknolle.'),
    ('FENUGREEK', 'Bockshornkleesamen mit herb-würzigem, leicht bitterem Aroma; ganz oder gemahlen sparsam verwendbar.'),
    ('FERMENTED_BLACK_BEANS', 'Salzig fermentierte schwarze Sojabohnen nach Douchi-Art; als Würzzutat gemeint, nicht gewöhnliche schwarze Bohnen.'),
    ('FERMENTED_SEASONINGS', 'Offene Familie fermentierter Würzsaucen, Pasten und vergleichbarer Zutaten; Rohstoff und Konsistenz bleiben offen.'),
    ('FERMENTED_TOFU', 'In Lake gereifte Tofuwürfel mit kräftigem, salzigem Aroma und cremiger Textur; als Würzmittel, nicht als fester Tofublock.'),
    ('FETA', 'Salzlakenkäse nach Feta-Art aus Schafmilch mit möglichem Ziegenmilchanteil; krümelig, säuerlich und salzig.'),
    ('FIG', 'Feige mit weichem, samenreichem und honigartig süßem Fruchtfleisch; frisch oder ungesüßt getrocknet verwendbar.'),
    ('FIRM_TOFU', 'Fester gepresster Tofu, der schneiden, braten und marinieren verträgt; nicht Seidentofu.'),
    ('FISH', 'Offene Vorgabe für Speisefisch; Art, Fettgehalt, Zuschnitt und Frisch- oder Konservenform bleiben echte Auswahlentscheidungen.'),
    ('FISH_ROE', 'Offene Vorgabe für essbare Fischeier; Fischart, Körnung, Salzgrad und Verarbeitung bleiben offen.'),
    ('FISH_SAUCE', 'Salzige fermentierte Würzsauce aus Fisch und Salz mit intensivem Umami; nicht Fischfond.'),
    ('FISH_STOCK', 'Brühe oder Fond auf Basis von Fischgräten und -abschnitten; nicht Dashi oder Fischsauce.'),
    ('FIVE_SPICE', 'Chinesisch geprägte Gewürzmischung mit typischerweise Sternanis, Fenchel, Zimt, Nelke und Szechuanpfeffer; Mischungen variieren.'),
    ('FLATBREAD', 'Offene Familie flacher Brote, weich oder knusprig und mit oder ohne Triebmittel; konkrete Küche und Getreide bleiben offen.'),
    ('FLAXSEED', 'Leinsamen mit nussigem Geschmack und hoher Quell- beziehungsweise Bindefähigkeit; ganz oder geschrotet verwendbar.'),
    ('FLOUR', 'Offene Vorgabe für fein gemahlenes Getreide, Pseudogetreide oder Hülsenfrüchte; Rohstoff und Backeigenschaften bleiben wählbar.'),
    ('FLOWER_VEGETABLES', 'Offene Vorgabe für Gemüse, dessen Blütenstand oder Blütenknospe im Mittelpunkt steht, etwa Brokkoli oder Artischocke.'),
    ('FREEKEH', 'Grün geernteter, gerösteter und gebrochener Weizen mit rauchig-nussigem Geschmack und festem Biss.'),
    ('FRESH_DAIRY_PRODUCTS', 'Offene Vorgabe für frische, nicht gereifte Milchprodukte wie Milch, Sahne oder Frischkäse.'),
    ('FRESH_HERBS', 'Offene Vorgabe für frische Küchenkräuter und aromatische Würzblätter; konkrete Pflanze und Intensität bleiben offen.'),
    ('FRESH_TURMERIC', 'Frisches Kurkuma-Rhizom mit erdig-pfeffrigem Aroma und starker gelber Färbung; nicht getrocknetes Pulver.'),
    ('FRUIT', 'Offene Vorgabe für kulinarisch als Obst verwendete Früchte; Art, Säure, Süße und Textur bleiben bewusst wählbar.'),
    ('FRUIT_VEGETABLES', 'Offene Vorgabe für botanische Früchte, die herzhaft als Gemüse verwendet werden, etwa Tomate, Paprika oder Kürbis.');

INSERT INTO _ingredient_curator_note_backfill (code, curator_note)
VALUES
    ('GALANGAL', 'Südostasiatisches Rhizom mit zitrisch-pfeffrigem, harzigem Aroma; frisch oder tiefgekühlt, nicht mit Ingwer gleichsetzen.'),
    ('GAME_MEAT', 'Offene Vorgabe für Fleisch jagdbarer Wildtiere; Tierart, Zuschnitt und Intensität bleiben bewusst wählbar.'),
    ('GARAM_MASALA', 'Indische Gewürzmischung aus warm-aromatischen Gewürzen; Zusammensetzung und Verwendung als ganze oder gemahlene Mischung variieren.'),
    ('GARLIC', 'Knoblauchknolle mit schwefelig-scharfem, beim Garen süßlich-mildem Aroma; frisch gemeint, nicht Pulver.'),
    ('GARLIC_BUTTER', 'Butterzubereitung mit Knoblauch als prägendem Aroma; weitere Kräuter sind möglich, aber nicht erforderlich.'),
    ('GARLIC_CHIVES', 'Flaches asiatisches Schnittlauchgewächs mit deutlichem Knoblaucharoma; auch Knoblauch-Schnittlauch genannt.'),
    ('GHEE', 'Geklärtes Butterreinfett mit nussigem Aroma und hoher Hitzetoleranz; nahezu frei von Wasser und Milcheiweiß.'),
    ('GINGER', 'Frisches Ingwer-Rhizom mit zitrischer Schärfe; nicht getrocknetes Ingwerpulver oder eingelegter Ingwer.'),
    ('GLASS_NOODLES', 'Transparente Nudeln aus Stärke, häufig Mungbohnen-, Süßkartoffel- oder Erbsenstärke; nicht Reisnudeln.'),
    ('GNOCCHI', 'Kleine weiche Klößchen, typischerweise auf Kartoffel- und Mehlbasis; gemeint ist das ungefüllte Grundprodukt.'),
    ('GOAT', 'Ziegenfleisch mit kräftigem Eigengeschmack; Zuschnitt und Alter des Tieres bleiben offen.'),
    ('GOAT_CHEESE', 'Käse aus Ziegenmilch; Frischkäse, Weichkäse und gereifte feste Formen sind mögliche Ausprägungen.'),
    ('GOCHUGARU', 'Koreanische grobe Chiliflocken mit fruchtigem Aroma und meist mittlerer Schärfe; nicht beliebige Chiliflocken.'),
    ('GOOSE', 'Gänsefleisch ohne Festlegung auf Brust, Keule oder ganzes Tier; fettreiche Haut ist ein typischer Bestandteil.'),
    ('GOOSEBERRY', 'Stachelbeere mit fester Schale und süß-säuerlichem bis herbem Fruchtfleisch; Farbe und Reifegrad bleiben offen.'),
    ('GOUDA', 'Halbfester bis fester Kuhmilchkäse nach Gouda-Art; Reifegrad reicht von mild-cremig bis kristallin-würzig.'),
    ('GRAINS', 'Offene Vorgabe für Getreide und kulinarisch vergleichbare Pseudogetreide; Art und Verarbeitungsgrad bleiben wählbar.'),
    ('GRAPE', 'Frische Weintrauben als süße, saftige Frucht; helle und dunkle sowie kernlose und kernhaltige Sorten sind umfasst.'),
    ('GRAPEFRUIT', 'Große Zitrusfrucht mit saftigem, deutlich bitter-säuerlichem Fruchtfleisch; Farbe und Sorte bleiben offen.'),
    ('GRAVLAX', 'Mit Salz, Zucker und meist Dill trocken gebeizter roher Lachs; nicht geräuchert und nicht gegart.'),
    ('GREEK_YOGURT', 'Abgetropfter beziehungsweise besonders proteinreicher Joghurt mit dichter, cremiger Textur; Fettstufe bleibt offen, natur gemeint.'),
    ('GREEN_ASPARAGUS', 'Grüner oberirdisch gewachsener Spargel mit kräftigerem, grasig-nussigem Aroma; Schälen ist meist nur am unteren Ende nötig.'),
    ('GREEN_BEANS', 'Junge essbare Bohnenhülsen mit knackiger Textur; vor dem Verzehr garen, nicht trockene Bohnenkerne.'),
    ('GREEN_BELL_PEPPER', 'Unreif grün geerntete Gemüsepaprika mit herberem, grasigem Geschmack; nicht scharfe grüne Chili.'),
    ('GREEN_PAPAYA', 'Unreife feste Papaya mit mildem Geschmack, als knackiges Gemüse verwendbar; nicht reife süße Papaya.'),
    ('GREEN_PEAS', 'Junge grüne Erbsen, frisch oder tiefgekühlt, mit süßlichem Geschmack; nicht getrocknete Spalterbsen.'),
    ('GREEN_PEPPER', 'Unreif geerntete Pfefferfrüchte, frisch, gefriergetrocknet oder in Lake; milder und frischer als schwarzer Pfeffer.'),
    ('GREEN_TEA', 'Nicht oder nur wenig oxidierter Tee mit grasigem bis nussigem Profil; Sorte, Blattgrad und Röstung bleiben offen.'),
    ('GRUYERE', 'Fester gereifter Kuhmilchkäse nach Gruyère-Art mit nussig-würzigem Aroma und guter Schmelzeignung.'),
    ('GUAVA', 'Tropische Frucht mit intensiv duftendem, süß-säuerlichem Fruchtfleisch und vielen essbaren Kernen.'),
    ('HABANERO', 'Sehr scharfe frische Chili mit ausgeprägt fruchtigem Aroma; Farbe und konkrete Habanero-Sorte bleiben offen.'),
    ('HADDOCK', 'Schellfisch mit mildem, magerem und blättrigem Fleisch; frisch oder tiefgekühlt, nicht automatisch geräuchert.'),
    ('HAKE', 'Seehecht als magerer Weißfisch mit zartem, grobblättrigem Fleisch; Zuschnitt bleibt offen.'),
    ('HALIBUT', 'Heilbutt mit festem, mildem und vergleichsweise fleischigem Weißfischfilet; schwarzer und weißer Heilbutt sind umfasst.'),
    ('HALLOUMI', 'Fester Salzlakenkäse mit hoher Hitzestabilität und charakteristischem Biss; meist aus Schaf-, Ziegen- und/oder Kuhmilch.'),
    ('HARISSA', 'Nordafrikanische Chilipaste mit Gewürzen und häufig Knoblauch; Schärfe, Ölanteil und genaue Zusammensetzung variieren.'),
    ('HAZELNUT', 'Haselnusskerne mit süßlich-nussigem Aroma; roh, geröstet, ganz oder gemahlen verwendbar.'),
    ('HEMP_SEEDS', 'Geschälte oder ungeschälte Hanfsamen mit mild-nussigem Geschmack; als Saat, nicht als Rauschmittel gemeint.'),
    ('HERB_BUTTER', 'Butterzubereitung mit frischen oder getrockneten Kräutern; Kräutermischung und weitere milde Würzung bleiben offen.'),
    ('HERRING', 'Hering als fettreicher Fisch; frisch oder schlicht tiefgekühlt gemeint, spezifische Reife- und Einlegeformen sind getrennt.'),
    ('HIJIKI', 'Dunkle fadenförmige Meeresalge der ostasiatischen Küche mit kräftigem Meeresaroma; üblicherweise getrocknet und eingeweicht.'),
    ('HOISIN_SAUCE', 'Dicke süß-salzige chinesische Würzsauce auf fermentierter Bohnenbasis; nicht Austernsauce oder Pflaumensauce.'),
    ('HOKKAIDO_SQUASH', 'Orangefarbener Hokkaido-Kürbis mit essbarer Schale und nussig-süßlichem, dichtem Fruchtfleisch.'),
    ('HONEY', 'Von Bienen erzeugtes flüssiges bis kristallines Süßungsmittel; Blütentyp und Aromaintensität bleiben offen.'),
    ('HONEYDEW_MELON', 'Helle Honigmelone mit glatter Schale und süßem, saftigem Fruchtfleisch; nicht Cantaloupe.'),
    ('HORSERADISH', 'Scharfe Meerrettichwurzel, frisch gerieben oder als möglichst schlichte Zubereitung; Schärfe verfliegt bei Hitze.'),
    ('HOT_MUSTARD', 'Senf mit ausgeprägt stechender Schärfe; Körnung und verwendete Senfsaat bleiben offen.'),
    ('HOT_PAPRIKA_POWDER', 'Scharfes Paprikapulver nach rosenscharfer Art; nicht süßes oder geräuchertes Paprikapulver.'),
    ('JALAPENO', 'Dickfleischige frische Chili mit milder bis mittlerer Schärfe; grüne und reife rote Früchte sind umfasst.'),
    ('JASMINE_RICE', 'Duftender südostasiatischer Langkornreis mit weicherem, leicht haftendem Korn; nicht Basmatireis.'),
    ('JERK_SEASONING', 'Jamaikanisch geprägte Gewürzmischung mit typischerweise Piment, Thymian und Chili; trocken oder als Marinadenbasis verwendbar.'),
    ('JERUSALEM_ARTICHOKE', 'Topinamburknolle mit nussig-süßlichem Geschmack und knackiger bis cremiger Textur; nicht Artischocke.'),
    ('KAFFIR_LIME_LEAVES', 'Aromatische Blätter der Makrut-Limette mit intensiv zitrischem Duft; frisch, tiefgekühlt oder getrocknet verwendbar.'),
    ('KALE', 'Grünkohl mit robusten krausen oder glatten Blättern und kräftig-grünem Geschmack; Stiele je nach Zartheit mitverwenden.'),
    ('KASHMIRI_CHILI_POWDER', 'Leuchtend rotes Chilipulver nach Kashmiri-Art mit fruchtigem Aroma und meist moderater Schärfe.'),
    ('KECAP_MANIS', 'Indonesische dicke süße Sojasauce mit Palmzucker beziehungsweise vergleichbarer Süße; nicht helle Sojasauce.'),
    ('KEFIR', 'Fermentiertes Milchgetränk aus Kefirkulturen mit säuerlicher, leicht hefiger Note; nicht Buttermilch oder Joghurt.'),
    ('KETCHUP', 'Glatte süß-säuerliche Tomatenwürzsauce; Gewürzung und Süße können variieren, Bananenketchup bleibt getrennt.'),
    ('KIDNEY_BEANS', 'Nierenförmige rote Bohnen mit fester Schale und cremigem Inneren; getrocknet ausreichend garen oder vorgegart verwenden.'),
    ('KIMCHI', 'Koreanisches milchsauer fermentiertes Gemüse, meist Chinakohl oder Rettich, mit kräftiger Würzung; konkrete Sorte bleibt offen.'),
    ('KING_OYSTER_MUSHROOM', 'Kräuterseitling mit dickem, festem Stiel und mildem, umamireichem Aroma; Stiel und Hut sind essbar.'),
    ('KIWI', 'Kiwi mit saftigem süß-säuerlichem Fruchtfleisch und essbaren kleinen Samen; grüne und goldene Sorten sind umfasst.'),
    ('KOHLRABI', 'Knackige verdickte Kohlrabi-Sprossachse mit mild-kohligem Geschmack; Blätter können mitverwendet werden.'),
    ('KOMBU', 'Dicke getrocknete Braunalge, besonders zum Ansetzen umamireicher Fonds wie Dashi; nicht Nori oder Wakame.'),
    ('LAKSA_PASTE', 'Fertige südostasiatische Gewürzpaste für Laksa mit Chili, Aromaten und Gewürzen; regional unterschiedliche Stile sind umfasst.'),
    ('LAMB', 'Lammfleisch ohne Festlegung auf Zuschnitt oder Garmethode; gemeint ist Fleisch vom jungen Schaf.'),
    ('LAMBS_LETTUCE', 'Feldsalat mit kleinen zarten Blättern und mild-nussigem Geschmack; überwiegend roh verwendet.'),
    ('LAMB_CHOP', 'Lammkotelett mit Knochen aus Rücken oder Rippenbereich; zum kurzen Braten oder Grillen geeignet.'),
    ('LAMB_LEG', 'Lammkeule als großer, relativ magerer Braten- oder Schmorcut; ganz oder ausgelöst verwendbar.'),
    ('LAMB_MINCE', 'Zerkleinertes Lammfleisch mit charakteristischem Eigengeschmack; nicht gemischtes Hackfleisch.'),
    ('LAMB_SHOULDER', 'Kollagenreiche Lammschulter mit kräftigem Geschmack; besonders für langsames Braten oder Schmoren geeignet.'),
    ('LARD', 'Ausgelassenes Schweinefett zum Braten, Backen oder Verfeinern; natur gemeint, nicht fertiger Griebenschmalzaufstrich.'),
    ('LASAGNE_SHEETS', 'Breite flache Weizenpastablätter für geschichtete Gerichte; frisch, getrocknet oder vorgekocht verwendbar.'),
    ('LEAFY_GREENS', 'Offene Vorgabe für Gemüse, dessen Blätter kulinarisch im Mittelpunkt stehen; Salate und Kochgemüse sind möglich.'),
    ('LEEK', 'Lauch mit mild-süßlichem Zwiebelaroma; weißer und grüner Teil sind je nach Gericht verwendbar.'),
    ('LEGUMES', 'Offene Vorgabe für Hülsenfrüchte wie Bohnen, Linsen, Erbsen oder Kichererbsen; Produktform bleibt wählbar.'),
    ('LEMON', 'Zitrone mit aromatischer Schale und deutlich saurem Saft; Fruchtfleisch und unbehandelte Schale sind ebenfalls nutzbar.'),
    ('LEMONGRASS', 'Faserige aromatische Halme mit klarem Zitronenduft; meist angedrückt, fein geschnitten oder zum Mitkochen verwendet.'),
    ('LENTILS', 'Linsen als kleine trockene Hülsenfrüchte; Sorte, Farbe und Formstabilität bleiben offen.'),
    ('LETTUCE', 'Kopfsalat mit zarten bis knackigen Blättern und mildem Geschmack; nicht die gesamte Blattsalatfamilie.'),
    ('LIGHT_SOY_SAUCE', 'Dünnflüssige salzige Sojasauce für Würze und Umami; nicht die süßlichere dunkle Sojasauce.'),
    ('LIME', 'Limette mit intensiv aromatischer Schale und saurem Saft; konkrete Sorte bleibt offen.'),
    ('LINGONBERRY', 'Preiselbeeren mit herber Säure; frisch oder ungesüßt tiefgekühlt gemeint, nicht Konfitüre.'),
    ('LOTUS_ROOT', 'Rhizom der Lotuspflanze mit charakteristischen Hohlkammern und knackiger Textur; frisch, tiefgekühlt oder schlicht konserviert.'),
    ('LOVAGE', 'Liebstöckelblätter mit kräftigem sellerieartig-würzigem Aroma; frisch oder sparsam getrocknet, nicht Maggi-Würze.'),
    ('LUPIN', 'Essbare, fachgerecht entbitterte Lupinensamen beziehungsweise schlichtes Lupinenprodukt; nicht rohe bittere Samen.'),
    ('LYCHEE', 'Litschi mit saftigem, floral-süßem Fruchtfleisch; frisch oder schlicht konserviert, ohne Schale und Kern.');

INSERT INTO _ingredient_curator_note_backfill (code, curator_note)
VALUES
    ('MACADAMIA', 'Sehr fettreiche, cremig-knackige Macadamianüsse mit mild-buttrigem Geschmack; natur oder geröstet verwendbar.'),
    ('MACKEREL', 'Makrele als fettreicher Fisch mit kräftigem Eigengeschmack; frisch oder tiefgekühlt, nicht automatisch geräuchert.'),
    ('MAITAKE', 'Maitake beziehungsweise Klapperschwamm mit vielgliedrigen Büscheln und kräftig-würzigem Pilzaroma.'),
    ('MALT_VINEGAR', 'Essig aus vermälztem Getreide mit malzig-röstigem Aroma; nicht Bier oder chinesischer schwarzer Essig.'),
    ('MAM_RUOC', 'Vietnamesische fermentierte Garnelenpaste mit sehr intensivem salzigem Aroma; meist sparsam als Würze verwendet.'),
    ('MANDARIN', 'Mandarine als leicht schälbare, süß-aromatische Zitrusfrucht; Clementinen und ähnliche handelsübliche Formen sind umfasst.'),
    ('MANGO', 'Mango mit saftigem, süß-aromatischem Fruchtfleisch; Sorte und Reifegrad bleiben offen.'),
    ('MAPLE_SYRUP', 'Eingekochter Saft des Zuckerahorns mit karamellig-holzigem Aroma; nicht künstlich aromatisierter Pancake-Sirup.'),
    ('MARJORAM', 'Majoranblätter mit warmem, leicht süßlichem und herbem Aroma; frisch oder getrocknet verwendbar.'),
    ('MARSALA', 'Aufgespriteter sizilianischer Wein nach Marsala-Art, trocken bis süß; als Kochwein, nicht beliebiger Likörwein.'),
    ('MASA_HARINA', 'Nixtamalisiertes Maismehl für Tortillas und ähnliche Teige; nicht gewöhnliches Maismehl oder Maisstärke.'),
    ('MASCARPONE', 'Sehr fettreicher, milder italienischer Frischkäse aus Rahm mit dichter cremiger Textur.'),
    ('MASSAMAN_CURRY_PASTE', 'Fertige Thai-Currypaste nach Massaman-Art mit warmen Gewürzen, Chili und Aromaten; Markenrezepturen variieren.'),
    ('MATCHA', 'Fein vermahlener japanischer Grüntee mit intensiv grasigem, herbem Umami; kein gesüßtes Matcha-Getränkepulver.'),
    ('MAYONNAISE', 'Kalte Emulsionssauce aus Öl und Ei beziehungsweise Eigelb mit Säure; Würzung und Ölsorte bleiben offen.'),
    ('MEAT', 'Offene Vorgabe für Fleisch von Säugetieren; Tierart, Zuschnitt, Fettanteil und Garmethode bleiben wählbar.'),
    ('MELONS', 'Offene Vorgabe für süße Melonenfrüchte; Wasser-, Honig- und Cantaloupe-Melonen sind mögliche Ausprägungen.'),
    ('MERGUEZ', 'Kräftig gewürzte nordafrikanische Bratwurst, typischerweise aus Lamm- und/oder Rindfleisch mit Chili; nicht Schweinewurst.'),
    ('MILK', 'Flüssige Kuhmilch als Kochzutat; Fettstufe bleibt offen, Pflanzendrinks und gesäuerte Milchprodukte sind getrennt.'),
    ('MILK_CHOCOLATE', 'Schokolade mit Milchbestandteilen und deutlicher Süße; Kakaoanteil und konkrete Milchform können variieren.'),
    ('MILLET', 'Glutenfreie kleine Hirsekörner mit mild-nussigem Geschmack; Sorte und geschälte Produktform bleiben offen.'),
    ('MINCED_MEAT', 'Offene Vorgabe für zerkleinertes rohes Fleisch; Tierart und Fettanteil sind bewusst nicht festgelegt.'),
    ('MINT', 'Frische Minzblätter mit kühlendem, aromatischem Geschmack; konkrete Minzart bleibt offen.'),
    ('MIRABELLE', 'Kleine gelbe Mirabellenpflaume mit süßem, intensiv aromatischem Fruchtfleisch; frisch oder ungesüßt tiefgekühlt.'),
    ('MIRIN', 'Süßer japanischer Reiswürzwein mit Alkohol und ausgeprägter Süße; nicht Reisessig oder bloß gesüßter Sirup.'),
    ('MOLASSES', 'Dunkler zähflüssiger Rückstand der Zuckerherstellung mit kräftig karamellig-herbem Aroma; nicht heller Sirup.'),
    ('MOLE_PASTE', 'Konzentrierte mexikanische Würzpaste für Mole-Saucen mit Chili, Gewürzen und weiteren variablen Zutaten; nicht fertige Sauce.'),
    ('MOLLUSCS', 'Offene Vorgabe für Weichtiere wie Muscheln, Schnecken, Oktopus oder Kalmar; Krebstiere sind nicht gemeint.'),
    ('MONKFISH', 'Seeteufel mit festem, magerem und nahezu grätenfreiem Fleisch; meist als Schwanzfilet erhältlich.'),
    ('MOREL', 'Morcheln mit wabenartigem Hut und intensivem Waldpilzaroma; nur vollständig gegart verwenden.'),
    ('MOZZARELLA', 'Milder Pasta-filata-Käse mit elastischer bis weicher Textur; Kuh- und Büffelmilchvarianten sind umfasst.'),
    ('MSG', 'Reines Mononatriumglutamat als kristalline Umami-Würze; kein vollständiger Gewürzmix oder Brühpulver.'),
    ('MULBERRY', 'Maulbeeren mit süßem, mild-säuerlichem Aroma; frisch oder getrocknet verwendbar.'),
    ('MUNG_BEANS', 'Kleine grüne Mungbohnen mit mildem Geschmack; ganz, geschält oder vorgegart verwendbar, nicht ihre Sprossen.'),
    ('MUSHROOMS', 'Offene Vorgabe für essbare Pilze; Art, Kultur- oder Waldpilz und frisch oder getrocknet bleiben wählbar.'),
    ('MUSHROOM_STOCK', 'Brühe oder Fond mit Pilzen als prägender Aromabasis; selbst gekocht oder als schlichtes Fertigprodukt verwendbar.'),
    ('MUSSELS', 'Miesmuscheln mit dunkler Schale und saftigem, jodig-süßlichem Fleisch; frisch, tiefgekühlt oder ausgelöst verwendbar.'),
    ('MUSTARD', 'Verzehrfertige Senfzubereitung aus Senfsaat, Flüssigkeit und Würzung; Schärfe und Körnung bleiben offen.'),
    ('MUSTARD_SEED', 'Ganze Senfsamen mit nussiger bis stechend-scharfer Wirkung; gelbe, braune und schwarze Saat sind umfasst.'),
    ('NAPA_CABBAGE', 'Chinakohl mit hellen knackigen Rippen und zarten Blättern; roh, gegart oder fermentiert verwendbar.'),
    ('NATTO', 'Japanische fermentierte Sojabohnen mit klebrigen Fäden und kräftigem, erdig-würzigem Aroma.'),
    ('NDUJA', 'Weiche streichfähige kalabrische Schweinewurst mit hohem Chili- und Fettanteil; nicht feste Chorizo.'),
    ('NECTARINE', 'Glattschalige Steinfrucht aus der Pfirsichfamilie mit saftigem süß-säuerlichem Fleisch.'),
    ('NEUTRAL_OIL', 'Raffiniertes Pflanzenöl mit wenig Eigengeschmack und guter Hitzetoleranz; konkrete Ölpflanze bleibt offen.'),
    ('NEW_POTATOES', 'Jung geerntete Kartoffeln mit dünner Schale und wachsiger Textur; Sorte bleibt offen.'),
    ('NOODLES', 'Offene Vorgabe für geformte Nudeln aus Getreide oder Stärke; Rohstoff, Form und Küchentradition bleiben wählbar.'),
    ('NORI', 'Dünne getrocknete Blätter aus roten Meeresalgen, typischerweise geröstet; nicht Kombu oder Wakame.'),
    ('NUTMEG', 'Muskatnuss als intensiv warm-würziger Samenkern, frisch gerieben oder gemahlen; sparsam dosieren.'),
    ('NUTRITIONAL_YEAST', 'Inaktive getrocknete Hefeflocken mit nussig-käsigem Umami; keine aktive Backhefe.'),
    ('NUTS', 'Offene Vorgabe für kulinarisch als Nüsse verwendete Kerne; Sorte, Röstung und Zerkleinerung bleiben wählbar.'),
    ('NUT_AND_SEED_PASTES', 'Offene Familie fein vermahlener Nuss- oder Samenpasten; Rohstoff, Röstung und Süßung bleiben offen.'),
    ('OATS', 'Hafer als ganzes Korn, Grütze oder Flocken; konkrete Verarbeitungsform bleibt wählbar.'),
    ('OAT_DRINK', 'Flüssiger Pflanzendrink auf Haferbasis; gesüßte und ungesüßte sowie baristataugliche Varianten sind umfasst.'),
    ('OCTOPUS', 'Oktopus mit festen Armen und kollagenreichem Fleisch, das durch geeignete Garung zart wird; nicht Kalmar.'),
    ('OFFAL', 'Offene Vorgabe für essbare Innereien und verwandte Schlachtteile; Tierart und Organ bleiben bewusst wählbar.'),
    ('OILS', 'Offene Vorgabe für flüssige Speiseöle; Rohstoff, Raffination, Eigengeschmack und Hitzetoleranz bleiben offen.'),
    ('OILY_FISH', 'Offene Vorgabe für fettreiche Fischarten mit kräftigerem Geschmack und saftigem Fleisch.'),
    ('OLIVES', 'Essfertig entbitterte Oliven in Lake oder Öl; Farbe, Sorte, Entsteinung und Würzung bleiben offen.'),
    ('OLIVE_OIL', 'Speiseöl aus Oliven; natives aromatisches und raffiniertes milderes Öl sind je nach Anwendung möglich.'),
    ('ONION', 'Küchenzwiebel mit schwefelig-scharfem, beim Garen süßlichem Aroma; gelbe beziehungsweise braune Standardsorte gemeint.'),
    ('OOLONG_TEA', 'Teiloxidierter Tee zwischen grünem und schwarzem Tee; Stil reicht von floral-leicht bis dunkel geröstet.'),
    ('ORANGE', 'Süße Orange mit saftigem Fruchtfleisch und aromatischer Schale; Blutorange bleibt als eigene Ausprägung getrennt.'),
    ('OREGANO', 'Oregano mit kräftig-herbem, warmem Kräuteraroma; frisch oder getrocknet verwendbar.'),
    ('ORZO', 'Kleine reisförmige Weizenpasta, auch Kritharaki genannt; trotz der Form kein Reis.'),
    ('OXTAIL', 'Quergeschnittener Rinderschwanz mit Knochen, Fett und viel Kollagen; für langsames Schmoren oder Brühen geeignet.'),
    ('OYSTER', 'Auster als essbare Muschel mit jodig-salzigem Geschmack; lebend in der Schale oder ausgelöst verwendbar.'),
    ('OYSTER_MUSHROOM', 'Austernseitling mit breitem Hut, zart-faseriger Textur und mildem Umami; nicht Kräuterseitling.'),
    ('OYSTER_SAUCE', 'Dicke salzig-süßliche Würzsauce mit Austernextrakt und Umami; vegetarische Pilzvarianten sind nicht gemeint.'),
    ('PAK_CHOI', 'Asiatisches Kohlgemüse mit saftigen hellen Stielen und dunklen Blättern; beide Teile sind essbar.'),
    ('PALM_SUGAR', 'Aus Palmensaft eingekochter Zucker mit karamelligem Aroma; Block-, Pasten- und Granulatformen sind umfasst.'),
    ('PANCETTA', 'Italienischer gepökelter, meist ungeräucherter Schweinebauch; gerollt oder flach und roh zu garen beziehungsweise gereift.'),
    ('PANDAN_LEAVES', 'Lange aromatische Pandanblätter mit süßlich-grünem, vanilleähnlichem Duft; meist zum Mitgaren oder Extrahieren.'),
    ('PANEER', 'Ungereifter indischer Frischkäse mit fester, nicht schmelzender Textur; typischerweise aus Kuh- oder Büffelmilch.'),
    ('PANGASIUS', 'Milder weißfleischiger Süßwasserfisch, meist als grätenarmes Filet erhältlich.'),
    ('PANKO', 'Grobe luftige japanische Weißbrotbrösel für besonders knusprige Panaden; nicht feine Semmelbrösel.'),
    ('PAPAYA', 'Reife Papaya mit weichem, süß-mildem Fruchtfleisch; grüne unreife Papaya bleibt getrennt.'),
    ('PARMESAN', 'Sehr harter, lange gereifter italienischer Kuhmilchkäse nach Parmesan-Art; würzig, salzig und umamireich.'),
    ('PARSLEY', 'Frische Petersilienblätter mit grün-würzigem Aroma; glatte und krause Formen sind umfasst, nicht Petersilienwurzel.'),
    ('PARSNIP', 'Pastinake mit süßlich-erdigem, leicht würzigem Wurzelfleisch; nicht Petersilienwurzel.'),
    ('PASSION_FRUIT', 'Passionsfrucht mit aromatischem süß-saurem Fruchtmark und knackigen essbaren Kernen.'),
    ('PEACH', 'Pfirsich mit samtiger Schale und saftigem süß-aromatischem Fruchtfleisch; weiß- und gelbfleischige Sorten sind umfasst.'),
    ('PEANUT', 'Erdnusskerne mit kräftig-nussigem Aroma; roh, geröstet, ganz oder gehackt verwendbar.'),
    ('PEANUT_BUTTER', 'Streichfähige Erdnusspaste, glatt oder stückig; ungesüßte und leicht gesüßte Varianten sind umfasst.'),
    ('PEAR', 'Birne als saftiges Kernobst; Sorte, Festigkeit und Verhältnis von Süße zu Säure bleiben offen.'),
    ('PEARL_BARLEY', 'Geschälte und rund geschliffene Gerstenkörner, auch Graupen; schneller garend und weicher als ganze Gerste.'),
    ('PEAS', 'Offene Vorgabe für Erbsenkerne; frisch, getrocknet oder gespalten sind mögliche Wege, essbare Hülsen nicht automatisch.'),
    ('PECAN', 'Pekannusskerne mit buttrigem, mild-süßlichem Aroma; natur oder geröstet verwendbar.'),
    ('PECORINO', 'Harter bis halbfester italienischer Schafmilchkäse; Herkunft, Reifegrad und Salzintensität bleiben offen.'),
    ('PENNE', 'Kurze röhrenförmige Weizenpasta mit schrägen Enden; glatt oder geriffelt verwendbar.'),
    ('PERSIMMON', 'Kaki mit süßem orangefarbenem Fruchtfleisch; feste nichtadstringierende und weichreife Sorten sind umfasst.'),
    ('PESTO', 'Rohe oder wenig erhitzte Kräuter- beziehungsweise Pflanzenpaste mit Öl; Zutatenbasis bleibt offen, nicht nur Pesto Genovese.'),
    ('PICKLED_CUCUMBER', 'Essigbasierte Gewürzgurke mit süß-säuerlicher bis würziger Lake; nicht milchsauer fermentierte Salzgurke.'),
    ('PICKLED_GINGER', 'Dünn geschnittener, süß-säuerlich eingelegter Ingwer nach Gari-Art; nicht frisches Ingwer-Rhizom.'),
    ('PICKLED_HERRING', 'Hering in essig- oder säurebasierter Würzlake; süße, zwiebelige und cremig weiterverarbeitete Varianten sind möglich.'),
    ('PIKEPERCH', 'Zander als magerer Süßwasserfisch mit festem, mildem Fleisch und wenigen Gräten.'),
    ('PINEAPPLE', 'Ananas mit saftigem süß-säuerlichem Fruchtfleisch; frisch, tiefgekühlt oder schlicht konserviert verwendbar.'),
    ('PINE_NUT', 'Ölreiche Samen von Pinien mit mild-harzigem, buttrigem Aroma; roh oder geröstet verwendbar.'),
    ('PINTO_BEANS', 'Gesprenkelte Pintobohnen mit erdig-cremigem Geschmack; getrocknet oder vorgegart verwendbar.'),
    ('PISTACHIO', 'Grüne Pistazienkerne mit süßlich-nussigem Aroma; ungesalzen, roh oder geröstet verwendbar.'),
    ('PITA', 'Rundes weiches Fladenbrot, häufig mit beim Backen entstehender Tasche; nicht Tortilla.'),
    ('PLAICE', 'Scholle als magerer Plattfisch mit zartem, mildem Fleisch; ganz oder als Filet verwendbar.'),
    ('PLANTAIN', 'Stärkereiche Kochbanane, meist gegart verwendet; grüne und reife süßere Stadien sind umfasst, nicht Dessertbanane.'),
    ('PLANT_PROTEIN_PRODUCTS', 'Offene Vorgabe für verarbeitete pflanzliche Proteinprodukte wie Tofu, Seitan oder Mykoprotein; Rohstoff bleibt wählbar.'),
    ('PLUM', 'Pflaume beziehungsweise Zwetschge als saftige Steinfrucht; Sorte, Süße und Festigkeit bleiben offen.'),
    ('POBLANO', 'Große dunkelgrüne mexikanische Chili mit milder bis mittlerer Schärfe; getrocknet heißt sie Ancho.'),
    ('POD_VEGETABLES', 'Offene Vorgabe für Gemüse aus jungen Hülsen, Schoten oder darin enthaltenen frischen Samen.'),
    ('POINTED_CABBAGE', 'Zarter kegelförmiger Spitzkohl mit milderem Geschmack als Weißkohl; roh und gegart verwendbar.'),
    ('POLENTA', 'Maisgrieß beziehungsweise daraus gegarte schnittfeste oder cremige Polenta; Körnung und Vorbehandlung bleiben offen.'),
    ('POMEGRANATE', 'Granatapfel mit saftig-säuerlichen Samenhüllen; gemeint sind Frucht und Kerne, nicht Sirup.'),
    ('POMEGRANATE_MOLASSES', 'Dick eingekochter Granatapfelsaft mit intensiver süß-saurer Fruchtigkeit; nicht Zuckerrohrmelasse.'),
    ('POMELO', 'Sehr große Zitrusfrucht mit dickem Mesokarp und mild bitter-säuerlichen Fruchtsegmenten; nicht Grapefruit.'),
    ('POME_FRUIT', 'Offene Vorgabe für Kernobst wie Apfel, Birne oder Quitte; Sorte und Reifegrad bleiben wählbar.'),
    ('PONZU', 'Japanische zitrusbetonte Würzsauce, meist mit Sojasauce und Dashi-Komponenten; konkrete Zitrusfrucht kann variieren.'),
    ('POPPY_SEEDS', 'Mohnsamen mit nussigem Aroma; ganz, gemahlen oder als ungesüßte Mohnmasse verwendbar.'),
    ('PORCINI', 'Steinpilze mit festem Fleisch und intensiv nussig-umamireichem Waldpilzaroma; frisch oder getrocknet verwendbar.'),
    ('PORK', 'Offene Vorgabe für Schweinefleisch; Zuschnitt, Fettanteil und geeignete Garmethode bleiben bewusst wählbar.'),
    ('PORK_BELLY', 'Durchwachsener Schweinebauch mit Schichten aus Fleisch und Fett; mit oder ohne Schwarte verwendbar.'),
    ('PORK_CHEEK', 'Kleiner, kollagenreicher Zuschnitt aus der Schweinebacke; durch langsames Garen besonders zart.'),
    ('PORK_CHOP', 'Schweinekotelett aus dem Rücken mit Rippen- oder Wirbelknochen; zum Braten oder Grillen geeignet.'),
    ('PORK_CUTLET', 'Dünne magere Schweinefleischscheibe für Schnitzel; paniert oder unpaniert, gemeint ist der Zuschnitt.'),
    ('PORK_KNUCKLE', 'Schweinshaxe mit Knochen, Schwarte und viel Bindegewebe; für langes Braten, Kochen oder Schmoren geeignet.'),
    ('PORK_LIVER', 'Schweineleber mit kräftigem, mineralischem Geschmack und weicher Textur; nicht Leberwurst.'),
    ('PORK_LOIN', 'Magerer Schweinerücken als Kotelettstrang oder ausgelöstes Stück; nicht Schweinefilet.'),
    ('PORK_MINCE', 'Zerkleinertes Schweinefleisch mit variablem Fettanteil; nicht gemischtes Hackfleisch.'),
    ('PORK_NECK', 'Gut marmorierter Schweinenacken mit saftigem Fleisch; zum Grillen, Braten oder Schmoren geeignet.'),
    ('PORK_RIBS', 'Fleischige Schweinerippen mit Knochen und Bindegewebe; Rippenabschnitt und Zuschnitt bleiben offen.'),
    ('PORK_SHOULDER', 'Durchwachsene Schweineschulter mit Bindegewebe; besonders für Braten, Schmoren oder Zupffleisch geeignet.'),
    ('PORK_STOCK', 'Brühe oder Fond auf Basis von Schweinefleisch und/oder -knochen; nicht fertige Suppe.'),
    ('PORK_TENDERLOIN', 'Sehr mageres und zartes Schweinefilet für kurze bis mittlere Garung; nicht Schweinerücken.'),
    ('PORK_TONGUE', 'Schweinezunge als festes, nach langem Garen zartes Muskelfleisch; vor dem Servieren üblicherweise gehäutet.'),
    ('PORT_WINE', 'Aufgespriteter portugiesischer Wein nach Portwein-Art mit deutlicher Süße und konzentriertem Fruchtaroma.'),
    ('POTATO', 'Kartoffel als stärkehaltige Knolle; Sorte, Kochtyp und Zubereitungsform bleiben offen.'),
    ('POTATO_STARCH', 'Feine geschmacksneutrale Stärke aus Kartoffeln zum Binden und für Teige; nicht Kartoffelmehl aus ganzen Knollen.'),
    ('POULTRY', 'Offene Vorgabe für Geflügelfleisch wie Hähnchen, Ente, Gans oder Pute; Tierart und Zuschnitt bleiben wählbar.'),
    ('PRESERVED_FISH', 'Offene Familie durch Salz, Trocknung, Räuchern, Einlegen oder Konservieren haltbar gemachter Fischprodukte.'),
    ('PRESERVED_LEMON', 'In Salzlake gereifte ganze oder geteilte Zitrone mit weicher Schale und intensiv salzig-zitrischem Aroma.'),
    ('PRESERVED_PRODUCE', 'Offene Vorgabe für eingelegtes, fermentiertes, getrocknetes oder anderweitig konserviertes pflanzliches Produkt.'),
    ('PROSCIUTTO', 'Italienischer luftgetrockneter Rohschinken nach Prosciutto-crudo-Art; dünn geschnitten oder als Kochzutat verwendbar.'),
    ('PRUNE', 'Getrocknete Pflaume mit konzentrierter Süße und weicher bis zäher Textur; entsteint oder mit Stein verwendbar.'),
    ('PUL_BIBER', 'Türkisch geprägte grobe Chiliflocken, häufig mild bis mittelscharf und leicht ölig; Aleppo-Stil ist eine mögliche Ausprägung.'),
    ('PUMPKIN', 'Speisekürbis mit festem bis cremigem Fruchtfleisch; die konkrete Sorte bleibt wählbar.'),
    ('PUMPKIN_SEEDS', 'Grüne geschälte oder ganze Kürbiskerne mit nussigem Aroma; roh oder geröstet verwendbar.'),
    ('PURSLANE', 'Portulak mit fleischigen Blättern, frischer Säure und leicht salzigem Geschmack; roh oder kurz gegart verwendbar.'),
    ('QUAIL', 'Wachtelfleisch als kleines, aromatisches Geflügel; ganz oder in Teilstücken verwendbar.'),
    ('QUAIL_EGG', 'Kleines gesprenkeltes Wachtelei mit höherem Eigelbanteil; frisch zu garen, nicht eingelegt.'),
    ('QUARK', 'Frischer säuerlicher Milchbruch mit magerer bis cremiger Konsistenz; Fettstufe bleibt offen.'),
    ('QUINCE', 'Quitte mit festem, roh herbem und beim Garen floral-aromatischem Fruchtfleisch; meist gegart verwendet.'),
    ('QUINOA', 'Glutenfreies Pseudogetreide mit kleinen Samen und leicht nussigem Geschmack; helle, rote und schwarze Sorten sind umfasst.'),
    ('RABBIT', 'Kaninchenfleisch mit magerem, mildem Geschmack; ganzes Tier oder Teilstücke sind verwendbar, unabhängig von Haus- oder Wildhaltung.'),
    ('RADICCHIO', 'Rot-weißer Blattsalat aus der Zichorienfamilie mit markanter Bitterkeit; roh oder gegart verwendbar.'),
    ('RADISH', 'Offene Rettichvorgabe von kleinen Radieschen bis größeren weißen oder schwarzen Rettichen; Schärfe und Form bleiben wählbar.'),
    ('RAISIN', 'Getrocknete Weintrauben mit konzentrierter Süße; helle und dunkle sowie kleine und große Formen sind umfasst.'),
    ('RAMEN_NOODLES', 'Japanische Weizennudeln für Ramen, typischerweise alkalisch und elastisch; frisch, getrocknet oder vorgegart verwendbar.'),
    ('RASPBERRY', 'Himbeere mit zarter Struktur und süß-säuerlichem Aroma; frisch oder ungesüßt tiefgekühlt verwendbar.'),
    ('RAS_EL_HANOUT', 'Nordafrikanische Gewürzmischung aus zahlreichen warmen, erdigen und floralen Gewürzen; Rezeptur variiert stark.'),
    ('RAZOR_CLAMS', 'Längliche Schwert- beziehungsweise Messermuscheln mit zartem, leicht süßlichem Fleisch; frisch oder ausgelöst verwendbar.'),
    ('REDFISH', 'Rotbarsch mit festem, mildem und relativ magerem Fleisch; meist als Filet erhältlich.'),
    ('RED_BELL_PEPPER', 'Reif rote Gemüsepaprika mit süßem, fruchtigem Geschmack; frisch gemeint, nicht geröstete Konserve.'),
    ('RED_CABBAGE', 'Rotkohl mit festen violetten Blättern und leicht pfeffrigem Geschmack; roh, geschmort oder fermentiert verwendbar.'),
    ('RED_CURRANT', 'Rote Johannisbeere mit klarer Säure und saftigem Fruchtfleisch; frisch oder ungesüßt tiefgekühlt.'),
    ('RED_LENTILS', 'Geschälte rote Linsen, die schnell garen und meist cremig zerfallen; nicht formstabile ganze Linsen.'),
    ('RED_ONION', 'Rote Zwiebel mit milderer Schärfe und violetter Farbe; roh und gegart verwendbar.'),
    ('RED_WINE', 'Rotwein als Kochzutat; Rebsorte, Körper und Trockenheitsgrad bleiben offen, kein aromatisiertes Weingetränk.'),
    ('RED_WINE_VINEGAR', 'Aus Rotwein vergorener Essig mit fruchtig-herber Säure; nicht Rotwein oder Balsamico.'),
    ('RENDANG_PASTE', 'Konzentrierte Gewürzpaste für Rendang mit Chili, Aromaten und Gewürzen; nicht das fertige Schmorgericht.'),
    ('RHUBARB', 'Fleischige saure Blattstiele des Rhabarbers; nur die Stiele verwenden, nicht die Blätter.'),
    ('RICE', 'Reiskorn als Kochzutat; Sorte, Kornlänge, Vollkornanteil und Klebrigkeit bleiben bewusst wählbar.'),
    ('RICE_CAKES', 'Koreanische Reiskuchen nach Tteok-Art mit zäher, elastischer Textur; Form und frisch oder tiefgekühlt bleiben offen.'),
    ('RICE_FLOUR', 'Fein gemahlener Reis, weiß oder als Vollkorn; nicht reine Reisstärke.'),
    ('RICE_NOODLES', 'Nudeln überwiegend auf Reisbasis; Breite, Form und Frisch- oder Trockenware bleiben offen.'),
    ('RICE_PAPER', 'Dünne trockene Blätter auf Reisbasis zum Einweichen und Rollen; nicht essbares Dekorpapier.'),
    ('RICE_PRODUCTS', 'Offene Vorgabe für verarbeitete Reisprodukte wie Nudeln, Reiskuchen, Mehl oder Papier; gewöhnliches Reiskorn bleibt getrennt.'),
    ('RICE_VINEGAR', 'Milder Essig aus Reis beziehungsweise Reiswein; helle und dunklere regionale Varianten sind möglich.'),
    ('RICOTTA', 'Milder italienischer Molkenfrischkäse mit körnig-cremiger Textur; Kuh-, Schaf- oder andere Milchbasis möglich.'),
    ('RISOTTO_RICE', 'Stärkereiche mittel- bis kurzkörnige Reissorte für cremiges Risotto, etwa Arborio oder Carnaroli.'),
    ('ROASTED_RED_PEPPER', 'Geröstete und gehäutete rote Paprika, frisch zubereitet oder schlicht in Glas beziehungsweise Öl konserviert.'),
    ('ROMAINE_LETTUCE', 'Römersalat mit länglichen kräftigen Blättern und knackiger Mittelrippe; roh oder gegrillt verwendbar.'),
    ('ROMANESCO', 'Hellgrünes Kohlgemüse mit fraktal geformtem Blütenstand und mild-nussigem Geschmack; nicht Brokkoli.'),
    ('ROOT_VEGETABLES', 'Offene Vorgabe für kulinarisch genutzte Wurzeln und Knollen; Art, Stärkegehalt und Süße bleiben wählbar.'),
    ('ROSEMARY', 'Rosmarinnadeln mit harzigem, kampferartigem Aroma; frisch oder getrocknet sparsam verwendbar.'),
    ('RUM', 'Spirituose aus Zuckerrohrprodukten; weißer, goldener oder dunkler Rum und Süßegrad bleiben offen.'),
    ('RUTABAGA', 'Steckrübe mit dichtem gelblichem Fleisch und mild erdig-süßlichem Kohlaroma; nicht Speiserübe.'),
    ('RYE_BREAD', 'Brot mit Roggen als prägendem Getreide; Misch- und Vollkornformen sind umfasst, Sauerteig wird nicht zwingend vorausgesetzt.'),
    ('RYE_FLOUR', 'Mehl aus Roggen mit kräftigem Getreidearoma; Ausmahlungsgrad bleibt offen.');

INSERT INTO _ingredient_curator_note_backfill (code, curator_note)
VALUES
    ('SAGE', 'Salbeiblätter mit kräftig herbem, kampferartigem Aroma; frisch oder getrocknet und meist sparsam verwendet.'),
    ('SAKE', 'Japanisches vergorenes Reisgetränk; trocken bis süß und als Kochsake oder Trinkqualität verwendbar, nicht Mirin.'),
    ('SALAD_GREENS', 'Offene Vorgabe für roh geeignete Blattsalate; Sorte, Bitterkeit und Blattstruktur bleiben wählbar.'),
    ('SALAMI', 'Luftgetrocknete beziehungsweise gereifte Rohwurst der Salami-Familie; Tierart, Körnung und Würzung können variieren.'),
    ('SALMON', 'Lachs als fettreicher Fisch mit festem, saftigem Fleisch; frisch oder tiefgekühlt, nicht bereits geräuchert oder gebeizt.'),
    ('SALMON_ROE', 'Lachsrogen mit großen orangefarbenen, salzig platzenden Eiern; meist gesalzen als Ikura erhältlich.'),
    ('SALSA', 'Fertige oder frisch zubereitete mexikanisch geprägte Würzsauce; Tomaten-, Chili-, Frucht- und Rohvarianten sind möglich.'),
    ('SAMBAL_BRANDAL', 'Gebratenes indonesisches Sambal mit Chili, Aromaten und häufig süßlich-würziger Tiefe; nicht Sambal Oelek.'),
    ('SAMBAL_OELEK', 'Schlichte grobe Chilipaste vor allem aus roten Chilis, Salz und Säure; nicht süßes oder komplex gebratenes Sambal.'),
    ('SARDINES', 'Sardinen als kleine fettreiche Meeresfische; frisch oder tiefgekühlt, Dosenware ist eine eigene Produktform.'),
    ('SAUCES_AND_PASTES', 'Offene Vorgabe für Saucen, Würzmittel und Pasten, die ein Gericht geschmacklich prägen; konkrete Basis bleibt offen.'),
    ('SAUERKRAUT', 'Milchsauer fermentierter fein geschnittener Weißkohl mit deutlicher Säure; roh oder gegart verwendbar.'),
    ('SAUSAGE', 'Offene Wurstfamilie; Tierart, Brüh-, Koch-, Brat- oder Reifeform und Würzung bleiben bewusst wählbar.'),
    ('SAVOY_CABBAGE', 'Wirsing mit gekräuselten zarten Blättern und mild-würzigem Kohlaroma; roh nur bei zarten Blättern, sonst gegart.'),
    ('SCALLOPS', 'Jakobsmuscheln mit festem, süßlichem Muskelfleisch; mit oder ohne Rogen und frisch oder tiefgekühlt verwendbar.'),
    ('SEAFOOD', 'Offene Vorgabe für Fisch und essbare Meerestiere; konkrete Tiergruppe, Fettgehalt und Produktform bleiben wählbar.'),
    ('SEA_BASS', 'Wolfsbarsch mit mildem, festem und magerem Fleisch; ganz oder als Filet verwendbar.'),
    ('SEA_BREAM', 'Dorade beziehungsweise Meerbrasse mit festem, mildem Fleisch; ganz oder als Filet verwendbar.'),
    ('SEEDS', 'Offene Vorgabe für kulinarisch genutzte Kerne und Samen; Sorte, Röstung und Zerkleinerung bleiben wählbar.'),
    ('SEMOLINA', 'Körniger Hartweizengrieß für Teige, Breie oder Bindung; nicht feines Weizenmehl.'),
    ('SERRANO_CHILI', 'Schlanke frische Serrano-Chili mit mittlerer bis hoher Schärfe und frischem grünen Aroma.'),
    ('SERRANO_HAM', 'Spanischer luftgetrockneter Rohschinken nach Serrano-Art; nicht italienischer Prosciutto.'),
    ('SESAME_OIL', 'Öl aus Sesam; geröstetes Öl ist intensiv würzend, helles ungeröstetes Öl milder und hitzetauglicher.'),
    ('SESAME_SEEDS', 'Sesamsamen mit nussigem Aroma; hell oder schwarz, roh oder geröstet verwendbar.'),
    ('SHALLOT', 'Kleine längliche Schalotte mit feinerem, milderem Zwiebelaroma; nicht Frühlingszwiebel.'),
    ('SHAOXING_WINE', 'Chinesischer fermentierter Reiswein nach Shaoxing-Art mit nussig-oxidativem Aroma; als Kochwein, nicht Reisessig.'),
    ('SHELLFISH', 'Offene Vorgabe für Schalen- und Krustentiere, insbesondere Krebstiere und zweischalige Muscheln.'),
    ('SHERRY', 'Aufgespriteter spanischer Wein nach Sherry-Art; trocken-oxidative bis süße Stile sind je nach Gericht möglich.'),
    ('SHERRY_VINEGAR', 'Aus Sherrywein erzeugter gereifter Essig mit nussig-komplexer Säure; nicht Sherry oder Rotweinessig.'),
    ('SHIITAKE', 'Shiitake mit fleischigem Biss und kräftigem Umami; frisch oder getrocknet, wobei Trockenware intensiver schmeckt.'),
    ('SHIMEJI', 'Büschelig wachsende japanische Zuchtpilze mit festem Biss und mild-nussigem Aroma; braune und weiße Formen sind umfasst.'),
    ('SHIRATAKI', 'Transparente, sehr stärkearme Nudeln aus Konjak mit elastischem Biss; nicht Glas- oder Reisnudeln.'),
    ('SHRIMP', 'Garnelen als Krebstiere mit festem, leicht süßlichem Fleisch; Größe, Schale und frisch oder tiefgekühlt bleiben offen.'),
    ('SHRIMP_PASTE', 'Offene Familie fermentierter Garnelenpasten mit sehr intensivem salzigem Umami; regionale feste und weiche Formen sind umfasst.'),
    ('SICHUAN_PEPPER', 'Aromatische Samenkapseln verschiedener Zanthoxylum-Arten mit zitrischem Duft und prickelnd-betäubender Wirkung; kein echter Pfeffer.'),
    ('SILKEN_TOFU', 'Sehr weicher, kaum gepresster Tofu mit glatter puddingartiger Textur; nicht fester Tofu.'),
    ('SMOKED_PAPRIKA', 'Geräuchertes Paprikapulver mit süßer bis scharfer Ausprägung und deutlichem Raucharoma.'),
    ('SMOKED_SALMON', 'Heiß- oder kaltgeräucherter Lachs mit salzigem Raucharoma; nicht bloß gebeizter Gravlax.'),
    ('SMOKED_TOFU', 'Fester Tofu mit deutlichem Raucharoma, durch Räuchern oder entsprechende Verarbeitung; nicht fermentierter Tofu.'),
    ('SMOKED_TROUT', 'Geräucherte Forelle, ganz oder als Filet, mit festem Fleisch und mildem Raucharoma.'),
    ('SOLE', 'Seezunge als feiner magerer Plattfisch mit zartem, festem Fleisch; nicht Scholle.'),
    ('SOURDOUGH_BREAD', 'Brot mit Sauerteig als prägendem Trieb- und Aromamittel; Getreide und Säuregrad bleiben offen.'),
    ('SOUR_CHERRY', 'Sauerkirsche mit deutlich höherer Säure als Süßkirsche; frisch, tiefgekühlt oder ungesüßt konserviert verwendbar.'),
    ('SOUR_CREAM', 'Gesäuerter Rahm mit frischer Säure und mittlerem Fettgehalt; nicht Crème fraîche oder Quark.'),
    ('SOYBEANS', 'Reife Sojabohnen als trockene oder vorgegarte Hülsenfrucht; nicht junge grüne Edamame.'),
    ('SOY_DRINK', 'Flüssiger Pflanzendrink aus Sojabohnen; gesüßte und ungesüßte Varianten sind umfasst.'),
    ('SOY_PRODUCTS', 'Offene Vorgabe für Sojabohnen und daraus hergestellte kulinarische Produkte; konkrete Verarbeitung bleibt wählbar.'),
    ('SOY_SAUCE', 'Fermentierte salzige Würzsauce auf Sojabohnenbasis; Stil, Weizenanteil, Farbe und Intensität bleiben offen.'),
    ('SPAETZLE', 'Weiche unregelmäßige Eiernudeln aus zähflüssigem Teig; frisch, getrocknet oder vorgegart verwendbar.'),
    ('SPAGHETTI', 'Lange dünne runde Weizenpasta; Vollkorn- und gewöhnliche Hartweizenvarianten sind umfasst.'),
    ('SPAGHETTI_SQUASH', 'Kürbis, dessen gegartes Fruchtfleisch in spaghettiartige Fasern zerfällt; nicht Pasta.'),
    ('SPELT', 'Dinkelkorn als Getreide mit nussigem Aroma; ganz, geschrotet oder als Flocken, nicht Dinkelmehl.'),
    ('SPICES', 'Offene Vorgabe für trockene Gewürze und Würzmittel; Pflanzenteil, Form und Aromaprofil bleiben wählbar.'),
    ('SPICE_BLENDS', 'Offene Vorgabe für bewusst zusammengesetzte trockene Gewürzmischungen; Stil und Schärfe bleiben offen.'),
    ('SPINACH', 'Spinatblätter mit mild-grünem, leicht mineralischem Geschmack; frisch oder tiefgekühlt verwendbar.'),
    ('SPLIT_PEAS', 'Getrocknete geschälte und halbierte Erbsen für Suppen, Pürees oder Eintöpfe; Farbe bleibt offen.'),
    ('SPRING_ONION', 'Frühlingszwiebel mit mildem Zwiebelaroma; weißer und grüner Teil sind essbar.'),
    ('SPROUTS', 'Offene Vorgabe für essbare junge Keimlinge; Pflanzenart, Größe und roh oder gegart bleiben wählbar.'),
    ('SQUID', 'Kalmar mit röhrenförmigem Mantel und Armen; kurz oder sehr lange garen, nicht Oktopus oder Sepia.'),
    ('SRIRACHA', 'Glatte fermentierte oder gereifte Chilisauce nach Sriracha-Art mit Knoblauch, Säure und leichter Süße.'),
    ('STARCHES', 'Offene Vorgabe für stärkeprägende Zutaten oder Sättigungsbeilagen; Getreide, Knolle und Produktform bleiben wählbar.'),
    ('STARCH_BINDERS', 'Offene Vorgabe für isolierte Stärke und andere neutrale Bindemittel; Rohstoff und Bindeeigenschaft bleiben offen.'),
    ('STAR_ANISE', 'Sternförmige Frucht mit intensiv süßlichem Anisaroma; ganz oder gemahlen sparsam verwendbar.'),
    ('STEM_VEGETABLES', 'Offene Vorgabe für Gemüse mit kulinarisch prägendem Stiel, Spross oder verdickter Sprossachse.'),
    ('STICKY_RICE', 'Klebreis mit hohem Amylopektinanteil und stark haftender Textur; weiß, schwarz oder violett möglich, nicht Sushireis.'),
    ('STINKY_TOFU', 'Intensiv fermentierter Tofu ostasiatischer Art mit markantem Geruch; Produktform und spätere Garung bleiben offen.'),
    ('STOCKS', 'Offene Vorgabe für Brühe oder Fond als aromatische Flüssigkeitsbasis; tierische, pflanzliche und pilzbasierte Formen sind möglich.'),
    ('STONE_FRUIT', 'Offene Vorgabe für Steinobst mit einem zentralen harten Kern; Art, Süße und Reifegrad bleiben wählbar.'),
    ('STRAWBERRY', 'Erdbeere mit süß-säuerlichem, aromatischem Fruchtfleisch; frisch oder ungesüßt tiefgekühlt verwendbar.'),
    ('SUGAR_SNAP_PEAS', 'Zuckerschoten mit essbarer knackiger Hülse und süßen jungen Erbsen; nicht ausgelöste grüne Erbsen.'),
    ('SUMAC', 'Getrocknete gemahlene Sumachfrüchte mit fruchtig-zitroniger Säure; nicht giftiger Zier-Sumach.'),
    ('SUNFLOWER_SEEDS', 'Sonnenblumenkerne mit mild-nussigem Geschmack; geschält, roh oder geröstet verwendbar.'),
    ('SUN_DRIED_TOMATO', 'Durch Trocknung konzentrierte Tomaten mit süß-säuerlichem Umami; trocken oder in Öl eingelegt verwendbar.'),
    ('SURIMI', 'Gegartes geformtes Fischmusprodukt, häufig als Krebsfleischimitat; nicht echtes Krabbenfleisch.'),
    ('SUSHI_RICE', 'Japanischer Rundkornreis mit haftender Textur, üblicherweise nach dem Garen gewürzt; nicht beliebiger Klebreis.'),
    ('SWEETENERS', 'Offene Vorgabe für Zucker, Sirupe, Honig und andere kulinarische Süßungsmittel; Form und Eigengeschmack bleiben offen.'),
    ('SWEET_PAPRIKA_POWDER', 'Mildes süßlich-fruchtiges Paprikapulver ohne prägende Schärfe oder Räucherung.'),
    ('SWEET_POTATO', 'Stärkereiche Süßkartoffelknolle mit süßlichem Geschmack; orange, violette und helle Sorten sind umfasst, nicht Yams.'),
    ('SWORDFISH', 'Schwertfisch mit festem, fleischigem und eher magerem Fischfleisch; meist als Steak oder Filet verwendet.'),
    ('TAHINI', 'Fein vermahlene Sesampaste, meist aus geschältem und geröstetem oder ungeröstetem Sesam; nicht fertige Tahinisauce.'),
    ('TAMARI', 'Japanische Sojasauce mit hohem Soja- und meist geringem oder keinem Weizenanteil; kräftig und umamireich.'),
    ('TAPENADE', 'Mediterrane Olivenpaste mit typischerweise Kapern und häufig Sardellen; konkrete Olivensorte und Würzung variieren.'),
    ('TAPIOCA_STARCH', 'Feine Stärke aus Maniok mit starker Bindung und elastischer Texturwirkung; nicht ganze Maniokwurzel.'),
    ('TARO', 'Stärkereiche Taroknolle mit mild-nussigem Geschmack; nur geschält und vollständig gegart verwenden.'),
    ('TARRAGON', 'Estragonblätter mit anisartigem, leicht bitterem Aroma; frisch oder getrocknet verwendbar.'),
    ('TEA', 'Offene Vorgabe für Aufguss und Blattmaterial der Teepflanze; Oxidation, Röstung und Sorte bleiben wählbar.'),
    ('TERIYAKI_SAUCE', 'Japanisch geprägte süß-salzige Glasur- und Würzsauce auf Sojasaucenbasis; Dicke und Süße variieren.'),
    ('THAI_BASIL', 'Thai-Basilikum mit anis- beziehungsweise lakritzartigem Aroma und festerem Blatt; nicht gewöhnliches süßes Basilikum.'),
    ('THAI_GREEN_CURRY_PASTE', 'Grüne Thai-Currypaste mit frischen grünen Chilis, Kräutern und Aromaten; Markenrezepturen variieren.'),
    ('THAI_RED_CURRY_PASTE', 'Rote Thai-Currypaste auf Basis getrockneter roter Chilis, Aromaten und Gewürzen; Markenrezepturen variieren.'),
    ('THAI_YELLOW_CURRY_PASTE', 'Gelbe Thai-Currypaste mit Kurkuma und warmen Gewürzen neben Chili und Aromaten; nicht Currypulver.'),
    ('THYME', 'Thymianblätter mit kräftig herb-würzigem Aroma; frisch oder getrocknet verwendbar.'),
    ('TOFU', 'Geronnener Sojabohnenquark; Festigkeit und Wassergehalt bleiben offen, fermentierte und geräucherte Formen sind getrennt.'),
    ('TOMATILLO', 'Grüne bis gelbliche Physalis-Verwandte mit papierartiger Hülle und frischer, deutlich säuerlicher Frucht; nicht grüne Tomate.'),
    ('TOMATO', 'Frische Tomate als saftig-säuerliches Fruchtgemüse; Sorte, Farbe und Größe bleiben offen.'),
    ('TOMATO_PASSATA', 'Fein passierte, unkonzentrierte Tomaten ohne Schale und Kerne; nicht Tomatensauce oder Tomatenmark.'),
    ('TOMATO_PASTE', 'Stark konzentriertes Tomatenpüree mit dichtem Umami; einfach bis mehrfach konzentriert, nicht Ketchup.'),
    ('TOMATO_PRODUCTS', 'Offene Vorgabe für verarbeitete Tomatenprodukte wie Konserve, Passata, Mark oder schlichte Sauce.'),
    ('TORTILLA', 'Dünnes ungesäuertes Fladenbrot aus nixtamalisiertem Mais oder Weizen; nicht spanische Eier-Kartoffel-Tortilla.'),
    ('TRIPE', 'Gereinigte essbare Vormägen, meist vom Rind, mit fester wabenartiger Textur; ausreichend vorgaren.'),
    ('TROPICAL_FRUIT', 'Offene Vorgabe für kulinarisch als tropisch verstandenes Obst; Art, Reife und Säure-Süße-Profil bleiben wählbar.'),
    ('TROUT', 'Forelle als fettreicher Süßwasserfisch mit zartem Fleisch; frisch oder tiefgekühlt, nicht geräuchert.'),
    ('TROUT_ROE', 'Forellenrogen mit kleinen orangefarbenen, salzig platzenden Eiern; meist leicht gesalzen erhältlich.'),
    ('TURKEY', 'Putenfleisch ohne Festlegung auf Brust, Keule oder Hack; Zuschnitt und Fettanteil bleiben offen.'),
    ('TURKEY_BREAST', 'Mageres helles Brustfleisch der Pute; als Filet, Schnitzel oder größeres Stück verwendbar.'),
    ('TURKEY_MINCE', 'Zerkleinertes Putenfleisch mit geringem bis mittlerem Fettanteil; nicht gemischtes Geflügelhack.'),
    ('TURMERIC', 'Getrocknetes gemahlenes Kurkuma mit erdig-warmem Aroma und starker gelber Färbung; nicht frisches Rhizom.'),
    ('TURNIP', 'Speiserübe mit weißem bis gelblichem, mild scharfem Wurzelfleisch; nicht Steckrübe.'),
    ('UDON', 'Dicke japanische Weizennudeln mit weichem, elastischem Biss; frisch, gefroren oder getrocknet verwendbar.'),
    ('VANILLA', 'Echte Vanille als Schote, Mark oder reiner Extrakt mit floral-süßem Aroma; nicht Vanillinzucker.'),
    ('VEAL', 'Offene Vorgabe für Kalbfleisch; Zuschnitt, Fettanteil und Garmethode bleiben bewusst wählbar.'),
    ('VEAL_CUTLET', 'Dünne Kalbfleischscheibe für Schnitzel; paniert oder unpaniert, gemeint ist der Zuschnitt.'),
    ('VEAL_LIVER', 'Zarte Kalbsleber mit milderem Geschmack als Rinderleber; kurze Garung bewahrt die weiche Textur.'),
    ('VEAL_SHANK', 'Quergeschnittene oder ganze Kalbshaxe mit Knochen und Kollagen; für langsames Schmoren wie bei Ossobuco geeignet.'),
    ('VEGETABLES', 'Offene Vorgabe für kulinarisch als Gemüse verwendete Pflanzen und Pflanzenteile; Art und Textur bleiben wählbar.'),
    ('VEGETABLE_STOCK', 'Pflanzliche Brühe oder Fond aus Gemüse und Aromaten; selbst gekocht oder als schlichtes Fertigprodukt verwendbar.'),
    ('VENISON', 'Hirschfleisch mit magerem, kräftigem Wildaroma; konkrete Hirschart und Zuschnitt bleiben offen.'),
    ('VIETNAMESE_CORIANDER', 'Vietnamesischer Koriander beziehungsweise Rau răm mit pfeffrig-zitrischem Aroma; botanisch kein echter Koriander.'),
    ('VINEGAR', 'Offene Vorgabe für Speiseessig; Rohstoff, Reife, Süße und Säureprofil bleiben wählbar.'),
    ('WAKAME', 'Zarte grüne Braunalge mit mildem Meeresaroma, meist getrocknet erhältlich; nicht Kombu oder Nori.'),
    ('WALNUT', 'Walnusskerne mit herb-nussigem Geschmack und hohem Fettanteil; roh oder geröstet verwendbar.'),
    ('WATERCRESS', 'Brunnenkresse mit saftigen Stielen und deutlich pfeffrigem Geschmack; roh oder kurz gegart verwendbar.'),
    ('WATERMELON', 'Wassermelone mit sehr saftigem, süßem Fruchtfleisch; kernarme und kernhaltige Sorten sind umfasst.'),
    ('WATER_CHESTNUT', 'Knackige unterirdische Sprossknollen der Wasserkastanie, frisch oder in Dose; botanisch keine Nuss.'),
    ('WATER_SPINACH', 'Wasserspinat beziehungsweise Kangkong mit hohlen Stielen und zarten Blättern; nicht gewöhnlicher Spinat.'),
    ('WHEAT_FLOUR', 'Mehl aus Weizen; Ausmahlungsgrad und Proteinanteil bleiben offen, nicht Hartweizengrieß.'),
    ('WHEAT_NOODLES', 'Weizennudeln außerhalb der engeren italienischen Pasta-Familie; Dicke sowie Ei- und Alkalianteil bleiben wählbar.'),
    ('WHEAT_PASTA', 'Offene Familie italienisch geprägter Weizenpasta; Form, frisch oder getrocknet und Ei-Anteil bleiben offen.'),
    ('WHITE_ASPARAGUS', 'Unter Lichtabschluss gewachsener weißer Spargel mit mildem, leicht bitterem Aroma; vor dem Garen meist vollständig schälen.'),
    ('WHITE_BEANS', 'Offene Familie weißer Bohnen mit mildem Geschmack und cremiger Textur; Sorte und Größe bleiben wählbar.'),
    ('WHITE_CABBAGE', 'Fester Weißkohl mit knackigen, dicht geschichteten Blättern; roh, gegart oder fermentiert verwendbar.'),
    ('WHITE_CHAMPIGNON', 'Frische weiße Zuchtchampignons mit mildem Pilzaroma; nicht braune oder konservierte Champignons.'),
    ('WHITE_CHOCOLATE', 'Kakaobutterbasierte Süßware mit Milch und Zucker, aber ohne Kakaomasse; nicht bloße Fettglasur.'),
    ('WHITE_FISH', 'Offene Vorgabe für mageren bis mäßig fetten Fisch mit hellem, mildem Fleisch; Art und Zuschnitt bleiben wählbar.'),
    ('WHITE_PEPPER', 'Reife, von der Fruchthülle befreite Pfefferkörner mit erdig-direkter Schärfe; ganz oder gemahlen verwendbar.'),
    ('WHITE_SAUSAGE', 'Helle Brühwurst nach Weißwurst-Art aus Kalb- und/oder Schweinefleisch; regionale Würzung und Garzustand variieren.'),
    ('WHITE_SUGAR', 'Raffinierter weißer Zucker als kristallines, weitgehend neutrales Süßungsmittel; Körnung bleibt offen.'),
    ('WHITE_TEA', 'Sehr wenig verarbeiteter Tee aus jungen Knospen und Blättern mit zartem, floralem Profil.'),
    ('WHITE_VINEGAR', 'Klarer neutraler Branntweinessig mit direkter Säure; nicht automatisch hochkonzentrierte Essigessenz.'),
    ('WHITE_WINE', 'Weißwein als Kochzutat; Rebsorte, Körper und Trockenheitsgrad bleiben offen, kein aromatisiertes Weingetränk.'),
    ('WHITE_WINE_VINEGAR', 'Aus Weißwein vergorener Essig mit heller fruchtiger Säure; nicht Weißwein oder Reisessig.'),
    ('WHOLEGRAIN_MUSTARD', 'Senf mit sichtbaren ganzen oder grob gebrochenen Senfkörnern und körniger Textur; Schärfe bleibt offen.'),
    ('WILD_BOAR', 'Wildschweinfleisch mit kräftigem Wildaroma und meist dunklerem Fleisch als Hausschwein; Zuschnitt bleibt offen.'),
    ('WONTON_WRAPPERS', 'Dünne quadratische Weizenteigblätter, meist mit Ei, zum Füllen als Wontons; nicht Reispapier.'),
    ('WOOD_EAR', 'Mu-Err- beziehungsweise Judasohren mit elastisch-knackiger Textur und mildem Geschmack; meist getrocknet und eingeweicht.'),
    ('WORCESTERSHIRE_SAUCE', 'Dünne britische fermentierte Würzsauce mit Säure, Süße, Gewürzen und typischerweise Sardellen; intensiv und sparsam dosiert.'),
    ('XO_SAUCE', 'Hongkonger ölbasierte Würzpaste mit getrockneten Meeresfrüchten, Chili und Aromaten; kräftig umamireich, nicht vegetarisch.'),
    ('YAM', 'Stärkereiche Yamsknolle der Gattung Dioscorea; Sorte bleibt offen, nicht Süßkartoffel oder Ube.'),
    ('YEAST_EXTRACT', 'Konzentrierter Hefeextrakt als salzig-umamireiche Paste oder Würze; nicht aktive Hefe oder Hefeflocken.'),
    ('YELLOW_BELL_PEPPER', 'Reif gelbe Gemüsepaprika mit mildem, süß-fruchtigem Geschmack; nicht scharfe gelbe Chili.'),
    ('YELLOW_LENTILS', 'Gelbe geschälte Linsen mit kurzer Garzeit und cremig zerfallender Textur; konkrete Hülsenfruchtvariante kann regional variieren.'),
    ('YELLOW_SPLIT_PEAS', 'Getrocknete gelbe geschälte und halbierte Erbsen; für Suppen, Pürees und Eintöpfe geeignet.'),
    ('YOGURT', 'Durch Milchsäurekulturen gesäuerte Milch mit cremiger bis stichfester Textur; natur und ohne prägende Zusätze gemeint.'),
    ('YUZU', 'Ostasiatische Zitrusfrucht mit intensiv floral-herbem Aroma; meist Saft und Schale, frisch oder ungesüßt konserviert.'),
    ('ZAATAR', 'Levantinische Gewürzmischung typischerweise aus Za’atar-Kraut beziehungsweise Thymian, Sumach, Sesam und Salz; Rezepturen variieren.'),
    ('ZUCCHINI', 'Zucchini als mildes, saftiges Fruchtgemüse; grüne und gelbe sowie längliche und runde Sorten sind umfasst.');

CREATE TEMP TABLE _ingredient_curator_note_revision (
    code text PRIMARY KEY,
    curator_note text NOT NULL CHECK (btrim(curator_note) <> '')
) ON COMMIT DROP;

INSERT INTO _ingredient_curator_note_revision (code, curator_note)
VALUES
    ('ALIGUE', 'Philippinische Würzpaste aus ausgelassenem Krabbenfett mit intensiv meeresfruchtig-röstigem Aroma; meist sparsam zum Aromatisieren verwendet.'),
    ('AQUAVIT', 'Mit Kümmel, Dill oder anderen Gewürzen aromatisierte skandinavische Spirituose, die sich auch zum Würzen beim Kochen eignet; nicht auf eine Marke oder ein nationales Rezept beschränkt.'),
    ('BAGOONG_ALAMANG', 'Philippinische salzig-fermentierte Würzpaste aus kleinen Garnelen oder Krill; kräftig umamireich und nicht mit fischbasiertem Bagoong gleichzusetzen.'),
    ('BAGOONG_ISDA', 'Philippinische salzig-fermentierte Würzzutat auf Fischbasis; Fischart und flüssige oder pastöse Konsistenz können regional variieren.'),
    ('BAKED_GOODS', 'Offene Familie gebackener oder vergleichbar ausgebackener stärkehaltiger Produkte; süße und herzhafte Formen sind umfasst.'),
    ('BAMBOO_SHOOTS', 'Junge essbare Bambussprossen mit mildem Geschmack und knackigem Biss; in Deutschland meist vorgegart in Dose oder Glas erhältlich.'),
    ('BAY_LEAF', 'Getrocknetes oder frisches Lorbeerblatt mit herb-würzigem Aroma für Brühen, Saucen und Schmorgerichte; vor dem Servieren üblicherweise entfernen.'),
    ('BRUSSELS_WAFFLE', 'Große rechteckige belgische Waffel nach Brüsseler Art, außen knusprig und innen luftig. Gemeint ist die Waffel selbst, ohne vorausgesetzte Beläge. Nicht mit der kompakteren Lütticher Zuckerwaffel gleichsetzen.'),
    ('CHAMPIGNON', 'Frischer Zuchtchampignon ohne Festlegung auf die weiße oder braune Form; konservierte Champignons und andere Speisepilze sind nicht gemeint.'),
    ('CHILI', 'Frische Chili als Fruchtgemüse; trockene, pulverisierte und eingelegte Formen sind damit nicht gemeint.'),
    ('CHILI_FLAKES', 'Getrocknete Chiliflocken mit variabler Sorte, Schärfe und regionaler Würzung; nicht fein gemahlenes Chilipulver.'),
    ('CHOCOLATE', 'Offene Schokoladenfamilie für dunkle, Milch- und weiße Schokolade; Kakaopulver ist nicht umfasst.'),
    ('COGNAC', 'Geschützter französischer Weinbrand aus Cognac mit charakteristisch gereiftem Aroma; nicht beliebiger Brandy oder Weinbrand.'),
    ('COCONUT_PRODUCTS', 'Offene Familie für Kokosfrucht, Kokoswasser, daraus gewonnene Emulsionen, Fett und weitere verarbeitete Kokosprodukte.'),
    ('CONFECTIONERY', 'Offene Familie verzehrfertiger Süßwaren wie Bonbons, Lakritz oder Marzipan; reine Süßungsmittel und Backgrundstoffe sind nicht automatisch umfasst.'),
    ('DAIRY_PRODUCTS', 'Offene Familie von Milchprodukten wie Milch, Rahm, fermentierten Erzeugnissen, Butter und Käse; Eier und pflanzliche Alternativen sind nicht gemeint.'),
    ('DRIED_CHILI', 'Ganze oder grob zerteilte getrocknete Chili mit konzentriertem Aroma; Pulver und feine Flocken sind damit nicht gemeint.'),
    ('FROG_LEGS', 'Essbare Froschschenkel mit zartem, mildem Fleisch; frisch oder tiefgekühlt als ganze Schenkelpaare beziehungsweise Teilstücke verwendbar.'),
    ('GARLIC_POWDER', 'Getrockneter gemahlener oder granulierter Knoblauch mit konzentriertem Aroma; nicht frischer Knoblauch oder Knoblauchsalz.'),
    ('GOCHUJANG', 'Koreanische fermentierte rote Chilipaste mit dicklicher Konsistenz sowie süß-scharfem, salzigem und umamireichem Profil.'),
    ('GREEN_SPLIT_PEAS', 'Getrocknete grüne geschälte und halbierte Erbsen mit mild-erdigem Geschmack; nicht gelbe Schälerbsen oder frische grüne Erbsen.'),
    ('HAM', 'Offene Schinkenfamilie aus gepökeltem Fleisch; gekochte, geräucherte und luftgetrocknete Ausprägungen sind umfasst.'),
    ('LAMBIC', 'Traditioneller belgischer Bierstil aus spontan vergorener Würze. Gemeint ist der Grundstil; Gueuze, Kriek und andere Frucht- oder Blendvarianten sind nicht automatisch eingeschlossen.'),
    ('LINGONBERRY_PRESERVES', 'Gesüßte Preiselbeerzubereitung wie Konfitüre, Kompott oder gerührte Preiselbeeren; nicht die ungesüßte frische Beere.'),
    ('LIQUORICE', 'Lakritzware mit süßen und salzigen Ausprägungen, auch als Kochzutat verwendbar; nicht Süßholzwurzel oder reiner Lakritzextrakt.'),
    ('LOBSTER', 'Hummer mit festem, süßlichem Fleisch aus Schwanz und Scheren; ganz, ausgelöst, frisch oder tiefgekühlt verwendbar.'),
    ('MAGGI_SEASONING', 'Dunkle flüssige Würzsauce nach Maggi-Art mit salzig-würzigem Umami; nicht Liebstöckel, Sojasauce oder Brühwürfel.'),
    ('MISO', 'Japanische fermentierte Würzpaste auf Sojabohnenbasis, häufig mit Reis oder Gerste; Farbe, Salzgehalt und Reifegrad bleiben offen.'),
    ('MYCOPROTEIN', 'Pilzproteinbasierte Fleischalternative; Marke, Produktform und Würzung können variieren.'),
    ('NORWEGIAN_WAFFLE', 'Dünne, weiche Waffel nach norwegischer Art, typischerweise herzförmig, leicht süß und mit Kardamom aromatisiert. Gemeint ist die Waffel selbst, ohne vorausgesetzte Beläge.'),
    ('OKRA', 'Junge Okraschoten mit grasig-mildem Geschmack; ihre Samen und Schleimstoffe entwickeln beim Garen eine charakteristische Bindung.'),
    ('ONION_POWDER', 'Getrocknete gemahlene oder granulierte Zwiebel mit konzentriertem Aroma; nicht frische Zwiebel oder Zwiebelsalz.'),
    ('PAPRIKA_POWDER', 'Paprikapulver als Gewürzfamilie mit süßen, scharfen und geräucherten Varianten; nicht frische Paprika.'),
    ('PICKLED_CHILI', 'In Essig- oder Gewürzlake eingelegte ganze oder geschnittene Chili; Sorte und Schärfe bleiben offen, trockene Formen sind nicht gemeint.'),
    ('PICKLED_MUSHROOMS', 'In Essiglake eingelegte Speisepilze; eine Fermentation wird nicht vorausgesetzt.'),
    ('PIMENT_D_ESPELETTE', 'Getrocknetes, fein gemahlenes Piment-d’Espelette-Gewürz nach französisch-baskischer Art; nicht generisches Chilipulver oder die frische ganze Schote.'),
    ('PLANT_DRINKS', 'Offene Familie flüssiger pflanzlicher Milchalternativen etwa aus Soja, Hafer oder Nüssen; Rohstoff und Süßung bleiben wählbar.'),
    ('READY_CURRY_PASTE', 'Offene Familie verzehrfertiger Currypasten mit bereits kombinierter Gewürz- und Aromatenbasis; Küche, Farbe und Schärfe bleiben offen.'),
    ('READY_SAUCES_AND_PASTES', 'Offene Familie gebrauchsfertiger Saucen, Würzen und Pasten mit bereits zusammengesetztem Geschmacksprofil.'),
    ('ROOKWORST', 'Niederländische geräucherte Koch- oder Brühwurst; die Fleischzusammensetzung kann variieren und muss nicht ausschließlich aus Schweinefleisch bestehen.'),
    ('SAFFRON', 'Getrocknete Safranfäden beziehungsweise Narben mit intensiv floral-honigartigem Aroma und starker gelber Färbekraft; sparsam dosieren.'),
    ('SAMBAL', 'Chilipaste oder Chilisauce mit je nach Variante unterschiedlicher Schärfe, Konsistenz und Aromatik; nicht auf Sambal Oelek beschränkt.'),
    ('SEITAN', 'Festes proteinreiches Lebensmittel aus ausgewaschenem oder isoliertem Weizengluten; natur oder neutral vorgewürzt verwendbar.'),
    ('SOBA', 'Japanische dünne Nudeln mit Buchweizen als typischem Teigbestandteil; Buchweizenanteil und Beimischung von Weizen können variieren.'),
    ('STROOPWAFEL', 'Zwei dünne Waffeln mit süßer Sirup- oder Karamellfüllung; gemeint ist die fertige Süßware, nicht eine allgemeine Waffel oder der Sirup allein.'),
    ('TEMPEH', 'Fester fermentierter Kuchen aus ganzen Sojabohnen mit nussigem Aroma und gutem Biss; nicht Tofu oder texturiertes Sojaprotein.'),
    ('TRUFFLE', 'Essbare Trüffel mit intensiv erdigem Aroma; frisch oder als hochwertiges Produkt mit erkennbarem Trüffelanteil verwendbar.'),
    ('TWAROG', 'Polnischer frischer Sauermilch- oder Bruchkäse mit krümeligem bis cremigem Gefüge; Quark ist als Ersatz ähnlich, aber nicht identisch. Nicht mit körnigem Hüttenkäse gleichsetzen.'),
    ('UBE', 'Violette Yamswurzel mit mild-süßlichem, nussigem Aroma; frisch, tiefgekühlt oder als ungesüßtes Püree, nicht violette Süßkartoffel.'),
    ('WAFFLES', 'Offene Waffelfamilie für süße und herzhafte Waffelprodukte. Bekannte Varianten sind Stroopwafel, Brüsseler Waffel und Lütticher Waffel; Belag oder Füllung werden nicht vorausgesetzt.');

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM _ingredient_curator_note_backfill source
        LEFT JOIN ingredient_concept concept ON concept.code = source.code
        WHERE concept.id IS NULL
    ) THEN
        RAISE EXCEPTION 'Curator-note backfill contains an unknown ingredient concept code';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM ingredient_concept concept
        WHERE (concept.curator_note IS NULL OR btrim(concept.curator_note) = '')
          AND NOT EXISTS (
              SELECT 1
              FROM _ingredient_curator_note_backfill source
              WHERE source.code = concept.code
          )
    ) THEN
        RAISE EXCEPTION 'Ingredient catalog contains an unreviewed concept without a curator note';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM _ingredient_curator_note_revision source
        LEFT JOIN ingredient_concept concept ON concept.code = source.code
        WHERE concept.id IS NULL
    ) THEN
        RAISE EXCEPTION 'Curator-note revision contains an unknown ingredient concept code';
    END IF;
END;
$$;

UPDATE ingredient_concept concept
SET curator_note = source.curator_note
FROM _ingredient_curator_note_backfill source
WHERE concept.code = source.code
  AND (concept.curator_note IS NULL OR btrim(concept.curator_note) = '');

UPDATE ingredient_concept concept
SET curator_note = source.curator_note
FROM _ingredient_curator_note_revision source
WHERE concept.code = source.code;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM ingredient_concept
        WHERE curator_note IS NULL OR btrim(curator_note) = ''
    ) THEN
        RAISE EXCEPTION 'Ingredient catalog still contains a blank curator note after backfill';
    END IF;
END;
$$;

ALTER TABLE ingredient_concept
    ALTER COLUMN curator_note SET NOT NULL;

ALTER TABLE ingredient_concept
    ADD CONSTRAINT ck_ingredient_concept_curator_note_not_blank
        CHECK (btrim(curator_note) <> '');
