--liquibase formatted sql

--changeset venomenon328:043-ingredient-name-alias-curation splitStatements:false
-- Issue #264, approved review INGREDIENT_ALIAS_REVIEW_R3_20260916 at
-- 59d769c32fee142e9dd0e61fe387289a0e6e5281. General approval:
-- issue comment 5694003700; BEEF_SUET exception: issue comment 5693948899.
-- Liquibase executes the complete guarded migration transactionally.

-- Serialize the same cross-concept name check/write boundary as CatalogNameLock.
SELECT pg_advisory_xact_lock(6241884431947263);

CREATE TEMP TABLE ingredient_name_alias_r3_review (
    code                  text PRIMARY KEY,
    previous_display_name text NOT NULL,
    previous_aliases      text[] NOT NULL,
    target_display_name   text NOT NULL,
    target_aliases        text[] NOT NULL
) ON COMMIT DROP;

-- BEGIN APPROVED R3 VALUES
INSERT INTO ingredient_name_alias_r3_review VALUES
    ('ADZUKI_BEANS', 'Adzukibohnen', ARRAY[]::text[], 'Adzukibohnen', ARRAY['Azukibohnen']::text[]),
    ('AGAVE_SYRUP', 'Agavendicksaft', ARRAY[]::text[], 'Agavendicksaft', ARRAY['Agavensirup']::text[]),
    ('AIOLI', 'Aioli', ARRAY[]::text[], 'Aioli', ARRAY['Allioli']::text[]),
    ('AJVAR', 'Ajvar', ARRAY[]::text[], 'Ajvar', ARRAY[]::text[]),
    ('AJWAIN', 'Ajwain', ARRAY[]::text[], 'Ajowan', ARRAY['Ajwain', 'Königskümmel']::text[]),
    ('ALE', 'Ale', ARRAY[]::text[], 'Ale', ARRAY[]::text[]),
    ('ALFALFA_SPROUTS', 'Alfalfasprossen', ARRAY[]::text[], 'Alfalfasprossen', ARRAY['Luzernensprossen']::text[]),
    ('ALIGUE', 'Aligue', ARRAY[]::text[], 'Aligue', ARRAY[]::text[]),
    ('ALLIUM_VEGETABLES', 'Lauch- und Zwiebelgemüse', ARRAY[]::text[], 'Lauch- und Zwiebelgemüse', ARRAY[]::text[]),
    ('ALLSPICE', 'Piment', ARRAY[]::text[], 'Piment', ARRAY['Nelkenpfeffer']::text[]),
    ('ALMOND', 'Mandeln', ARRAY[]::text[], 'Mandeln', ARRAY[]::text[]),
    ('ALMOND_BUTTER', 'Mandelmus', ARRAY[]::text[], 'Mandelmus', ARRAY[]::text[]),
    ('ALMOND_DRINK', 'Mandeldrink', ARRAY[]::text[], 'Mandelmilch', ARRAY['Mandeldrink']::text[]),
    ('AMARANTH', 'Amaranth', ARRAY[]::text[], 'Amaranth', ARRAY['Amarant']::text[]),
    ('ANCHOVIES', 'Sardellen', ARRAY[]::text[], 'Sardellen', ARRAY[]::text[]),
    ('ANCHO_CHILI', 'Ancho-Chili', ARRAY[]::text[], 'Ancho-Chili', ARRAY['Ancho']::text[]),
    ('ANNATTO', 'Annatto', ARRAY[]::text[], 'Annatto', ARRAY[]::text[]),
    ('APPLE', 'Apfel', ARRAY[]::text[], 'Apfel', ARRAY[]::text[]),
    ('APPLE_CIDER_VINEGAR', 'Apfelessig', ARRAY[]::text[], 'Apfelessig', ARRAY['Apfelweinessig']::text[]),
    ('APRICOT', 'Aprikose', ARRAY[]::text[], 'Aprikose', ARRAY['Marille']::text[]),
    ('APRICOT_PRESERVES', 'Aprikosenkonfitüre', ARRAY[]::text[], 'Aprikosenkonfitüre', ARRAY['Aprikosenmarmelade']::text[]),
    ('AQUAVIT', 'Aquavit', ARRAY[]::text[], 'Aquavit', ARRAY['Akvavit']::text[]),
    ('ARCTIC_CHAR', 'Arktischer Saibling', ARRAY[]::text[], 'Arktischer Saibling', ARRAY['Wandersaibling']::text[]),
    ('ARTICHOKE', 'Artischocke', ARRAY[]::text[], 'Artischocke', ARRAY[]::text[]),
    ('ARUGULA', 'Rucola', ARRAY[]::text[], 'Rucola', ARRAY['Rauke']::text[]),
    ('ASPARAGUS', 'Spargel', ARRAY[]::text[], 'Spargel', ARRAY[]::text[]),
    ('AVOCADO', 'Avocado', ARRAY[]::text[], 'Avocado', ARRAY[]::text[]),
    ('BACON', 'Bacon', ARRAY[]::text[], 'Bacon', ARRAY['Frühstücksspeck']::text[]),
    ('BAGOONG', 'Bagoong', ARRAY[]::text[], 'Bagoong', ARRAY[]::text[]),
    ('BAGOONG_ALAMANG', 'Bagoong alamang', ARRAY[]::text[], 'Bagoong alamang', ARRAY[]::text[]),
    ('BAGOONG_ISDA', 'Bagoong isda', ARRAY[]::text[], 'Bagoong isda', ARRAY[]::text[]),
    ('BAGUETTE', 'Baguette', ARRAY[]::text[], 'Baguette', ARRAY[]::text[]),
    ('BAKED_BEANS', 'Baked Beans', ARRAY[]::text[], 'Baked Beans', ARRAY[]::text[]),
    ('BAKED_GOODS', 'Backware', ARRAY[]::text[], 'Backware', ARRAY[]::text[]),
    ('BALSAMIC_VINEGAR', 'Balsamico', ARRAY[]::text[], 'Balsamico', ARRAY['Aceto Balsamico']::text[]),
    ('BAMBOO_SHOOTS', 'Bambussprossen', ARRAY[]::text[], 'Bambussprossen', ARRAY[]::text[]),
    ('BANANA', 'Banane', ARRAY[]::text[], 'Banane', ARRAY[]::text[]),
    ('BANANA_BLOSSOM', 'Bananenblüte', ARRAY[]::text[], 'Bananenblüte', ARRAY['Bananenherz']::text[]),
    ('BANANA_KETCHUP', 'Bananenketchup', ARRAY[]::text[], 'Bananenketchup', ARRAY[]::text[]),
    ('BANANA_LEAVES', 'Bananenblätter', ARRAY[]::text[], 'Bananenblätter', ARRAY[]::text[]),
    ('BARBECUE_SAUCE', 'Barbecuesauce', ARRAY[]::text[], 'Barbecuesauce', ARRAY['BBQ-Sauce']::text[]),
    ('BARLEY', 'Gerste', ARRAY[]::text[], 'Gerste', ARRAY[]::text[]),
    ('BASIL', 'Basilikum', ARRAY[]::text[], 'Basilikum', ARRAY[]::text[]),
    ('BASMATI_RICE', 'Basmatireis', ARRAY[]::text[], 'Basmatireis', ARRAY[]::text[]),
    ('BAY_LEAF', 'Lorbeerblatt', ARRAY[]::text[], 'Lorbeerblatt', ARRAY[]::text[]),
    ('BEANS', 'Bohnen', ARRAY[]::text[], 'Bohnen', ARRAY[]::text[]),
    ('BEAN_SPROUTS', 'Mungbohnensprossen', ARRAY[]::text[], 'Mungbohnensprossen', ARRAY['Mungobohnenkeimlinge', 'Mungobohnensprossen']::text[]),
    ('BEEF', 'Rindfleisch', ARRAY[]::text[], 'Rindfleisch', ARRAY[]::text[]),
    ('BEEF_BRISKET', 'Rinderbrust', ARRAY[]::text[], 'Rinderbrust', ARRAY[]::text[]),
    ('BEEF_CHEEK', 'Rinderbäckchen', ARRAY[]::text[], 'Rinderbäckchen', ARRAY['Rinderbacken']::text[]),
    ('BEEF_GOULASH', 'Rindergulasch', ARRAY[]::text[], 'Rindergulasch', ARRAY[]::text[]),
    ('BEEF_HEART', 'Rinderherz', ARRAY[]::text[], 'Rinderherz', ARRAY[]::text[]),
    ('BEEF_LIVER', 'Rinderleber', ARRAY[]::text[], 'Rinderleber', ARRAY[]::text[]),
    ('BEEF_MINCE', 'Rinderhack', ARRAY[]::text[], 'Rinderhack', ARRAY['Rinderhackfleisch']::text[]),
    ('BEEF_ROAST', 'Rinderbraten', ARRAY[]::text[], 'Rinderbraten', ARRAY[]::text[]),
    ('BEEF_ROULADE', 'Rinderroulade', ARRAY[]::text[], 'Rinderroulade', ARRAY[]::text[]),
    ('BEEF_RUMP', 'Rinderhüfte', ARRAY[]::text[], 'Rinderhüfte', ARRAY[]::text[]),
    ('BEEF_SHIN', 'Rinderbeinscheibe', ARRAY[]::text[], 'Rinderbeinscheibe', ARRAY[]::text[]),
    ('BEEF_SHORT_RIBS', 'Rinderrippen', ARRAY[]::text[], 'Querrippe', ARRAY['Short Ribs']::text[]),
    ('BEEF_STEAK', 'Rindersteak', ARRAY[]::text[], 'Rindersteak', ARRAY[]::text[]),
    ('BEEF_STOCK', 'Rinderfond', ARRAY[]::text[], 'Rinderfond', ARRAY[]::text[]),
    ('BEEF_SUET', 'Rindernierenfett (Suet)', ARRAY[]::text[], 'Rindernierenfett', ARRAY['Beef Suet']::text[]),
    ('BEEF_TAFELSPITZ', 'Tafelspitz', ARRAY[]::text[], 'Tafelspitz', ARRAY[]::text[]),
    ('BEEF_TENDERLOIN', 'Rinderfilet', ARRAY[]::text[], 'Rinderfilet', ARRAY[]::text[]),
    ('BEEF_TONGUE', 'Rinderzunge', ARRAY[]::text[], 'Rinderzunge', ARRAY[]::text[]),
    ('BEER', 'Bier', ARRAY[]::text[], 'Bier', ARRAY[]::text[]),
    ('BEETROOT', 'Rote Bete', ARRAY[]::text[], 'Rote Bete', ARRAY['Rote Beete', 'Rote Rübe']::text[]),
    ('BELACAN', 'Belacan', ARRAY[]::text[], 'Belacan', ARRAY[]::text[]),
    ('BELL_PEPPER', 'Paprika', ARRAY[]::text[], 'Paprika', ARRAY[]::text[]),
    ('BELUGA_LENTILS', 'Belugalinsen', ARRAY[]::text[], 'Belugalinsen', ARRAY[]::text[]),
    ('BERBERE', 'Berbere', ARRAY[]::text[], 'Berbere', ARRAY[]::text[]),
    ('BERG_CHEESE', 'Bergkäse', ARRAY[]::text[], 'Bergkäse', ARRAY[]::text[]),
    ('BERRIES', 'Beeren', ARRAY[]::text[], 'Beeren', ARRAY[]::text[]),
    ('BIRDS_EYE_CHILI', 'Bird’s-Eye-Chili', ARRAY[]::text[], 'Bird’s-Eye-Chili', ARRAY[]::text[]),
    ('BITTER_MELON', 'Bittermelone', ARRAY[]::text[], 'Bittermelone', ARRAY['Bittergurke']::text[]),
    ('BIVALVES', 'Muscheln', ARRAY[]::text[], 'Muscheln', ARRAY[]::text[]),
    ('BLACKBERRY', 'Brombeere', ARRAY[]::text[], 'Brombeere', ARRAY[]::text[]),
    ('BLACK_BEANS', 'schwarze Bohnen', ARRAY[]::text[], 'schwarze Bohnen', ARRAY[]::text[]),
    ('BLACK_CARDAMOM', 'schwarzer Kardamom oder Thảo quả', ARRAY[]::text[], 'schwarzer Kardamom oder Thảo quả', ARRAY[]::text[]),
    ('BLACK_CURRANT', 'schwarze Johannisbeere', ARRAY[]::text[], 'schwarze Johannisbeere', ARRAY[]::text[]),
    ('BLACK_EYED_PEAS', 'Augenbohnen', ARRAY[]::text[], 'Augenbohnen', ARRAY['Schwarzaugenbohnen']::text[]),
    ('BLACK_GARLIC', 'schwarzer Knoblauch', ARRAY[]::text[], 'schwarzer Knoblauch', ARRAY[]::text[]),
    ('BLACK_PEPPER', 'schwarzer Pfeffer', ARRAY[]::text[], 'schwarzer Pfeffer', ARRAY[]::text[]),
    ('BLACK_PUDDING', 'Black Pudding', ARRAY[]::text[], 'Black Pudding', ARRAY[]::text[]),
    ('BLACK_TEA', 'schwarzer Tee', ARRAY[]::text[], 'schwarzer Tee', ARRAY[]::text[]),
    ('BLACK_VINEGAR', 'chinesischer schwarzer Essig', ARRAY[]::text[], 'chinesischer schwarzer Essig', ARRAY[]::text[]),
    ('BLOOD_ORANGE', 'Blutorange', ARRAY[]::text[], 'Blutorange', ARRAY[]::text[]),
    ('BLOOD_SAUSAGE', 'Blutwurst', ARRAY[]::text[], 'Blutwurst', ARRAY[]::text[]),
    ('BLUEBERRY', 'Heidelbeere', ARRAY[]::text[], 'Heidelbeere', ARRAY['Blaubeere']::text[]),
    ('BLUE_CHEESE', 'Blauschimmelkäse', ARRAY[]::text[], 'Blauschimmelkäse', ARRAY[]::text[]),
    ('BLUE_STILTON', 'Blue Stilton', ARRAY[]::text[], 'Blue Stilton', ARRAY[]::text[]),
    ('BOMBA_RICE', 'Bomba-Reis', ARRAY[]::text[], 'Bomba-Reis', ARRAY[]::text[]),
    ('BONE_MARROW', 'Knochenmark', ARRAY[]::text[], 'Knochenmark', ARRAY[]::text[]),
    ('BONITO_FLAKES', 'Bonitoflocken', ARRAY[]::text[], 'Bonitoflocken', ARRAY['Katsuobushi']::text[]),
    ('BRANDY', 'Brandy oder Weinbrand', ARRAY[]::text[], 'Weinbrand', ARRAY['Brandy']::text[]),
    ('BRATWURST', 'Bratwurst', ARRAY[]::text[], 'Bratwurst', ARRAY[]::text[]),
    ('BRAZIL_NUT', 'Paranüsse', ARRAY[]::text[], 'Paranüsse', ARRAY[]::text[]),
    ('BREAD', 'Brot oder Fladenbrot', ARRAY[]::text[], 'Brot oder Fladenbrot', ARRAY[]::text[]),
    ('BREADCRUMBS', 'Semmelbrösel', ARRAY[]::text[], 'Semmelbrösel', ARRAY['Paniermehl', 'Semmelmehl']::text[]),
    ('BREAD_DUMPLING', 'Semmelknödel', ARRAY[]::text[], 'Semmelknödel', ARRAY['Semmelkloß']::text[]),
    ('BRIE', 'Brie', ARRAY[]::text[], 'Brie', ARRAY[]::text[]),
    ('BROAD_BEANS', 'Dicke Bohnen', ARRAY[]::text[], 'Dicke Bohnen', ARRAY['Ackerbohnen', 'Puffbohnen', 'Saubohnen']::text[]),
    ('BROCCOLI', 'Brokkoli', ARRAY[]::text[], 'Brokkoli', ARRAY[]::text[]),
    ('BROKEN_RICE', 'Bruchreis', ARRAY[]::text[], 'Bruchreis', ARRAY[]::text[]),
    ('BROWN_CHAMPIGNON', 'braune Champignons', ARRAY[]::text[], 'braune Champignons', ARRAY[]::text[]),
    ('BROWN_RICE', 'Vollkornreis', ARRAY[]::text[], 'Vollkornreis', ARRAY['brauner Reis', 'Naturreis']::text[]),
    ('BROWN_SAUCE', 'Brown Sauce', ARRAY[]::text[], 'Brown Sauce', ARRAY[]::text[]),
    ('BROWN_SUGAR', 'brauner Zucker', ARRAY[]::text[], 'brauner Zucker', ARRAY[]::text[]),
    ('BRUNOST', 'Brunost', ARRAY[]::text[], 'Brunost', ARRAY['Braunkäse']::text[]),
    ('BRUSSELS_SPROUTS', 'Rosenkohl', ARRAY[]::text[], 'Rosenkohl', ARRAY[]::text[]),
    ('BRUSSELS_WAFFLE', 'Brüsseler Waffel', ARRAY[]::text[], 'Brüsseler Waffel', ARRAY[]::text[]),
    ('BUCKWHEAT', 'Buchweizen', ARRAY[]::text[], 'Buchweizen', ARRAY[]::text[]),
    ('BUCKWHEAT_FLOUR', 'Buchweizenmehl', ARRAY[]::text[], 'Buchweizenmehl', ARRAY[]::text[]),
    ('BULGUR', 'Bulgur', ARRAY[]::text[], 'Bulgur', ARRAY[]::text[]),
    ('BUTTER', 'Butter', ARRAY[]::text[], 'Butter', ARRAY[]::text[]),
    ('BUTTERMILK', 'Buttermilch', ARRAY[]::text[], 'Buttermilch', ARRAY[]::text[]),
    ('BUTTERNUT_SQUASH', 'Butternut-Kürbis', ARRAY[]::text[], 'Butternut-Kürbis', ARRAY['Butternusskürbis']::text[]),
    ('BUTTER_BEANS', 'Limabohnen', ARRAY[]::text[], 'Limabohnen', ARRAY['Butterbohnen']::text[]),
    ('CABBAGE_VEGETABLES', 'Kohlgemüse', ARRAY[]::text[], 'Kohlgemüse', ARRAY[]::text[]),
    ('CALAMANSI', 'Calamansi', ARRAY[]::text[], 'Calamansi', ARRAY['Kalamansi']::text[]),
    ('CALVADOS', 'Calvados', ARRAY[]::text[], 'Calvados', ARRAY[]::text[]),
    ('CAMEMBERT', 'Camembert', ARRAY[]::text[], 'Camembert', ARRAY[]::text[]),
    ('CANNED_CHAMPIGNONS', 'Dosenchampignons', ARRAY[]::text[], 'Dosenchampignons', ARRAY[]::text[]),
    ('CANNED_SARDINES', 'Sardinen aus der Dose', ARRAY[]::text[], 'Sardinen aus der Dose', ARRAY[]::text[]),
    ('CANNED_TOMATOES', 'Dosentomaten', ARRAY[]::text[], 'Dosentomaten', ARRAY[]::text[]),
    ('CANNED_TUNA', 'Thunfisch aus der Dose', ARRAY[]::text[], 'Thunfisch aus der Dose', ARRAY[]::text[]),
    ('CANNELLINI_BEANS', 'Cannellini-Bohnen', ARRAY[]::text[], 'Cannellini-Bohnen', ARRAY[]::text[]),
    ('CANTALOUPE', 'Cantaloupe-Melone', ARRAY[]::text[], 'Cantaloupe-Melone', ARRAY[]::text[]),
    ('CAPERS', 'Kapern', ARRAY[]::text[], 'Kapern', ARRAY[]::text[]),
    ('CARAWAY', 'Kümmel', ARRAY[]::text[], 'Kümmel', ARRAY[]::text[]),
    ('CARDAMOM', 'Kardamom', ARRAY[]::text[], 'Kardamom', ARRAY[]::text[]),
    ('CARP', 'Karpfen', ARRAY[]::text[], 'Karpfen', ARRAY[]::text[]),
    ('CARROT', 'Karotte', ARRAY[]::text[], 'Karotte', ARRAY['Mohrrübe', 'Möhre']::text[]),
    ('CASHEW', 'Cashewkerne', ARRAY[]::text[], 'Cashewkerne', ARRAY[]::text[]),
    ('CASHEW_BUTTER', 'Cashewmus', ARRAY[]::text[], 'Cashewmus', ARRAY[]::text[]),
    ('CASSAVA', 'Maniok', ARRAY[]::text[], 'Maniok', ARRAY['Cassava', 'Yuca']::text[]),
    ('CATFISH', 'Wels', ARRAY[]::text[], 'Wels', ARRAY[]::text[]),
    ('CAULIFLOWER', 'Blumenkohl', ARRAY[]::text[], 'Blumenkohl', ARRAY[]::text[]),
    ('CAVA', 'Cava', ARRAY[]::text[], 'Cava', ARRAY[]::text[]),
    ('CAYENNE_PEPPER', 'Cayennepfeffer', ARRAY[]::text[], 'Cayennepfeffer', ARRAY[]::text[]),
    ('CELERIAC', 'Knollensellerie', ARRAY[]::text[], 'Knollensellerie', ARRAY[]::text[]),
    ('CELERY_STALK', 'Staudensellerie', ARRAY[]::text[], 'Staudensellerie', ARRAY['Stangensellerie']::text[]),
    ('CHAMPIGNON', 'frische Champignons', ARRAY[]::text[], 'frische Champignons', ARRAY[]::text[]),
    ('CHAMPIGNONS', 'Champignons', ARRAY[]::text[], 'Champignons', ARRAY[]::text[]),
    ('CHANTERELLE', 'Pfifferlinge', ARRAY[]::text[], 'Pfifferlinge', ARRAY['Eierschwammerl']::text[]),
    ('CHARD', 'Mangold', ARRAY[]::text[], 'Mangold', ARRAY[]::text[]),
    ('CHEDDAR', 'Cheddar', ARRAY[]::text[], 'Cheddar', ARRAY[]::text[]),
    ('CHEESE', 'Käse', ARRAY[]::text[], 'Käse', ARRAY[]::text[]),
    ('CHERRY', 'Kirsche', ARRAY[]::text[], 'Kirsche', ARRAY[]::text[]),
    ('CHERRY_TOMATO', 'Kirschtomaten', ARRAY[]::text[], 'Kirschtomaten', ARRAY['Cherrytomaten']::text[]),
    ('CHERVIL', 'Kerbel', ARRAY[]::text[], 'Kerbel', ARRAY[]::text[]),
    ('CHESTNUT', 'Esskastanien', ARRAY[]::text[], 'Esskastanien', ARRAY[]::text[]),
    ('CHIA_SEEDS', 'Chiasamen', ARRAY[]::text[], 'Chiasamen', ARRAY[]::text[]),
    ('CHICKEN', 'Hähnchen', ARRAY[]::text[], 'Hähnchen', ARRAY[]::text[]),
    ('CHICKEN_BREAST', 'Hähnchenbrust', ARRAY[]::text[], 'Hähnchenbrust', ARRAY[]::text[]),
    ('CHICKEN_DRUMSTICKS', 'Hähnchenunterkeulen', ARRAY[]::text[], 'Hähnchenunterkeulen', ARRAY[]::text[]),
    ('CHICKEN_FEET', 'Hühnerfüße', ARRAY[]::text[], 'Hühnerfüße', ARRAY[]::text[]),
    ('CHICKEN_LIVER', 'Hähnchenleber', ARRAY[]::text[], 'Hähnchenleber', ARRAY[]::text[]),
    ('CHICKEN_STOCK', 'Hühnerbrühe', ARRAY[]::text[], 'Hühnerbrühe', ARRAY[]::text[]),
    ('CHICKEN_THIGH', 'Hähnchenschenkel', ARRAY[]::text[], 'Hähnchenschenkel', ARRAY['Hähnchenkeule']::text[]),
    ('CHICKEN_WINGS', 'Hähnchenflügel', ARRAY[]::text[], 'Hähnchenflügel', ARRAY['Chicken Wings']::text[]),
    ('CHICKPEAS', 'Kichererbsen', ARRAY[]::text[], 'Kichererbsen', ARRAY[]::text[]),
    ('CHICKPEA_FLOUR', 'Kichererbsenmehl', ARRAY[]::text[], 'Kichererbsenmehl', ARRAY[]::text[]),
    ('CHICORY', 'Chicorée', ARRAY[]::text[], 'Chicorée', ARRAY['Salatzichorie']::text[]),
    ('CHILI', 'frische Chili', ARRAY[]::text[], 'frische Chili', ARRAY[]::text[]),
    ('CHILI_CONDIMENTS', 'Chilisauce oder -paste', ARRAY[]::text[], 'Chilisauce oder -paste', ARRAY[]::text[]),
    ('CHILI_CRISP', 'Chili-Crisp', ARRAY[]::text[], 'Chili-Crisp', ARRAY['Chili-Crunch']::text[]),
    ('CHILI_FLAKES', 'Chiliflocken', ARRAY[]::text[], 'Chiliflocken', ARRAY[]::text[]),
    ('CHILI_OIL', 'Chiliöl', ARRAY[]::text[], 'Chiliöl', ARRAY[]::text[]),
    ('CHILI_POWDER', 'Chilipulver', ARRAY[]::text[], 'Chilipulver', ARRAY[]::text[]),
    ('CHIPOTLE', 'Chipotle', ARRAY[]::text[], 'Chipotle', ARRAY[]::text[]),
    ('CHIVES', 'Schnittlauch', ARRAY[]::text[], 'Schnittlauch', ARRAY[]::text[]),
    ('CHOCOLATE', 'Schokolade', ARRAY[]::text[], 'Schokolade', ARRAY[]::text[]),
    ('CHOCOLATE_HAGELSLAG', 'Schoko-Hagelslag', ARRAY[]::text[], 'Schoko-Hagelslag', ARRAY[]::text[]),
    ('CHORIZO', 'Chorizo', ARRAY[]::text[], 'Chorizo', ARRAY[]::text[]),
    ('CIDER', 'Cider', ARRAY[]::text[], 'Cider', ARRAY[]::text[]),
    ('CILANTRO', 'Koriandergrün', ARRAY[]::text[], 'Koriandergrün', ARRAY[]::text[]),
    ('CINNAMON', 'Zimt', ARRAY[]::text[], 'Zimt', ARRAY[]::text[]),
    ('CITRUS_FRUIT', 'Zitrusfrucht', ARRAY[]::text[], 'Zitrusfrucht', ARRAY[]::text[]),
    ('CLAMS', 'Venusmuscheln', ARRAY[]::text[], 'Venusmuscheln', ARRAY['Clam']::text[]),
    ('CLOTTED_CREAM', 'Clotted Cream', ARRAY[]::text[], 'Clotted Cream', ARRAY[]::text[]),
    ('CLOUDBERRY', 'Moltebeere', ARRAY[]::text[], 'Moltebeere', ARRAY[]::text[]),
    ('CLOUDBERRY_PRESERVES', 'Moltebeerkonfitüre/-kompott', ARRAY[]::text[], 'Moltebeerkonfitüre/-kompott', ARRAY[]::text[]),
    ('CLOVES', 'Gewürznelken', ARRAY[]::text[], 'Gewürznelken', ARRAY[]::text[]),
    ('COCKLES', 'Herzmuscheln', ARRAY[]::text[], 'Herzmuscheln', ARRAY[]::text[]),
    ('COCOA_POWDER', 'Kakaopulver', ARRAY[]::text[], 'Kakaopulver', ARRAY[]::text[]),
    ('COCOA_PRODUCTS', 'Kakao oder Schokolade', ARRAY[]::text[], 'Kakao oder Schokolade', ARRAY[]::text[]),
    ('COCONUT', 'Kokosnuss', ARRAY[]::text[], 'Kokosnuss', ARRAY[]::text[]),
    ('COCONUT_CREAM', 'Kokoscreme', ARRAY[]::text[], 'Kokoscreme', ARRAY[]::text[]),
    ('COCONUT_FLAKES', 'Kokosraspeln', ARRAY[]::text[], 'Kokosraspeln', ARRAY[]::text[]),
    ('COCONUT_MILK', 'Kokosmilch', ARRAY[]::text[], 'Kokosmilch', ARRAY[]::text[]),
    ('COCONUT_OIL', 'Kokosöl', ARRAY[]::text[], 'Kokosöl', ARRAY['Kokosfett']::text[]),
    ('COCONUT_PRODUCTS', 'Kokoszutat', ARRAY[]::text[], 'Kokoszutat', ARRAY[]::text[]),
    ('COCONUT_VINEGAR', 'Kokosessig', ARRAY[]::text[], 'Kokosessig', ARRAY[]::text[]),
    ('COCONUT_WATER', 'Kokoswasser', ARRAY[]::text[], 'Kokoswasser', ARRAY[]::text[]),
    ('COD', 'Kabeljau', ARRAY[]::text[], 'Kabeljau', ARRAY['Dorsch']::text[]),
    ('COFFEE', 'Kaffee', ARRAY[]::text[], 'Kaffee', ARRAY[]::text[]),
    ('COGNAC', 'Cognac', ARRAY[]::text[], 'Cognac', ARRAY[]::text[]),
    ('COM_ME', 'Mẻ oder Cơm mẻ', ARRAY[]::text[], 'Mẻ', ARRAY['Cơm mẻ']::text[]),
    ('CONDENSED_MILK', 'gezuckerte Kondensmilch', ARRAY[]::text[], 'gezuckerte Kondensmilch', ARRAY[]::text[]),
    ('CONFECTIONERY', 'Süßware', ARRAY[]::text[], 'Süßware', ARRAY[]::text[]),
    ('COOKED_HAM', 'Kochschinken', ARRAY[]::text[], 'Kochschinken', ARRAY[]::text[]),
    ('COOKING_ALCOHOL', 'Kochalkohol', ARRAY[]::text[], 'Kochalkohol', ARRAY[]::text[]),
    ('COOKING_FATS', 'Kochfett', ARRAY[]::text[], 'Kochfett', ARRAY[]::text[]),
    ('CORIANDER_ROOT', 'Korianderwurzel', ARRAY[]::text[], 'Korianderwurzel', ARRAY[]::text[]),
    ('CORIANDER_SEED', 'Koriandersaat', ARRAY[]::text[], 'Koriandersaat', ARRAY['Koriandersamen']::text[]),
    ('CORN', 'Mais', ARRAY[]::text[], 'Mais', ARRAY[]::text[]),
    ('CORNMEAL', 'Maismehl', ARRAY[]::text[], 'Maismehl', ARRAY[]::text[]),
    ('CORNSTARCH', 'Maisstärke', ARRAY[]::text[], 'Maisstärke', ARRAY[]::text[]),
    ('COUSCOUS', 'Couscous', ARRAY[]::text[], 'Couscous', ARRAY[]::text[]),
    ('CRAB', 'Krabben oder Krebsfleisch', ARRAY[]::text[], 'Krabben oder Krebsfleisch', ARRAY[]::text[]),
    ('CRANBERRY', 'Cranberry', ARRAY[]::text[], 'Cranberry', ARRAY[]::text[]),
    ('CRAYFISH', 'Flusskrebse', ARRAY[]::text[], 'Flusskrebse', ARRAY[]::text[]),
    ('CREAM', 'Sahne', ARRAY[]::text[], 'Sahne', ARRAY['Rahm']::text[]),
    ('CREAM_CHEESE', 'Frischkäse', ARRAY[]::text[], 'Frischkäse', ARRAY[]::text[]),
    ('CREME_FRAICHE', 'Crème fraîche', ARRAY[]::text[], 'Crème fraîche', ARRAY[]::text[]),
    ('CRISPBREAD', 'Knäckebrot', ARRAY[]::text[], 'Knäckebrot', ARRAY[]::text[]),
    ('CROISSANT', 'Croissant', ARRAY[]::text[], 'Croissant', ARRAY[]::text[]),
    ('CRUSTACEANS', 'Krustentiere', ARRAY[]::text[], 'Krustentiere', ARRAY['Krebstiere']::text[]),
    ('CUCUMBER', 'Gurke', ARRAY[]::text[], 'Gurke', ARRAY[]::text[]),
    ('CULANTRO', 'Culantro oder Sägeblattkoriander', ARRAY[]::text[], 'Culantro', ARRAY['Langer Koriander', 'Sägeblattkoriander']::text[]),
    ('CULTURED_DAIRY', 'gesäuertes Milchprodukt', ARRAY[]::text[], 'gesäuertes Milchprodukt', ARRAY[]::text[]),
    ('CUMBERLAND_SAUSAGE', 'Cumberland Sausage', ARRAY[]::text[], 'Cumberland Sausage', ARRAY[]::text[]),
    ('CUMIN', 'Kreuzkümmel', ARRAY[]::text[], 'Kreuzkümmel', ARRAY['Cumin']::text[]),
    ('CURED_MEAT', 'gepökeltes oder luftgetrocknetes Fleisch', ARRAY[]::text[], 'gepökeltes oder luftgetrocknetes Fleisch', ARRAY[]::text[]),
    ('CURRY_LEAVES', 'Curryblätter', ARRAY[]::text[], 'Curryblätter', ARRAY[]::text[]),
    ('CURRY_POWDER', 'Currypulver', ARRAY[]::text[], 'Currypulver', ARRAY[]::text[]),
    ('CUSTARD', 'Custard', ARRAY[]::text[], 'Custard', ARRAY[]::text[]),
    ('CUTTLEFISH', 'Sepia', ARRAY[]::text[], 'Sepia', ARRAY[]::text[]),
    ('DAIKON', 'Daikon', ARRAY[]::text[], 'Daikon', ARRAY[]::text[]),
    ('DAING', 'Daing', ARRAY[]::text[], 'Daing', ARRAY[]::text[]),
    ('DAIRY_PRODUCTS', 'Milchprodukte', ARRAY[]::text[], 'Milchprodukte', ARRAY[]::text[]),
    ('DANABLU', 'Danablu', ARRAY[]::text[], 'Danablu', ARRAY[]::text[]),
    ('DANBO', 'Danbo', ARRAY[]::text[], 'Danbo', ARRAY[]::text[]),
    ('DARK_CHOCOLATE', 'Zartbitterschokolade', ARRAY[]::text[], 'Zartbitterschokolade', ARRAY['Bitterschokolade']::text[]),
    ('DARK_SOY_SAUCE', 'dunkle Sojasauce', ARRAY[]::text[], 'dunkle Sojasauce', ARRAY[]::text[]),
    ('DASHI', 'Dashi', ARRAY[]::text[], 'Dashi', ARRAY[]::text[]),
    ('DATE', 'Dattel', ARRAY[]::text[], 'Dattel', ARRAY[]::text[]),
    ('DATE_SYRUP', 'Dattelsirup', ARRAY[]::text[], 'Dattelsirup', ARRAY[]::text[]),
    ('DIJON_MUSTARD', 'Dijon-Senf', ARRAY[]::text[], 'Dijon-Senf', ARRAY[]::text[]),
    ('DILL', 'Dill', ARRAY[]::text[], 'Dill', ARRAY[]::text[]),
    ('DOENJANG', 'Doenjang', ARRAY[]::text[], 'Doenjang', ARRAY[]::text[]),
    ('DOUBANJIANG', 'Doubanjiang', ARRAY[]::text[], 'Doubanjiang', ARRAY[]::text[]),
    ('DRAGON_FRUIT', 'Drachenfrucht', ARRAY[]::text[], 'Drachenfrucht', ARRAY['Pitahaya', 'Pitaya']::text[]),
    ('DRIED_APRICOT', 'getrocknete Aprikosen', ARRAY[]::text[], 'getrocknete Aprikosen', ARRAY[]::text[]),
    ('DRIED_CHILI', 'getrocknete Chili', ARRAY[]::text[], 'getrocknete Chili', ARRAY[]::text[]),
    ('DRIED_FISH', 'getrockneter Fisch', ARRAY[]::text[], 'getrockneter Fisch', ARRAY[]::text[]),
    ('DRIED_FRUIT', 'Trockenfrüchte', ARRAY[]::text[], 'Trockenfrüchte', ARRAY['Dörrobst', 'Trockenobst']::text[]),
    ('DRIED_SHRIMP', 'getrocknete Garnelen', ARRAY[]::text[], 'getrocknete Garnelen', ARRAY[]::text[]),
    ('DRIED_WILD_MUSHROOMS', 'getrocknete Waldpilze', ARRAY[]::text[], 'getrocknete Waldpilze', ARRAY[]::text[]),
    ('DUCK', 'Ente', ARRAY[]::text[], 'Ente', ARRAY[]::text[]),
    ('DUCK_BREAST', 'Entenbrust', ARRAY[]::text[], 'Entenbrust', ARRAY[]::text[]),
    ('DUCK_CONFIT', 'Entenconfit', ARRAY[]::text[], 'Entenconfit', ARRAY['Confit de canard']::text[]),
    ('DUCK_EGG', 'Entenei', ARRAY[]::text[], 'Entenei', ARRAY[]::text[]),
    ('DUCK_FAT', 'Entenfett', ARRAY[]::text[], 'Entenfett', ARRAY['Entenschmalz']::text[]),
    ('DUCK_LEG', 'Entenkeule', ARRAY[]::text[], 'Entenkeule', ARRAY[]::text[]),
    ('DULSE', 'Dulse', ARRAY[]::text[], 'Dulse', ARRAY['Lappentang']::text[]),
    ('DUMPLING_DOUGH', 'Dumpling-Teig', ARRAY[]::text[], 'Dumpling-Teig', ARRAY[]::text[]),
    ('DUMPLING_WRAPPERS', 'Teigblatt oder Dumpling-Hülle', ARRAY[]::text[], 'Teigblatt oder Dumpling-Hülle', ARRAY[]::text[]),
    ('EDAM', 'Edamer', ARRAY[]::text[], 'Edamer', ARRAY['Edamer Käse']::text[]),
    ('EDAMAME', 'Edamame', ARRAY[]::text[], 'Edamame', ARRAY[]::text[]),
    ('EDIBLE_SNAILS', 'essbare Schnecken', ARRAY[]::text[], 'essbare Schnecken', ARRAY[]::text[]),
    ('EEL', 'Aal', ARRAY[]::text[], 'Aal', ARRAY[]::text[]),
    ('EGG', 'Ei', ARRAY[]::text[], 'Ei', ARRAY['Hühnerei']::text[]),
    ('EGGPLANT', 'Aubergine', ARRAY[]::text[], 'Aubergine', ARRAY[]::text[]),
    ('EGGS', 'Eier', ARRAY[]::text[], 'Eier', ARRAY[]::text[]),
    ('EGG_FLECKERL', 'Eierfleckerl', ARRAY[]::text[], 'Eierfleckerl', ARRAY[]::text[]),
    ('EGG_NOODLES', 'Eiernudeln', ARRAY[]::text[], 'Eiernudeln', ARRAY[]::text[]),
    ('EGUSI_SEEDS', 'Egusi-Samen', ARRAY[]::text[], 'Egusi-Samen', ARRAY[]::text[]),
    ('ELDERBERRY', 'Holunderbeeren', ARRAY[]::text[], 'Holunderbeeren', ARRAY[]::text[]),
    ('ENDIVE', 'Endivie', ARRAY[]::text[], 'Endivie', ARRAY[]::text[]),
    ('ENGLISH_MUSTARD', 'English Mustard', ARRAY[]::text[], 'Englischer Senf', ARRAY['English Mustard']::text[]),
    ('ENOKI', 'Enoki', ARRAY[]::text[], 'Enoki', ARRAY[]::text[]),
    ('ESCARGOT', 'Weinbergschnecken', ARRAY[]::text[], 'Weinbergschnecken', ARRAY['Escargots']::text[]),
    ('EVAPORATED_MILK', 'Kondensmilch', ARRAY[]::text[], 'Kondensmilch', ARRAY[]::text[]),
    ('FARRO', 'Emmer oder Farro', ARRAY[]::text[], 'Farro', ARRAY['Emmer']::text[]),
    ('FENALAR', 'Fenalår', ARRAY[]::text[], 'Fenalår', ARRAY[]::text[]),
    ('FENNEL', 'Fenchel', ARRAY[]::text[], 'Fenchel', ARRAY[]::text[]),
    ('FENNEL_SEED', 'Fenchelsaat', ARRAY[]::text[], 'Fenchelsaat', ARRAY['Fenchelsamen']::text[]),
    ('FENUGREEK', 'Bockshornklee', ARRAY[]::text[], 'Bockshornklee', ARRAY[]::text[]),
    ('FERMENTED_BLACK_BEANS', 'fermentierte schwarze Bohnen', ARRAY[]::text[], 'Fermentierte schwarze Bohnen', ARRAY['Douchi']::text[]),
    ('FERMENTED_CUCUMBER', 'Salzgurke', ARRAY[]::text[], 'Salzgurke', ARRAY[]::text[]),
    ('FERMENTED_SEASONINGS', 'fermentierte Würzzutat', ARRAY[]::text[], 'fermentierte Würzzutat', ARRAY[]::text[]),
    ('FERMENTED_TOFU', 'fermentierter Tofu', ARRAY[]::text[], 'Fermentierter Tofu', ARRAY[]::text[]),
    ('FETA', 'Feta', ARRAY[]::text[], 'Feta', ARRAY[]::text[]),
    ('FIG', 'Feige', ARRAY[]::text[], 'Feige', ARRAY[]::text[]),
    ('FINGERROOT', 'Fingerwurz', ARRAY[]::text[], 'Fingerwurz', ARRAY[]::text[]),
    ('FIRM_TOFU', 'fester Tofu', ARRAY[]::text[], 'fester Tofu', ARRAY[]::text[]),
    ('FISH', 'Fisch', ARRAY[]::text[], 'Fisch', ARRAY[]::text[]),
    ('FISH_MINT', 'Fischminze', ARRAY[]::text[], 'Fischminze', ARRAY[]::text[]),
    ('FISH_ROE', 'Fischrogen', ARRAY[]::text[], 'Fischrogen', ARRAY[]::text[]),
    ('FISH_SAUCE', 'Fischsauce', ARRAY[]::text[], 'Fischsauce', ARRAY[]::text[]),
    ('FISH_STOCK', 'Fischfond', ARRAY[]::text[], 'Fischfond', ARRAY[]::text[]),
    ('FIVE_SPICE', 'Fünf-Gewürze-Pulver', ARRAY[]::text[], 'Fünf-Gewürze-Pulver', ARRAY['Five-Spice Powder', 'Fünf-Gewürz-Pulver', 'Fünf-Gewürze-Mischung']::text[]),
    ('FLATBREAD', 'Fladenbrot', ARRAY[]::text[], 'Fladenbrot', ARRAY[]::text[]),
    ('FLATBROD', 'Flatbrød', ARRAY[]::text[], 'Flatbrød', ARRAY[]::text[]),
    ('FLAXSEED', 'Leinsamen', ARRAY[]::text[], 'Leinsamen', ARRAY[]::text[]),
    ('FLEUR_DE_SEL', 'Fleur de sel', ARRAY[]::text[], 'Fleur de sel', ARRAY[]::text[]),
    ('FLOUR', 'Mehl', ARRAY[]::text[], 'Mehl', ARRAY[]::text[]),
    ('FLOWER_VEGETABLES', 'Blütengemüse', ARRAY[]::text[], 'Blütengemüse', ARRAY[]::text[]),
    ('FOIE_GRAS', 'Foie gras', ARRAY[]::text[], 'Foie gras', ARRAY[]::text[]),
    ('FRANKFURT_GREEN_SAUCE', 'Frankfurter Grüne Soße', ARRAY[]::text[], 'Frankfurter Grüne Soße', ARRAY[]::text[]),
    ('FREEKEH', 'Freekeh', ARRAY[]::text[], 'Freekeh', ARRAY[]::text[]),
    ('FRENCH_FRIES', 'Pommes frites', ARRAY[]::text[], 'Pommes frites', ARRAY['Pommes']::text[]),
    ('FRESHWATER_SNAILS', 'Süßwasserschnecken', ARRAY[]::text[], 'Süßwasserschnecken', ARRAY[]::text[]),
    ('FRESH_DAIRY_PRODUCTS', 'frisches Milchprodukt', ARRAY[]::text[], 'frisches Milchprodukt', ARRAY[]::text[]),
    ('FRESH_HERBS', 'Kräuter und Würzblätter', ARRAY[]::text[], 'Kräuter und Würzblätter', ARRAY[]::text[]),
    ('FRESH_TURMERIC', 'frischer Kurkuma', ARRAY[]::text[], 'frischer Kurkuma', ARRAY[]::text[]),
    ('FRIED_ONIONS', 'Röstzwiebeln', ARRAY[]::text[], 'Röstzwiebeln', ARRAY[]::text[]),
    ('FROG_LEGS', 'Froschschenkel', ARRAY[]::text[], 'Froschschenkel', ARRAY[]::text[]),
    ('FRUIT', 'Obst', ARRAY[]::text[], 'Obst', ARRAY[]::text[]),
    ('FRUIT_DUMPLING', 'Obstknödel', ARRAY[]::text[], 'Obstknödel', ARRAY[]::text[]),
    ('FRUIT_VEGETABLES', 'Fruchtgemüse', ARRAY[]::text[], 'Fruchtgemüse', ARRAY[]::text[]),
    ('GAC_FRUIT', 'Gấc-Frucht', ARRAY[]::text[], 'Gấc-Frucht', ARRAY[]::text[]),
    ('GALANGAL', 'Galgant', ARRAY[]::text[], 'Galgant', ARRAY[]::text[]),
    ('GAME_MEAT', 'Wildfleisch', ARRAY[]::text[], 'Wildfleisch', ARRAY['Wildbret']::text[]),
    ('GARAM_MASALA', 'Garam Masala', ARRAY[]::text[], 'Garam Masala', ARRAY[]::text[]),
    ('GARLIC', 'Knoblauch', ARRAY[]::text[], 'Knoblauch', ARRAY[]::text[]),
    ('GARLIC_BUTTER', 'Knoblauchbutter', ARRAY[]::text[], 'Knoblauchbutter', ARRAY[]::text[]),
    ('GARLIC_CHIVES', 'Knoblauch-Schnittlauch', ARRAY[]::text[], 'Knoblauch-Schnittlauch', ARRAY['Schnittknoblauch']::text[]),
    ('GARLIC_POWDER', 'Knoblauchpulver', ARRAY[]::text[], 'Knoblauchpulver', ARRAY[]::text[]),
    ('GHEE', 'Ghee', ARRAY[]::text[], 'Ghee', ARRAY[]::text[]),
    ('GINGER', 'Ingwer', ARRAY[]::text[], 'Ingwer', ARRAY[]::text[]),
    ('GIO_LUA', 'Giò lụa oder Chả lụa', ARRAY[]::text[], 'Giò lụa', ARRAY['Chả lụa']::text[]),
    ('GLASS_NOODLES', 'Glasnudeln', ARRAY[]::text[], 'Glasnudeln', ARRAY[]::text[]),
    ('GNOCCHI', 'Gnocchi', ARRAY[]::text[], 'Gnocchi', ARRAY[]::text[]),
    ('GOAT', 'Ziegenfleisch', ARRAY[]::text[], 'Ziegenfleisch', ARRAY[]::text[]),
    ('GOAT_CHEESE', 'Ziegenkäse', ARRAY[]::text[], 'Ziegenkäse', ARRAY[]::text[]),
    ('GOCHUGARU', 'Gochugaru', ARRAY[]::text[], 'Gochugaru', ARRAY[]::text[]),
    ('GOCHUJANG', 'Gochujang', ARRAY[]::text[], 'Gochujang', ARRAY[]::text[]),
    ('GOLDEN_SYRUP', 'Golden Syrup', ARRAY[]::text[], 'Golden Syrup', ARRAY[]::text[]),
    ('GOOSE', 'Gans', ARRAY[]::text[], 'Gans', ARRAY[]::text[]),
    ('GOOSEBERRY', 'Stachelbeere', ARRAY[]::text[], 'Stachelbeere', ARRAY[]::text[]),
    ('GOUDA', 'Gouda', ARRAY[]::text[], 'Gouda', ARRAY[]::text[]),
    ('GRAINS', 'Getreide oder Pseudogetreide', ARRAY[]::text[], 'Getreide oder Pseudogetreide', ARRAY[]::text[]),
    ('GRAPE', 'Weintrauben', ARRAY[]::text[], 'Weintrauben', ARRAY[]::text[]),
    ('GRAPEFRUIT', 'Grapefruit', ARRAY[]::text[], 'Grapefruit', ARRAY[]::text[]),
    ('GRAVLAX', 'Gravlax', ARRAY[]::text[], 'Gravlax', ARRAY['Graved Lachs']::text[]),
    ('GREEK_YOGURT', 'griechischer Joghurt', ARRAY[]::text[], 'griechischer Joghurt', ARRAY[]::text[]),
    ('GREEN_ASPARAGUS', 'grüner Spargel', ARRAY[]::text[], 'grüner Spargel', ARRAY[]::text[]),
    ('GREEN_BEANS', 'grüne Bohnen', ARRAY[]::text[], 'grüne Bohnen', ARRAY[]::text[]),
    ('GREEN_BELL_PEPPER', 'grüne Paprika', ARRAY[]::text[], 'grüne Paprika', ARRAY[]::text[]),
    ('GREEN_PAPAYA', 'grüne Papaya', ARRAY[]::text[], 'grüne Papaya', ARRAY[]::text[]),
    ('GREEN_PEAS', 'grüne Erbsen', ARRAY[]::text[], 'grüne Erbsen', ARRAY[]::text[]),
    ('GREEN_PEPPER', 'grüne Pfefferkörner', ARRAY[]::text[], 'grüne Pfefferkörner', ARRAY[]::text[]),
    ('GREEN_RICE_FLAKES', 'Cốm oder grüne Reisflocken', ARRAY[]::text[], 'Cốm', ARRAY[]::text[]),
    ('GREEN_SPLIT_PEAS', 'grüne Schälerbsen', ARRAY[]::text[], 'grüne Schälerbsen', ARRAY[]::text[]),
    ('GREEN_TEA', 'grüner Tee', ARRAY[]::text[], 'grüner Tee', ARRAY[]::text[]),
    ('GRUYERE', 'Gruyère', ARRAY[]::text[], 'Gruyère', ARRAY['Greyerzer']::text[]),
    ('GUAVA', 'Guave', ARRAY[]::text[], 'Guave', ARRAY[]::text[]),
    ('HABANERO', 'Habanero', ARRAY[]::text[], 'Habanero', ARRAY[]::text[]),
    ('HADDOCK', 'Schellfisch', ARRAY[]::text[], 'Schellfisch', ARRAY[]::text[]),
    ('HAGGIS', 'Haggis', ARRAY[]::text[], 'Haggis', ARRAY[]::text[]),
    ('HAKE', 'Seehecht', ARRAY[]::text[], 'Seehecht', ARRAY[]::text[]),
    ('HALIBUT', 'Heilbutt', ARRAY[]::text[], 'Heilbutt', ARRAY[]::text[]),
    ('HALLOUMI', 'Halloumi', ARRAY[]::text[], 'Halloumi', ARRAY[]::text[]),
    ('HAM', 'Schinken', ARRAY[]::text[], 'Schinken', ARRAY[]::text[]),
    ('HARISSA', 'Harissa', ARRAY[]::text[], 'Harissa', ARRAY[]::text[]),
    ('HARZER_CHEESE', 'Harzer Käse', ARRAY[]::text[], 'Harzer Käse', ARRAY[]::text[]),
    ('HAZELNUT', 'Haselnüsse', ARRAY[]::text[], 'Haselnüsse', ARRAY[]::text[]),
    ('HEMP_SEEDS', 'Hanfsamen', ARRAY[]::text[], 'Hanfsamen', ARRAY[]::text[]),
    ('HERBES_DE_PROVENCE', 'Kräuter der Provence', ARRAY[]::text[], 'Kräuter der Provence', ARRAY['Herbes de Provence']::text[]),
    ('HERB_BUTTER', 'Kräuterbutter', ARRAY[]::text[], 'Kräuterbutter', ARRAY[]::text[]),
    ('HERRING', 'Hering', ARRAY[]::text[], 'Hering', ARRAY[]::text[]),
    ('HERVE_CHEESE', 'Herve-Käse', ARRAY[]::text[], 'Herve-Käse', ARRAY[]::text[]),
    ('HIJIKI', 'Hijiki', ARRAY[]::text[], 'Hijiki', ARRAY[]::text[]),
    ('HOISIN_SAUCE', 'Hoisinsauce', ARRAY[]::text[], 'Hoisinsauce', ARRAY[]::text[]),
    ('HOKKAIDO_SQUASH', 'Hokkaido-Kürbis', ARRAY[]::text[], 'Hokkaido-Kürbis', ARRAY[]::text[]),
    ('HOLY_BASIL', 'Krapao', ARRAY[]::text[], 'Krapao', ARRAY['Heiliges Basilikum']::text[]),
    ('HONEY', 'Honig', ARRAY[]::text[], 'Honig', ARRAY[]::text[]),
    ('HONEYDEW_MELON', 'Honigmelone', ARRAY[]::text[], 'Honigmelone', ARRAY[]::text[]),
    ('HORSERADISH', 'Meerrettich', ARRAY[]::text[], 'Meerrettich', ARRAY[]::text[]),
    ('HOT_MUSTARD', 'scharfer Senf', ARRAY[]::text[], 'scharfer Senf', ARRAY[]::text[]),
    ('HOT_PAPRIKA_POWDER', 'Paprikapulver rosenscharf', ARRAY[]::text[], 'Paprikapulver rosenscharf', ARRAY[]::text[]),
    ('IBERICO_HAM', 'Jamón ibérico', ARRAY[]::text[], 'Jamón ibérico', ARRAY[]::text[]),
    ('INVERTEBRATES', 'wirbellose Tiere', ARRAY[]::text[], 'wirbellose Tiere', ARRAY[]::text[]),
    ('JACKFRUIT', 'Jackfruit', ARRAY[]::text[], 'Jackfruit', ARRAY['Jackfrucht']::text[]),
    ('JALAPENO', 'Jalapeño', ARRAY[]::text[], 'Jalapeño', ARRAY[]::text[]),
    ('JASMINE_RICE', 'Jasminreis', ARRAY[]::text[], 'Jasminreis', ARRAY[]::text[]),
    ('JENEVER', 'Jenever', ARRAY[]::text[], 'Jenever', ARRAY['Genever']::text[]),
    ('JERK_SEASONING', 'Jerk-Gewürzmischung', ARRAY[]::text[], 'Jerk-Gewürzmischung', ARRAY[]::text[]),
    ('JERUSALEM_ARTICHOKE', 'Topinambur', ARRAY[]::text[], 'Topinambur', ARRAY[]::text[]),
    ('JUNIPER_BERRIES', 'Wacholderbeeren', ARRAY[]::text[], 'Wacholderbeeren', ARRAY[]::text[]),
    ('KAESEKRAINER', 'Käsekrainer', ARRAY[]::text[], 'Käsekrainer', ARRAY[]::text[]),
    ('KAFFIR_LIME_LEAVES', 'Makrut-Limettenblätter', ARRAY[]::text[], 'Makrut-Limettenblätter', ARRAY['Kaffir-Limettenblätter']::text[]),
    ('KALE', 'Grünkohl', ARRAY[]::text[], 'Grünkohl', ARRAY[]::text[]),
    ('KASHMIRI_CHILI_POWDER', 'Kashmiri-Chilipulver', ARRAY[]::text[], 'Kashmiri-Chilipulver', ARRAY[]::text[]),
    ('KASSELER', 'Kasseler', ARRAY[]::text[], 'Kasseler', ARRAY['Kassler']::text[]),
    ('KECAP_MANIS', 'Kecap Manis', ARRAY[]::text[], 'Kecap Manis', ARRAY['Ketjap Manis']::text[]),
    ('KEFIR', 'Kefir', ARRAY[]::text[], 'Kefir', ARRAY[]::text[]),
    ('KETCHUP', 'Ketchup', ARRAY[]::text[], 'Ketchup', ARRAY['Tomatenketchup']::text[]),
    ('KIDNEY', 'Niere', ARRAY[]::text[], 'Niere', ARRAY[]::text[]),
    ('KIDNEY_BEANS', 'Kidneybohnen', ARRAY[]::text[], 'Kidneybohnen', ARRAY[]::text[]),
    ('KIMCHI', 'Kimchi', ARRAY[]::text[], 'Kimchi', ARRAY[]::text[]),
    ('KING_OYSTER_MUSHROOM', 'Kräuterseitlinge', ARRAY[]::text[], 'Kräuterseitlinge', ARRAY[]::text[]),
    ('KIWI', 'Kiwi', ARRAY[]::text[], 'Kiwi', ARRAY[]::text[]),
    ('KLIPPFISH', 'Klippfisch', ARRAY[]::text[], 'Klippfisch', ARRAY[]::text[]),
    ('KOHLRABI', 'Kohlrabi', ARRAY[]::text[], 'Kohlrabi', ARRAY[]::text[]),
    ('KOLACHE', 'Kolatschen', ARRAY[]::text[], 'Kolatschen', ARRAY['Koláč']::text[]),
    ('KOMBU', 'Kombu', ARRAY[]::text[], 'Kombu', ARRAY[]::text[]),
    ('LAKSA_PASTE', 'Laksa-Paste', ARRAY[]::text[], 'Laksa-Paste', ARRAY[]::text[]),
    ('LAMB', 'Lamm', ARRAY[]::text[], 'Lamm', ARRAY['Lammfleisch']::text[]),
    ('LAMBIC', 'Lambic', ARRAY[]::text[], 'Lambic', ARRAY[]::text[]),
    ('LAMBS_LETTUCE', 'Feldsalat', ARRAY[]::text[], 'Feldsalat', ARRAY['Rapunzelsalat']::text[]),
    ('LAMB_CHOP', 'Lammkotelett', ARRAY[]::text[], 'Lammkotelett', ARRAY[]::text[]),
    ('LAMB_LEG', 'Lammkeule', ARRAY[]::text[], 'Lammkeule', ARRAY[]::text[]),
    ('LAMB_MINCE', 'Lammhack', ARRAY[]::text[], 'Lammhack', ARRAY['Lammhackfleisch']::text[]),
    ('LAMB_SHOULDER', 'Lammschulter', ARRAY[]::text[], 'Lammschulter', ARRAY[]::text[]),
    ('LAND_SNAILS', 'Landschnecken', ARRAY[]::text[], 'Landschnecken', ARRAY[]::text[]),
    ('LANGOUSTINE', 'Kaisergranat', ARRAY[]::text[], 'Kaisergranat', ARRAY['Kaiserhummer']::text[]),
    ('LARD', 'Schweineschmalz', ARRAY[]::text[], 'Schweineschmalz', ARRAY[]::text[]),
    ('LASAGNE_SHEETS', 'Lasagneplatten', ARRAY[]::text[], 'Lasagneplatten', ARRAY['Lasagneblätter']::text[]),
    ('LA_LOT_LEAVES', 'Lá-lốt-Blätter', ARRAY[]::text[], 'Lá-lốt-Blätter', ARRAY[]::text[]),
    ('LEAFY_GREENS', 'Blattgemüse', ARRAY[]::text[], 'Blattgemüse', ARRAY[]::text[]),
    ('LEBERKAESE', 'Leberkäse', ARRAY[]::text[], 'Leberkäse', ARRAY['Fleischkäse']::text[]),
    ('LEEK', 'Lauch', ARRAY[]::text[], 'Lauch', ARRAY['Porree']::text[]),
    ('LEFSE', 'Lefse', ARRAY[]::text[], 'Lefse', ARRAY[]::text[]),
    ('LEGUMES', 'Hülsenfrüchte', ARRAY[]::text[], 'Hülsenfrüchte', ARRAY[]::text[]),
    ('LEIPAJUUSTO', 'Leipäjuusto (Brotkäse)', ARRAY[]::text[], 'Leipäjuusto', ARRAY['Brotkäse', 'Juustoleipä']::text[]),
    ('LEMON', 'Zitrone', ARRAY[]::text[], 'Zitrone', ARRAY[]::text[]),
    ('LEMONGRASS', 'Zitronengras', ARRAY[]::text[], 'Zitronengras', ARRAY[]::text[]),
    ('LENTILS', 'Linsen', ARRAY[]::text[], 'Linsen', ARRAY[]::text[]),
    ('LETTUCE', 'Kopfsalat', ARRAY[]::text[], 'Kopfsalat', ARRAY[]::text[]),
    ('LIEGE_SYRUP', 'Sirop de Liège', ARRAY[]::text[], 'Sirop de Liège', ARRAY[]::text[]),
    ('LIEGE_WAFFLE', 'Lütticher Waffel', ARRAY[]::text[], 'Lütticher Waffel', ARRAY[]::text[]),
    ('LIGHT_SOY_SAUCE', 'helle Sojasauce', ARRAY[]::text[], 'helle Sojasauce', ARRAY[]::text[]),
    ('LIME', 'Limette', ARRAY[]::text[], 'Limette', ARRAY[]::text[]),
    ('LINGONBERRY', 'Preiselbeeren', ARRAY[]::text[], 'Preiselbeeren', ARRAY[]::text[]),
    ('LINGONBERRY_PRESERVES', 'Preiselbeer-Konfitüre/-kompott', ARRAY[]::text[], 'Preiselbeer-Konfitüre/-kompott', ARRAY[]::text[]),
    ('LIQUORICE', 'Lakritz', ARRAY[]::text[], 'Lakritz', ARRAY['Lakritze']::text[]),
    ('LIVER_PATE', 'Leberpastete', ARRAY[]::text[], 'Leberpastete', ARRAY[]::text[]),
    ('LIVER_SAUSAGE', 'Leberwurst', ARRAY[]::text[], 'Leberwurst', ARRAY[]::text[]),
    ('LOBSTER', 'Hummer', ARRAY[]::text[], 'Hummer', ARRAY[]::text[]),
    ('LONGGANISA', 'Longganisa', ARRAY[]::text[], 'Longganisa', ARRAY[]::text[]),
    ('LORNE_SAUSAGE', 'Lorne Sausage', ARRAY[]::text[], 'Lorne Sausage', ARRAY['Square Sausage']::text[]),
    ('LOTUS_ROOT', 'Lotuswurzel', ARRAY[]::text[], 'Lotuswurzel', ARRAY[]::text[]),
    ('LOTUS_SEEDS', 'Lotussamen', ARRAY[]::text[], 'Lotussamen', ARRAY[]::text[]),
    ('LOVAGE', 'Liebstöckel', ARRAY[]::text[], 'Liebstöckel', ARRAY['Maggikraut']::text[]),
    ('LUPIN', 'Lupinen', ARRAY[]::text[], 'Lupinen', ARRAY[]::text[]),
    ('LUTEFISK', 'Lutefisk', ARRAY[]::text[], 'Lutefisk', ARRAY[]::text[]),
    ('LYCHEE', 'Litschi', ARRAY[]::text[], 'Litschi', ARRAY['Lychee']::text[]),
    ('MACADAMIA', 'Macadamianüsse', ARRAY[]::text[], 'Macadamianüsse', ARRAY[]::text[]),
    ('MACAPUNO', 'Macapuno', ARRAY[]::text[], 'Macapuno', ARRAY[]::text[]),
    ('MACKEREL', 'Makrele', ARRAY[]::text[], 'Makrele', ARRAY[]::text[]),
    ('MAGGI_SEASONING', 'Maggi-Würze', ARRAY[]::text[], 'Maggi-Würze', ARRAY[]::text[]),
    ('MAITAKE', 'Maitake', ARRAY[]::text[], 'Maitake', ARRAY['Klapperschwamm']::text[]),
    ('MALT_VINEGAR', 'Malzessig', ARRAY[]::text[], 'Malzessig', ARRAY[]::text[]),
    ('MAM_NEM', 'Mắm nêm', ARRAY[]::text[], 'Mắm nêm', ARRAY[]::text[]),
    ('MAM_RUOC', 'Mắm ruốc', ARRAY[]::text[], 'Mắm ruốc', ARRAY[]::text[]),
    ('MAM_TOM', 'Mắm tôm', ARRAY[]::text[], 'Mắm tôm', ARRAY[]::text[]),
    ('MANCHEGO', 'Manchego', ARRAY[]::text[], 'Manchego', ARRAY[]::text[]),
    ('MANDARIN', 'Mandarine', ARRAY[]::text[], 'Mandarine', ARRAY[]::text[]),
    ('MANGO', 'Mango', ARRAY[]::text[], 'Mango', ARRAY[]::text[]),
    ('MAPLE_SYRUP', 'Ahornsirup', ARRAY[]::text[], 'Ahornsirup', ARRAY[]::text[]),
    ('MARJORAM', 'Majoran', ARRAY[]::text[], 'Majoran', ARRAY[]::text[]),
    ('MARROWFAT_PEAS', 'Marrowfat Peas', ARRAY[]::text[], 'Marrowfat Peas', ARRAY[]::text[]),
    ('MARSALA', 'Marsala', ARRAY[]::text[], 'Marsala', ARRAY[]::text[]),
    ('MARZIPAN', 'Marzipan', ARRAY[]::text[], 'Marzipan', ARRAY[]::text[]),
    ('MASA_HARINA', 'Masa Harina', ARRAY[]::text[], 'Masa Harina', ARRAY[]::text[]),
    ('MASCARPONE', 'Mascarpone', ARRAY[]::text[], 'Mascarpone', ARRAY[]::text[]),
    ('MASSAMAN_CURRY_PASTE', 'Massaman-Currypaste', ARRAY[]::text[], 'Massaman-Currypaste', ARRAY[]::text[]),
    ('MATCHA', 'Matcha', ARRAY[]::text[], 'Matcha', ARRAY[]::text[]),
    ('MATJES', 'Matjes', ARRAY[]::text[], 'Matjes', ARRAY[]::text[]),
    ('MAYONNAISE', 'Mayonnaise', ARRAY[]::text[], 'Mayonnaise', ARRAY[]::text[]),
    ('MEAT', 'Fleisch', ARRAY[]::text[], 'Fleisch', ARRAY[]::text[]),
    ('MEAT_ASPIC', 'Fleischsülze', ARRAY[]::text[], 'Fleischsülze', ARRAY[]::text[]),
    ('MELONS', 'Melone', ARRAY[]::text[], 'Melone', ARRAY[]::text[]),
    ('MEMBRILLO', 'Quittenpaste', ARRAY[]::text[], 'Quittenpaste', ARRAY['Dulce de membrillo', 'Quittenbrot']::text[]),
    ('MERGUEZ', 'Merguez', ARRAY[]::text[], 'Merguez', ARRAY[]::text[]),
    ('MILK', 'Milch', ARRAY[]::text[], 'Milch', ARRAY['Kuhmilch']::text[]),
    ('MILKFISH', 'Milchfisch oder Bangus', ARRAY[]::text[], 'Milchfisch', ARRAY['Bangus']::text[]),
    ('MILK_CHOCOLATE', 'Milchschokolade', ARRAY[]::text[], 'Milchschokolade', ARRAY[]::text[]),
    ('MILLET', 'Hirse', ARRAY[]::text[], 'Hirse', ARRAY[]::text[]),
    ('MINCED_MEAT', 'Hackfleisch', ARRAY[]::text[], 'Hackfleisch', ARRAY['Hack']::text[]),
    ('MINCEMEAT', 'Mincemeat (britische Fruchtfüllung)', ARRAY[]::text[], 'Mincemeat (britische Fruchtfüllung)', ARRAY[]::text[]),
    ('MINT', 'Minze', ARRAY[]::text[], 'Minze', ARRAY[]::text[]),
    ('MIRABELLE', 'Mirabelle', ARRAY[]::text[], 'Mirabelle', ARRAY[]::text[]),
    ('MIRIN', 'Mirin', ARRAY[]::text[], 'Mirin', ARRAY[]::text[]),
    ('MISO', 'Miso', ARRAY[]::text[], 'Miso', ARRAY[]::text[]),
    ('MOLASSES', 'Melasse', ARRAY[]::text[], 'Melasse', ARRAY[]::text[]),
    ('MOLE_PASTE', 'Mole-Paste', ARRAY[]::text[], 'Mole-Paste', ARRAY[]::text[]),
    ('MOLLUSCS', 'Weichtiere', ARRAY[]::text[], 'Weichtiere', ARRAY['Mollusken']::text[]),
    ('MONKFISH', 'Seeteufel', ARRAY[]::text[], 'Seeteufel', ARRAY['Lotte']::text[]),
    ('MOOSE', 'Elchfleisch', ARRAY[]::text[], 'Elchfleisch', ARRAY[]::text[]),
    ('MORCILLA', 'Morcilla', ARRAY[]::text[], 'Morcilla', ARRAY[]::text[]),
    ('MOREL', 'Morcheln', ARRAY[]::text[], 'Morcheln', ARRAY[]::text[]),
    ('MORINGA_LEAVES', 'Moringablätter oder Malunggay', ARRAY[]::text[], 'Moringablätter', ARRAY['Malunggay']::text[]),
    ('MOZZARELLA', 'Mozzarella', ARRAY[]::text[], 'Mozzarella', ARRAY[]::text[]),
    ('MSG', 'Mononatriumglutamat', ARRAY[]::text[], 'Mononatriumglutamat', ARRAY['MSG']::text[]),
    ('MULBERRY', 'Maulbeeren', ARRAY[]::text[], 'Maulbeeren', ARRAY[]::text[]),
    ('MUNG_BEANS', 'Mungbohnen', ARRAY[]::text[], 'Mungbohnen', ARRAY['Mungobohnen']::text[]),
    ('MUOI_TOM', 'Muối tôm', ARRAY[]::text[], 'Muối tôm', ARRAY[]::text[]),
    ('MUSHROOMS', 'Pilze', ARRAY[]::text[], 'Pilze', ARRAY[]::text[]),
    ('MUSHROOM_STOCK', 'Pilzfond', ARRAY[]::text[], 'Pilzfond', ARRAY[]::text[]),
    ('MUSSELS', 'Miesmuscheln', ARRAY[]::text[], 'Miesmuscheln', ARRAY[]::text[]),
    ('MUSTARD', 'Senf', ARRAY[]::text[], 'Senf', ARRAY[]::text[]),
    ('MUSTARD_SEED', 'Senfsaat', ARRAY[]::text[], 'Senfsaat', ARRAY['Senfsamen']::text[]),
    ('MUTTON', 'Mutton (Fleisch ausgewachsener Schafe)', ARRAY[]::text[], 'Schaf', ARRAY[]::text[]),
    ('MUTTON_CHOP', 'Mutton-Kotelett', ARRAY[]::text[], 'Schafkotelett', ARRAY[]::text[]),
    ('MUTTON_LEG', 'Mutton-Keule', ARRAY[]::text[], 'Schafkeule', ARRAY[]::text[]),
    ('MUTTON_MINCE', 'Mutton-Hackfleisch', ARRAY[]::text[], 'Schafhackfleisch', ARRAY[]::text[]),
    ('MUTTON_SHOULDER', 'Mutton-Schulter', ARRAY[]::text[], 'Schafschulter', ARRAY[]::text[]),
    ('MYCOPROTEIN', 'Mykoprotein', ARRAY[]::text[], 'Mykoprotein', ARRAY[]::text[]),
    ('NAM_PRIK_PAO', 'Nam Prik Pao', ARRAY[]::text[], 'Nam Prik Pao', ARRAY[]::text[]),
    ('NAPA_CABBAGE', 'Chinakohl', ARRAY[]::text[], 'Chinakohl', ARRAY[]::text[]),
    ('NATA_DE_COCO', 'Nata de coco', ARRAY[]::text[], 'Nata de coco', ARRAY[]::text[]),
    ('NATTO', 'Nattō', ARRAY[]::text[], 'Nattō', ARRAY['Natto']::text[]),
    ('NDUJA', '’Nduja', ARRAY[]::text[], '’Nduja', ARRAY['Nduja']::text[]),
    ('NECTARINE', 'Nektarine', ARRAY[]::text[], 'Nektarine', ARRAY[]::text[]),
    ('NEUTRAL_OIL', 'neutrales Pflanzenöl', ARRAY[]::text[], 'neutrales Pflanzenöl', ARRAY[]::text[]),
    ('NEW_POTATOES', 'Frühkartoffeln', ARRAY[]::text[], 'Frühkartoffeln', ARRAY[]::text[]),
    ('NIPA_PALM_VINEGAR', 'Nipapalmenessig', ARRAY[]::text[], 'Nipapalmenessig', ARRAY[]::text[]),
    ('NOODLES', 'Nudeln', ARRAY[]::text[], 'Nudeln', ARRAY[]::text[]),
    ('NORA_PEPPER', 'Ñora-Paprika', ARRAY[]::text[], 'Ñora-Paprika', ARRAY[]::text[]),
    ('NORI', 'Nori', ARRAY[]::text[], 'Nori', ARRAY[]::text[]),
    ('NORTHERN_PRAWN', 'Eismeergarnele', ARRAY[]::text[], 'Eismeergarnele', ARRAY['Nordische Garnele']::text[]),
    ('NORTH_SEA_SHRIMP', 'Nordseekrabbe', ARRAY[]::text[], 'Nordseekrabbe', ARRAY['Nordseegarnele']::text[]),
    ('NORWEGIAN_WAFFLE', 'Norwegische Waffel', ARRAY[]::text[], 'Norwegische Waffel', ARRAY[]::text[]),
    ('NUTMEG', 'Muskatnuss', ARRAY[]::text[], 'Muskatnuss', ARRAY[]::text[]),
    ('NUTRITIONAL_YEAST', 'Hefeflocken', ARRAY[]::text[], 'Hefeflocken', ARRAY[]::text[]),
    ('NUTS', 'Nüsse', ARRAY[]::text[], 'Nüsse', ARRAY[]::text[]),
    ('NUT_AND_SEED_PASTES', 'Nuss- oder Samenpaste', ARRAY[]::text[], 'Nuss- oder Samenpaste', ARRAY[]::text[]),
    ('OATS', 'Hafer', ARRAY[]::text[], 'Hafer', ARRAY[]::text[]),
    ('OAT_DRINK', 'Haferdrink', ARRAY[]::text[], 'Hafermilch', ARRAY['Haferdrink']::text[]),
    ('OCTOPUS', 'Oktopus', ARRAY[]::text[], 'Oktopus', ARRAY['Krake', 'Pulpo']::text[]),
    ('OFFAL', 'Innereien', ARRAY[]::text[], 'Innereien', ARRAY[]::text[]),
    ('OILS', 'Speiseöl', ARRAY[]::text[], 'Speiseöl', ARRAY[]::text[]),
    ('OILY_FISH', 'fettreicher Fisch', ARRAY[]::text[], 'fettreicher Fisch', ARRAY[]::text[]),
    ('OKRA', 'Okra', ARRAY[]::text[], 'Okra', ARRAY[]::text[]),
    ('OLIVES', 'Oliven', ARRAY[]::text[], 'Oliven', ARRAY[]::text[]),
    ('OLIVE_OIL', 'Olivenöl', ARRAY[]::text[], 'Olivenöl', ARRAY[]::text[]),
    ('OLOMOUC_TVARUZKY', 'Olmützer Quargel', ARRAY[]::text[], 'Olmützer Quargel', ARRAY['Olomoucké tvarůžky']::text[]),
    ('ONION', 'Zwiebel', ARRAY[]::text[], 'Zwiebel', ARRAY[]::text[]),
    ('ONION_POWDER', 'Zwiebelpulver', ARRAY[]::text[], 'Zwiebelpulver', ARRAY[]::text[]),
    ('OOLONG_TEA', 'Oolongtee', ARRAY[]::text[], 'Oolongtee', ARRAY[]::text[]),
    ('ORANGE', 'Orange', ARRAY[]::text[], 'Orange', ARRAY['Apfelsine']::text[]),
    ('OREGANO', 'Oregano', ARRAY[]::text[], 'Oregano', ARRAY['Dost', 'Wilder Majoran']::text[]),
    ('ORZO', 'Kritharaki oder Orzo', ARRAY[]::text[], 'Orzo', ARRAY['Kritharaki', 'Risoni']::text[]),
    ('OXTAIL', 'Ochsenschwanz', ARRAY[]::text[], 'Ochsenschwanz', ARRAY[]::text[]),
    ('OYSTER', 'Austern', ARRAY[]::text[], 'Austern', ARRAY[]::text[]),
    ('OYSTER_MUSHROOM', 'Austernpilze', ARRAY[]::text[], 'Austernpilze', ARRAY['Austernseitlinge']::text[]),
    ('OYSTER_SAUCE', 'Austernsauce', ARRAY[]::text[], 'Austernsauce', ARRAY[]::text[]),
    ('PADRON_PEPPER', 'Padrón-Paprika', ARRAY[]::text[], 'Padrón-Paprika', ARRAY[]::text[]),
    ('PAK_CHOI', 'Pak Choi', ARRAY[]::text[], 'Pak Choi', ARRAY['Bok Choy']::text[]),
    ('PALM_SUGAR', 'Palmzucker', ARRAY[]::text[], 'Palmzucker', ARRAY[]::text[]),
    ('PANCETTA', 'Pancetta', ARRAY[]::text[], 'Pancetta', ARRAY[]::text[]),
    ('PANDAN_LEAVES', 'Pandanblätter', ARRAY[]::text[], 'Pandanblätter', ARRAY[]::text[]),
    ('PANEER', 'Paneer', ARRAY[]::text[], 'Paneer', ARRAY['Panir']::text[]),
    ('PANGASIUS', 'Pangasius', ARRAY[]::text[], 'Pangasius', ARRAY[]::text[]),
    ('PANKO', 'Panko', ARRAY[]::text[], 'Panko', ARRAY[]::text[]),
    ('PAPAYA', 'Papaya', ARRAY[]::text[], 'Papaya', ARRAY[]::text[]),
    ('PAPRIKA_POWDER', 'Paprikapulver', ARRAY[]::text[], 'Paprikapulver', ARRAY[]::text[]),
    ('PARMESAN', 'Parmesan', ARRAY[]::text[], 'Parmesan', ARRAY[]::text[]),
    ('PARSLEY', 'Petersilie', ARRAY[]::text[], 'Petersilie', ARRAY[]::text[]),
    ('PARSLEY_ROOT', 'Petersilienwurzel', ARRAY[]::text[], 'Petersilienwurzel', ARRAY['Wurzelpetersilie']::text[]),
    ('PARSNIP', 'Pastinake', ARRAY[]::text[], 'Pastinake', ARRAY[]::text[]),
    ('PASSION_FRUIT', 'Passionsfrucht', ARRAY[]::text[], 'Passionsfrucht', ARRAY[]::text[]),
    ('PASTIS', 'Pastis', ARRAY[]::text[], 'Pastis', ARRAY[]::text[]),
    ('PEACH', 'Pfirsich', ARRAY[]::text[], 'Pfirsich', ARRAY[]::text[]),
    ('PEANUT', 'Erdnüsse', ARRAY[]::text[], 'Erdnüsse', ARRAY[]::text[]),
    ('PEANUT_BUTTER', 'Erdnussbutter', ARRAY[]::text[], 'Erdnussbutter', ARRAY[]::text[]),
    ('PEANUT_SATAY_SAUCE', 'Erdnuss-Satay-Sauce', ARRAY[]::text[], 'Erdnuss-Satay-Sauce', ARRAY['Pindasaus']::text[]),
    ('PEAR', 'Birne', ARRAY[]::text[], 'Birne', ARRAY[]::text[]),
    ('PEARL_BARLEY', 'Graupen', ARRAY[]::text[], 'Gerstengraupen', ARRAY[]::text[]),
    ('PEAS', 'Erbsen', ARRAY[]::text[], 'Erbsen', ARRAY[]::text[]),
    ('PEA_EGGPLANT', 'Erbsenaubergine', ARRAY[]::text[], 'Erbsenaubergine', ARRAY[]::text[]),
    ('PECAN', 'Pekannüsse', ARRAY[]::text[], 'Pekannüsse', ARRAY[]::text[]),
    ('PECORINO', 'Pecorino', ARRAY[]::text[], 'Pecorino', ARRAY[]::text[]),
    ('PENNE', 'Penne', ARRAY[]::text[], 'Penne', ARRAY[]::text[]),
    ('PEPPER', 'Pfeffer', ARRAY[]::text[], 'Pfeffer', ARRAY[]::text[]),
    ('PERILLA_LEAVES', 'Perillablätter', ARRAY[]::text[], 'Perillablätter', ARRAY[]::text[]),
    ('PERSIMMON', 'Kaki', ARRAY[]::text[], 'Kaki', ARRAY[]::text[]),
    ('PESTO', 'Pesto', ARRAY[]::text[], 'Pesto', ARRAY[]::text[]),
    ('PICKLED_CHILI', 'eingelegte Chili', ARRAY[]::text[], 'eingelegte Chili', ARRAY[]::text[]),
    ('PICKLED_CUCUMBER', 'Gewürzgurke', ARRAY[]::text[], 'Gewürzgurke', ARRAY['Essiggurke']::text[]),
    ('PICKLED_GINGER', 'eingelegter Ingwer', ARRAY[]::text[], 'eingelegter Ingwer', ARRAY['Gari']::text[]),
    ('PICKLED_HERRING', 'eingelegter Hering', ARRAY[]::text[], 'eingelegter Hering', ARRAY[]::text[]),
    ('PICKLED_MUSHROOMS', 'eingelegte Pilze', ARRAY[]::text[], 'eingelegte Pilze', ARRAY[]::text[]),
    ('PICKLED_SAUSAGE', 'eingelegte Wurst', ARRAY[]::text[], 'eingelegte Wurst', ARRAY[]::text[]),
    ('PIKEPERCH', 'Zander', ARRAY[]::text[], 'Zander', ARRAY[]::text[]),
    ('PILSNER_LAGER', 'Pilsner', ARRAY[]::text[], 'Pilsner', ARRAY['Pils']::text[]),
    ('PIMENT_D_ESPELETTE', 'Piment d’Espelette', ARRAY[]::text[], 'Piment d’Espelette', ARRAY[]::text[]),
    ('PINEAPPLE', 'Ananas', ARRAY[]::text[], 'Ananas', ARRAY[]::text[]),
    ('PINE_NUT', 'Pinienkerne', ARRAY[]::text[], 'Pinienkerne', ARRAY[]::text[]),
    ('PINNEKJOTT', 'Pinnekjøtt', ARRAY[]::text[], 'Pinnekjøtt', ARRAY[]::text[]),
    ('PINTO_BEANS', 'Pintobohnen', ARRAY[]::text[], 'Pintobohnen', ARRAY['Wachtelbohnen']::text[]),
    ('PIQUILLO_PEPPER', 'Piquillo-Paprika', ARRAY[]::text[], 'Piquillo-Paprika', ARRAY[]::text[]),
    ('PISTACHIO', 'Pistazien', ARRAY[]::text[], 'Pistazien', ARRAY[]::text[]),
    ('PITA', 'Pita', ARRAY[]::text[], 'Pita', ARRAY[]::text[]),
    ('PLAICE', 'Scholle', ARRAY[]::text[], 'Scholle', ARRAY[]::text[]),
    ('PLANTAIN', 'Kochbanane', ARRAY[]::text[], 'Kochbanane', ARRAY[]::text[]),
    ('PLANT_DRINKS', 'pflanzlicher Drink', ARRAY[]::text[], 'pflanzlicher Drink', ARRAY[]::text[]),
    ('PLANT_PROTEIN_PRODUCTS', 'pflanzliches Proteinprodukt', ARRAY[]::text[], 'pflanzliches Proteinprodukt', ARRAY[]::text[]),
    ('PLA_RA', 'Pla Ra', ARRAY[]::text[], 'Pla Ra', ARRAY[]::text[]),
    ('PLUM', 'Pflaume', ARRAY[]::text[], 'Pflaume', ARRAY[]::text[]),
    ('PLUM_BUTTER', 'Pflaumenmus', ARRAY[]::text[], 'Pflaumenmus', ARRAY['Powidl']::text[]),
    ('POBLANO', 'Poblano', ARRAY[]::text[], 'Poblano', ARRAY[]::text[]),
    ('POD_VEGETABLES', 'Hülsen- und Schotengemüse', ARRAY[]::text[], 'Hülsen- und Schotengemüse', ARRAY[]::text[]),
    ('POINTED_CABBAGE', 'Spitzkohl', ARRAY[]::text[], 'Spitzkohl', ARRAY[]::text[]),
    ('POLENTA', 'Polenta', ARRAY[]::text[], 'Polenta', ARRAY[]::text[]),
    ('POLLOCK', 'Köhler (Seelachs)', ARRAY[]::text[], 'Seelachs', ARRAY['Köhler']::text[]),
    ('POMEGRANATE', 'Granatapfel', ARRAY[]::text[], 'Granatapfel', ARRAY[]::text[]),
    ('POMEGRANATE_MOLASSES', 'Granatapfelmelasse', ARRAY[]::text[], 'Granatapfelmelasse', ARRAY[]::text[]),
    ('POMELO', 'Pomelo', ARRAY[]::text[], 'Pomelo', ARRAY[]::text[]),
    ('POME_FRUIT', 'Kernobst', ARRAY[]::text[], 'Kernobst', ARRAY[]::text[]),
    ('PONZU', 'Ponzu', ARRAY[]::text[], 'Ponzu', ARRAY[]::text[]),
    ('POPPY_SEEDS', 'Mohn', ARRAY[]::text[], 'Mohn', ARRAY[]::text[]),
    ('PORCINI', 'Steinpilze', ARRAY[]::text[], 'Steinpilze', ARRAY[]::text[]),
    ('PORK', 'Schweinefleisch', ARRAY[]::text[], 'Schweinefleisch', ARRAY[]::text[]),
    ('PORK_BELLY', 'Schweinebauch', ARRAY[]::text[], 'Schweinebauch', ARRAY[]::text[]),
    ('PORK_CHEEK', 'Schweinebäckchen', ARRAY[]::text[], 'Schweinebäckchen', ARRAY[]::text[]),
    ('PORK_CHOP', 'Schweinekotelett', ARRAY[]::text[], 'Schweinekotelett', ARRAY[]::text[]),
    ('PORK_CRACKLINGS', 'Schweinegrieben', ARRAY[]::text[], 'Schweinegrieben', ARRAY[]::text[]),
    ('PORK_CUTLET', 'Schweineschnitzel', ARRAY[]::text[], 'Schweineschnitzel', ARRAY[]::text[]),
    ('PORK_KNUCKLE', 'Schweinshaxe', ARRAY[]::text[], 'Schweinshaxe', ARRAY[]::text[]),
    ('PORK_LIVER', 'Schweineleber', ARRAY[]::text[], 'Schweineleber', ARRAY[]::text[]),
    ('PORK_LOIN', 'Schweinerücken', ARRAY[]::text[], 'Schweinerücken', ARRAY[]::text[]),
    ('PORK_MINCE', 'Schweinehack', ARRAY[]::text[], 'Schweinehack', ARRAY['Schweinehackfleisch']::text[]),
    ('PORK_NECK', 'Schweinenacken', ARRAY[]::text[], 'Schweinenacken', ARRAY['Schweinekamm']::text[]),
    ('PORK_RIBS', 'Schweinerippchen', ARRAY[]::text[], 'Schweinerippchen', ARRAY[]::text[]),
    ('PORK_SHOULDER', 'Schweineschulter', ARRAY[]::text[], 'Schweineschulter', ARRAY['Schweinebug']::text[]),
    ('PORK_STOCK', 'Schweinefond', ARRAY[]::text[], 'Schweinefond', ARRAY[]::text[]),
    ('PORK_TENDERLOIN', 'Schweinefilet', ARRAY[]::text[], 'Schweinefilet', ARRAY[]::text[]),
    ('PORK_TONGUE', 'Schweinezunge', ARRAY[]::text[], 'Schweinezunge', ARRAY[]::text[]),
    ('PORT_WINE', 'Portwein', ARRAY[]::text[], 'Portwein', ARRAY[]::text[]),
    ('POTATO', 'Kartoffel', ARRAY[]::text[], 'Kartoffel', ARRAY[]::text[]),
    ('POTATO_DUMPLING', 'Kartoffelknödel', ARRAY[]::text[], 'Kartoffelknödel', ARRAY['Kartoffelkloß']::text[]),
    ('POTATO_STARCH', 'Kartoffelstärke', ARRAY[]::text[], 'Kartoffelstärke', ARRAY[]::text[]),
    ('POULTRY', 'Geflügel', ARRAY[]::text[], 'Geflügel', ARRAY[]::text[]),
    ('PRESERVED_FISH', 'konservierter Fisch', ARRAY[]::text[], 'konservierter Fisch', ARRAY[]::text[]),
    ('PRESERVED_LEMON', 'Salzzitrone', ARRAY[]::text[], 'Salzzitrone', ARRAY[]::text[]),
    ('PRESERVED_PRODUCE', 'konservierte pflanzliche Zutat', ARRAY[]::text[], 'konservierte pflanzliche Zutat', ARRAY[]::text[]),
    ('PRETZEL', 'Laugenbrezel', ARRAY[]::text[], 'Laugenbrezel', ARRAY[]::text[]),
    ('PROSCIUTTO', 'Prosciutto', ARRAY[]::text[], 'Prosciutto crudo', ARRAY[]::text[]),
    ('PRUNE', 'Trockenpflaumen', ARRAY[]::text[], 'Trockenpflaumen', ARRAY['Dörrpflaumen']::text[]),
    ('PUL_BIBER', 'Pul Biber', ARRAY[]::text[], 'Pul Biber', ARRAY[]::text[]),
    ('PUMPERNICKEL', 'Pumpernickel', ARRAY[]::text[], 'Pumpernickel', ARRAY[]::text[]),
    ('PUMPKIN', 'Kürbis', ARRAY[]::text[], 'Kürbis', ARRAY[]::text[]),
    ('PUMPKIN_SEEDS', 'Kürbiskerne', ARRAY[]::text[], 'Kürbiskerne', ARRAY[]::text[]),
    ('PUMPKIN_SEED_OIL', 'Kürbiskernöl', ARRAY[]::text[], 'Kürbiskernöl', ARRAY[]::text[]),
    ('PURSLANE', 'Portulak', ARRAY[]::text[], 'Portulak', ARRAY[]::text[]),
    ('QUAIL', 'Wachtel', ARRAY[]::text[], 'Wachtel', ARRAY[]::text[]),
    ('QUAIL_EGG', 'Wachtelei', ARRAY[]::text[], 'Wachtelei', ARRAY[]::text[]),
    ('QUARK', 'Quark', ARRAY[]::text[], 'Quark', ARRAY['Topfen']::text[]),
    ('QUINCE', 'Quitte', ARRAY[]::text[], 'Quitte', ARRAY[]::text[]),
    ('QUINOA', 'Quinoa', ARRAY[]::text[], 'Quinoa', ARRAY[]::text[]),
    ('RABBIT', 'Kaninchen', ARRAY[]::text[], 'Kaninchen', ARRAY[]::text[]),
    ('RADICCHIO', 'Radicchio', ARRAY[]::text[], 'Radicchio', ARRAY[]::text[]),
    ('RADISH', 'Rettich', ARRAY[]::text[], 'Rettich', ARRAY[]::text[]),
    ('RAISIN', 'Rosinen', ARRAY[]::text[], 'Rosinen', ARRAY[]::text[]),
    ('RAKFISK', 'Rakfisk', ARRAY[]::text[], 'Rakfisk', ARRAY[]::text[]),
    ('RAMEN_NOODLES', 'Ramennudeln', ARRAY[]::text[], 'Ramennudeln', ARRAY[]::text[]),
    ('RASPBERRY', 'Himbeere', ARRAY[]::text[], 'Himbeere', ARRAY[]::text[]),
    ('RAS_EL_HANOUT', 'Ras el-Hanout', ARRAY[]::text[], 'Ras el-Hanout', ARRAY[]::text[]),
    ('RAZOR_CLAMS', 'Schwertmuscheln', ARRAY[]::text[], 'Schwertmuscheln', ARRAY['Scheidenmuscheln']::text[]),
    ('READY_CURRY_PASTE', 'fertige Currypaste', ARRAY[]::text[], 'fertige Currypaste', ARRAY[]::text[]),
    ('READY_SAUCES_AND_PASTES', 'fertige Sauce oder Würzpaste', ARRAY[]::text[], 'fertige Sauce oder Würzpaste', ARRAY[]::text[]),
    ('REDFISH', 'Rotbarsch', ARRAY[]::text[], 'Rotbarsch', ARRAY[]::text[]),
    ('RED_BELL_PEPPER', 'rote Paprika', ARRAY[]::text[], 'rote Paprika', ARRAY[]::text[]),
    ('RED_CABBAGE', 'Rotkohl', ARRAY[]::text[], 'Rotkohl', ARRAY['Blaukraut', 'Rotkraut']::text[]),
    ('RED_CURRANT', 'rote Johannisbeere', ARRAY[]::text[], 'rote Johannisbeere', ARRAY[]::text[]),
    ('RED_LENTILS', 'rote Linsen', ARRAY[]::text[], 'rote Linsen', ARRAY[]::text[]),
    ('RED_ONION', 'rote Zwiebel', ARRAY[]::text[], 'rote Zwiebel', ARRAY[]::text[]),
    ('RED_WINE', 'Rotwein', ARRAY[]::text[], 'Rotwein', ARRAY[]::text[]),
    ('RED_WINE_VINEGAR', 'Rotweinessig', ARRAY[]::text[], 'Rotweinessig', ARRAY[]::text[]),
    ('REINDEER', 'Rentierfleisch', ARRAY[]::text[], 'Rentierfleisch', ARRAY[]::text[]),
    ('REMOULADE', 'Remoulade', ARRAY[]::text[], 'Remoulade', ARRAY[]::text[]),
    ('RENDANG_PASTE', 'Rendang-Paste', ARRAY[]::text[], 'Rendang-Paste', ARRAY[]::text[]),
    ('RHUBARB', 'Rhabarber', ARRAY[]::text[], 'Rhabarber', ARRAY[]::text[]),
    ('RICE', 'Reis', ARRAY[]::text[], 'Reis', ARRAY[]::text[]),
    ('RICE_CAKES', 'koreanische Reiskuchen', ARRAY[]::text[], 'Tteok', ARRAY['Koreanische Reiskuchen']::text[]),
    ('RICE_FLOUR', 'Reismehl', ARRAY[]::text[], 'Reismehl', ARRAY[]::text[]),
    ('RICE_NOODLES', 'Reisnudeln', ARRAY[]::text[], 'Reisnudeln', ARRAY[]::text[]),
    ('RICE_PADDY_HERB', 'Reisfeldkraut', ARRAY[]::text[], 'Reisfeldkraut', ARRAY[]::text[]),
    ('RICE_PAPER', 'Reispapier', ARRAY[]::text[], 'Reispapier', ARRAY[]::text[]),
    ('RICE_PRODUCTS', 'Reisprodukt', ARRAY[]::text[], 'Reisprodukt', ARRAY[]::text[]),
    ('RICE_VINEGAR', 'Reisessig', ARRAY[]::text[], 'Reisessig', ARRAY[]::text[]),
    ('RICOTTA', 'Ricotta', ARRAY[]::text[], 'Ricotta', ARRAY[]::text[]),
    ('RILLETTES', 'Rillettes', ARRAY[]::text[], 'Rillettes', ARRAY[]::text[]),
    ('RISOTTO_RICE', 'Risottoreis', ARRAY[]::text[], 'Risottoreis', ARRAY[]::text[]),
    ('ROASTED_PUMPKIN_SEED_OIL', 'Kürbiskernöl, geröstet', ARRAY[]::text[], 'Kürbiskernöl, geröstet', ARRAY[]::text[]),
    ('ROASTED_RED_PEPPER', 'geröstete Paprika', ARRAY[]::text[], 'geröstete Paprika', ARRAY[]::text[]),
    ('ROD_POLSE', 'Rød pølse', ARRAY[]::text[], 'Rød pølse', ARRAY[]::text[]),
    ('ROMAINE_LETTUCE', 'Römersalat', ARRAY[]::text[], 'Römersalat', ARRAY['Romanasalat', 'Römischer Salat']::text[]),
    ('ROMANESCO', 'Romanesco', ARRAY[]::text[], 'Romanesco', ARRAY[]::text[]),
    ('ROMESCO', 'Romesco-Sauce', ARRAY[]::text[], 'Romesco-Sauce', ARRAY['Romesco']::text[]),
    ('ROOKWORST', 'Rookworst', ARRAY[]::text[], 'Rookworst', ARRAY[]::text[]),
    ('ROOT_VEGETABLES', 'Wurzel- und Knollengemüse', ARRAY[]::text[], 'Wurzel- und Knollengemüse', ARRAY[]::text[]),
    ('ROQUEFORT', 'Roquefort', ARRAY[]::text[], 'Roquefort', ARRAY[]::text[]),
    ('ROSEMARY', 'Rosmarin', ARRAY[]::text[], 'Rosmarin', ARRAY[]::text[]),
    ('RUM', 'Rum', ARRAY[]::text[], 'Rum', ARRAY[]::text[]),
    ('RUNNER_BEANS', 'Käferbohnen', ARRAY[]::text[], 'Käferbohnen', ARRAY[]::text[]),
    ('RUTABAGA', 'Steckrübe', ARRAY[]::text[], 'Steckrübe', ARRAY['Kohlrübe']::text[]),
    ('RYE_BREAD', 'Roggenbrot', ARRAY[]::text[], 'Roggenbrot', ARRAY[]::text[]),
    ('RYE_FLOUR', 'Roggenmehl', ARRAY[]::text[], 'Roggenmehl', ARRAY[]::text[]),
    ('SAFFRON', 'Safran', ARRAY[]::text[], 'Safran', ARRAY[]::text[]),
    ('SAGE', 'Salbei', ARRAY[]::text[], 'Salbei', ARRAY[]::text[]),
    ('SAHTI', 'Sahti', ARRAY[]::text[], 'Sahti', ARRAY[]::text[]),
    ('SAI_UA', 'Sai Ua', ARRAY[]::text[], 'Sai Ua', ARRAY[]::text[]),
    ('SAKE', 'Sake', ARRAY[]::text[], 'Sake', ARRAY[]::text[]),
    ('SALAD_GREENS', 'Blattsalat', ARRAY[]::text[], 'Blattsalat', ARRAY[]::text[]),
    ('SALAMI', 'Salami', ARRAY[]::text[], 'Salami', ARRAY[]::text[]),
    ('SALMON', 'Lachs', ARRAY[]::text[], 'Lachs', ARRAY[]::text[]),
    ('SALMON_ROE', 'Lachsrogen', ARRAY[]::text[], 'Lachsrogen', ARRAY[]::text[]),
    ('SALSA', 'Salsa', ARRAY[]::text[], 'Salsa', ARRAY[]::text[]),
    ('SALTED_DUCK_EGG', 'gesalzenes Entenei', ARRAY[]::text[], 'gesalzenes Entenei', ARRAY[]::text[]),
    ('SALTY_LIQUORICE', 'Salzlakritz', ARRAY[]::text[], 'Salzlakritz', ARRAY[]::text[]),
    ('SAMBAL', 'Sambal', ARRAY[]::text[], 'Sambal', ARRAY[]::text[]),
    ('SAMBAL_BRANDAL', 'Sambal Brandal', ARRAY[]::text[], 'Sambal Brandal', ARRAY[]::text[]),
    ('SAMBAL_OELEK', 'Sambal Oelek', ARRAY[]::text[], 'Sambal Oelek', ARRAY['Sambal Ulek']::text[]),
    ('SARDINES', 'Sardinen', ARRAY[]::text[], 'Sardinen', ARRAY[]::text[]),
    ('SAUCES_AND_PASTES', 'Sauce, Würzmittel oder Paste', ARRAY[]::text[], 'Sauce, Würzmittel oder Paste', ARRAY[]::text[]),
    ('SAUERKRAUT', 'Sauerkraut', ARRAY[]::text[], 'Sauerkraut', ARRAY[]::text[]),
    ('SAUSAGE', 'Wurst', ARRAY[]::text[], 'Wurst', ARRAY[]::text[]),
    ('SAVOY_CABBAGE', 'Wirsing', ARRAY[]::text[], 'Wirsing', ARRAY['Wirsingkohl']::text[]),
    ('SCALLOPS', 'Jakobsmuscheln', ARRAY[]::text[], 'Jakobsmuscheln', ARRAY[]::text[]),
    ('SCOTTISH_OATCAKES', 'schottische Oatcakes', ARRAY[]::text[], 'schottische Oatcakes', ARRAY[]::text[]),
    ('SEAFOOD', 'Fisch und Meeresfrüchte', ARRAY[]::text[], 'Fisch und Meeresfrüchte', ARRAY[]::text[]),
    ('SEAWEED', 'Algen', ARRAY[]::text[], 'Algen', ARRAY[]::text[]),
    ('SEA_BASS', 'Wolfsbarsch', ARRAY[]::text[], 'Wolfsbarsch', ARRAY['Loup de mer']::text[]),
    ('SEA_BREAM', 'Dorade', ARRAY[]::text[], 'Dorade', ARRAY[]::text[]),
    ('SEA_BUCKTHORN', 'Sanddornbeeren', ARRAY[]::text[], 'Sanddorn', ARRAY[]::text[]),
    ('SEA_SNAILS', 'Meeresschnecken', ARRAY[]::text[], 'Meeresschnecken', ARRAY[]::text[]),
    ('SEEDS', 'Kerne und Samen', ARRAY[]::text[], 'Kerne und Samen', ARRAY[]::text[]),
    ('SEITAN', 'Seitan', ARRAY[]::text[], 'Seitan', ARRAY[]::text[]),
    ('SEMOLINA', 'Hartweizengrieß', ARRAY[]::text[], 'Hartweizengrieß', ARRAY[]::text[]),
    ('SERRANO_CHILI', 'Serrano-Chili', ARRAY[]::text[], 'Serrano-Chili', ARRAY[]::text[]),
    ('SERRANO_HAM', 'Serrano-Schinken', ARRAY[]::text[], 'Serrano-Schinken', ARRAY['Jamón serrano']::text[]),
    ('SESAME_OIL', 'Sesamöl', ARRAY[]::text[], 'Sesamöl', ARRAY[]::text[]),
    ('SESAME_SEEDS', 'Sesam', ARRAY[]::text[], 'Sesam', ARRAY[]::text[]),
    ('SHALLOT', 'Schalotte', ARRAY[]::text[], 'Schalotte', ARRAY[]::text[]),
    ('SHAOXING_WINE', 'Shaoxing-Reiswein', ARRAY[]::text[], 'Shaoxing-Reiswein', ARRAY[]::text[]),
    ('SHELLFISH', 'Schalen- und Krustentiere', ARRAY[]::text[], 'Schalen- und Krustentiere', ARRAY[]::text[]),
    ('SHERRY', 'Sherry', ARRAY[]::text[], 'Sherry', ARRAY[]::text[]),
    ('SHERRY_VINEGAR', 'Sherryessig', ARRAY[]::text[], 'Sherryessig', ARRAY[]::text[]),
    ('SHIITAKE', 'Shiitake', ARRAY[]::text[], 'Shiitake', ARRAY[]::text[]),
    ('SHIMEJI', 'Shimeji', ARRAY[]::text[], 'Shimeji', ARRAY[]::text[]),
    ('SHIRATAKI', 'Shirataki-Nudeln', ARRAY[]::text[], 'Shirataki-Nudeln', ARRAY['Konjaknudeln']::text[]),
    ('SHRIMP', 'Garnelen', ARRAY[]::text[], 'Garnelen', ARRAY['Shrimps']::text[]),
    ('SHRIMP_PASTE', 'Garnelenpaste', ARRAY[]::text[], 'Garnelenpaste', ARRAY[]::text[]),
    ('SICHUAN_PEPPER', 'Szechuanpfeffer', ARRAY[]::text[], 'Szechuanpfeffer', ARRAY['Sichuanpfeffer']::text[]),
    ('SILKEN_TOFU', 'Seidentofu', ARRAY[]::text[], 'Seidentofu', ARRAY[]::text[]),
    ('SLIVOVICE', 'Sliwowitz', ARRAY[]::text[], 'Sliwowitz', ARRAY['Slibowitz']::text[]),
    ('SMOKED_HADDOCK', 'geräucherter Schellfisch', ARRAY[]::text[], 'geräucherter Schellfisch', ARRAY[]::text[]),
    ('SMOKED_PAPRIKA', 'geräuchertes Paprikapulver', ARRAY[]::text[], 'geräuchertes Paprikapulver', ARRAY[]::text[]),
    ('SMOKED_SALMON', 'Räucherlachs', ARRAY[]::text[], 'Räucherlachs', ARRAY[]::text[]),
    ('SMOKED_TOFU', 'Räuchertofu', ARRAY[]::text[], 'Räuchertofu', ARRAY[]::text[]),
    ('SMOKED_TROUT', 'Räucherforelle', ARRAY[]::text[], 'Räucherforelle', ARRAY[]::text[]),
    ('SOBA', 'Soba', ARRAY[]::text[], 'Soba', ARRAY[]::text[]),
    ('SOBRASADA', 'Sobrasada', ARRAY[]::text[], 'Sobrasada', ARRAY['Sobrassada']::text[]),
    ('SOFT_WHEAT_SEMOLINA', 'Weichweizengrieß', ARRAY[]::text[], 'Weichweizengrieß', ARRAY[]::text[]),
    ('SOLE', 'Seezunge', ARRAY[]::text[], 'Seezunge', ARRAY[]::text[]),
    ('SOURDOUGH_BREAD', 'Sauerteigbrot', ARRAY[]::text[], 'Sauerteigbrot', ARRAY[]::text[]),
    ('SOUR_CHERRY', 'Sauerkirsche', ARRAY[]::text[], 'Sauerkirsche', ARRAY[]::text[]),
    ('SOUR_CREAM', 'saure Sahne', ARRAY[]::text[], 'saure Sahne', ARRAY['Sauerrahm']::text[]),
    ('SOUR_RYE_STARTER', 'Żur-Saueransatz', ARRAY[]::text[], 'Żur-Saueransatz', ARRAY[]::text[]),
    ('SOYBEANS', 'Sojabohnen', ARRAY[]::text[], 'Sojabohnen', ARRAY[]::text[]),
    ('SOY_DRINK', 'Sojadrink', ARRAY[]::text[], 'Sojamilch', ARRAY['Sojadrink']::text[]),
    ('SOY_PRODUCTS', 'Sojazutat', ARRAY[]::text[], 'Sojazutat', ARRAY[]::text[]),
    ('SOY_SAUCE', 'Sojasauce', ARRAY[]::text[], 'Sojasauce', ARRAY[]::text[]),
    ('SPAETZLE', 'Spätzle', ARRAY[]::text[], 'Spätzle', ARRAY[]::text[]),
    ('SPAGHETTI', 'Spaghetti', ARRAY[]::text[], 'Spaghetti', ARRAY[]::text[]),
    ('SPAGHETTI_SQUASH', 'Spaghettikürbis', ARRAY[]::text[], 'Spaghettikürbis', ARRAY[]::text[]),
    ('SPECULAAS_SPICE', 'Spekulatiusgewürz', ARRAY[]::text[], 'Spekulatiusgewürz', ARRAY[]::text[]),
    ('SPECULOOS', 'Spekulatius', ARRAY[]::text[], 'Spekulatius', ARRAY['Speculaas', 'Speculoos']::text[]),
    ('SPELT', 'Dinkel', ARRAY[]::text[], 'Dinkel', ARRAY[]::text[]),
    ('SPICES', 'Gewürz oder trockenes Würzmittel', ARRAY[]::text[], 'Gewürz oder trockenes Würzmittel', ARRAY[]::text[]),
    ('SPICE_BLENDS', 'Gewürzmischung', ARRAY[]::text[], 'Gewürzmischung', ARRAY[]::text[]),
    ('SPINACH', 'Spinat', ARRAY[]::text[], 'Spinat', ARRAY[]::text[]),
    ('SPLIT_PEAS', 'Spalterbsen', ARRAY[]::text[], 'Spalterbsen', ARRAY[]::text[]),
    ('SPRING_ONION', 'Frühlingszwiebel', ARRAY[]::text[], 'Frühlingszwiebel', ARRAY['Lauchzwiebel']::text[]),
    ('SPROUTS', 'Sprossen', ARRAY[]::text[], 'Sprossen', ARRAY['Keimsprossen']::text[]),
    ('SQUID', 'Tintenfisch', ARRAY[]::text[], 'Kalmar', ARRAY['Calamares', 'Calamari']::text[]),
    ('SRIRACHA', 'Sriracha', ARRAY[]::text[], 'Sriracha', ARRAY[]::text[]),
    ('STARCHES', 'stärkehaltige Zutat oder Sättigungsbeilage', ARRAY[]::text[], 'stärkehaltige Zutat oder Sättigungsbeilage', ARRAY[]::text[]),
    ('STARCH_BINDERS', 'Stärke oder Bindemittel', ARRAY[]::text[], 'Stärke oder Bindemittel', ARRAY[]::text[]),
    ('STARFRUIT', 'Sternfrucht oder Karambole', ARRAY[]::text[], 'Karambole', ARRAY['Karambola', 'Sternfrucht']::text[]),
    ('STAR_ANISE', 'Sternanis', ARRAY[]::text[], 'Sternanis', ARRAY[]::text[]),
    ('STEM_VEGETABLES', 'Stängelgemüse', ARRAY[]::text[], 'Stängelgemüse', ARRAY[]::text[]),
    ('STICKY_RICE', 'Klebreis', ARRAY[]::text[], 'Klebreis', ARRAY[]::text[]),
    ('STINKY_TOFU', 'Stinky Tofu', ARRAY[]::text[], 'Stinky Tofu', ARRAY[]::text[]),
    ('STOCKFISH', 'Stockfisch', ARRAY[]::text[], 'Stockfisch', ARRAY[]::text[]),
    ('STOCKS', 'Brühe oder Fond', ARRAY[]::text[], 'Brühe oder Fond', ARRAY[]::text[]),
    ('STONE_FRUIT', 'Steinobst', ARRAY[]::text[], 'Steinobst', ARRAY[]::text[]),
    ('STRAWBERRY', 'Erdbeere', ARRAY[]::text[], 'Erdbeere', ARRAY[]::text[]),
    ('STROOPWAFEL', 'Stroopwafel', ARRAY[]::text[], 'Stroopwafel', ARRAY[]::text[]),
    ('STRUDEL_DOUGH', 'Strudelteig', ARRAY[]::text[], 'Strudelteig', ARRAY[]::text[]),
    ('SUGARCANE_VINEGAR', 'Zuckerrohressig', ARRAY[]::text[], 'Zuckerrohressig', ARRAY[]::text[]),
    ('SUGAR_SNAP_PEAS', 'Zuckerschoten', ARRAY[]::text[], 'Zuckerschoten', ARRAY['Kaiserschote', 'Knackerbse', 'Zuckerschote']::text[]),
    ('SUMAC', 'Sumach', ARRAY[]::text[], 'Sumach', ARRAY['Sumak']::text[]),
    ('SUNFLOWER_SEEDS', 'Sonnenblumenkerne', ARRAY[]::text[], 'Sonnenblumenkerne', ARRAY[]::text[]),
    ('SUN_DRIED_TOMATO', 'getrocknete Tomaten', ARRAY[]::text[], 'getrocknete Tomaten', ARRAY[]::text[]),
    ('SURIMI', 'Surimi', ARRAY[]::text[], 'Surimi', ARRAY[]::text[]),
    ('SUSHI_RICE', 'Sushireis', ARRAY[]::text[], 'Sushireis', ARRAY[]::text[]),
    ('SWEETENERS', 'Süßungsmittel', ARRAY[]::text[], 'Süßungsmittel', ARRAY[]::text[]),
    ('SWEET_PAPRIKA_POWDER', 'Paprikapulver edelsüß', ARRAY[]::text[], 'Paprikapulver edelsüß', ARRAY[]::text[]),
    ('SWEET_POTATO', 'Süßkartoffel', ARRAY[]::text[], 'Süßkartoffel', ARRAY['Batate']::text[]),
    ('SWORDFISH', 'Schwertfisch', ARRAY[]::text[], 'Schwertfisch', ARRAY[]::text[]),
    ('SYRUP', 'Sirup', ARRAY[]::text[], 'Sirup', ARRAY[]::text[]),
    ('TABLEA', 'Tablea oder Tableya', ARRAY[]::text[], 'Tablea', ARRAY['Tableya']::text[]),
    ('TAHINI', 'Tahini', ARRAY[]::text[], 'Tahini', ARRAY['Tahin', 'Tahina']::text[]),
    ('TAI_PLA', 'Tai Pla', ARRAY[]::text[], 'Tai Pla', ARRAY[]::text[]),
    ('TAMARI', 'Tamari', ARRAY[]::text[], 'Tamari', ARRAY[]::text[]),
    ('TAMARIND', 'Tamarinde', ARRAY[]::text[], 'Tamarinde', ARRAY[]::text[]),
    ('TAPENADE', 'Tapenade', ARRAY[]::text[], 'Tapenade', ARRAY[]::text[]),
    ('TAPIOCA_STARCH', 'Tapiokastärke', ARRAY[]::text[], 'Tapiokastärke', ARRAY[]::text[]),
    ('TARO', 'Taro', ARRAY[]::text[], 'Taro', ARRAY[]::text[]),
    ('TARRAGON', 'Estragon', ARRAY[]::text[], 'Estragon', ARRAY[]::text[]),
    ('TEA', 'Tee', ARRAY[]::text[], 'Tee', ARRAY[]::text[]),
    ('TEMPEH', 'Tempeh', ARRAY[]::text[], 'Tempeh', ARRAY[]::text[]),
    ('TERIYAKI_SAUCE', 'Teriyakisauce', ARRAY[]::text[], 'Teriyakisauce', ARRAY[]::text[]),
    ('THAI_BASIL', 'Thai-Basilikum', ARRAY[]::text[], 'Thai-Basilikum', ARRAY[]::text[]),
    ('THAI_EGGPLANT', 'Thai-Aubergine', ARRAY[]::text[], 'Thai-Aubergine', ARRAY[]::text[]),
    ('THAI_GREEN_CURRY_PASTE', 'grüne Thai-Currypaste', ARRAY[]::text[], 'grüne Thai-Currypaste', ARRAY[]::text[]),
    ('THAI_RED_CURRY_PASTE', 'rote Thai-Currypaste', ARRAY[]::text[], 'rote Thai-Currypaste', ARRAY[]::text[]),
    ('THAI_YELLOW_CURRY_PASTE', 'gelbe Thai-Currypaste', ARRAY[]::text[], 'gelbe Thai-Currypaste', ARRAY[]::text[]),
    ('THYME', 'Thymian', ARRAY[]::text[], 'Thymian', ARRAY[]::text[]),
    ('TIROLER_GRAUKAESE', 'Tiroler Graukäse', ARRAY[]::text[], 'Tiroler Graukäse', ARRAY[]::text[]),
    ('TIROLER_SPECK', 'Tiroler Speck', ARRAY[]::text[], 'Tiroler Speck', ARRAY[]::text[]),
    ('TOFU', 'Tofu', ARRAY[]::text[], 'Tofu', ARRAY['Sojabohnenquark']::text[]),
    ('TOMATILLO', 'Tomatillo', ARRAY[]::text[], 'Tomatillo', ARRAY[]::text[]),
    ('TOMATO', 'Tomate', ARRAY[]::text[], 'Tomate', ARRAY[]::text[]),
    ('TOMATO_PASSATA', 'passierte Tomaten', ARRAY[]::text[], 'passierte Tomaten', ARRAY['Passata']::text[]),
    ('TOMATO_PASTE', 'Tomatenmark', ARRAY[]::text[], 'Tomatenmark', ARRAY[]::text[]),
    ('TOMATO_PRODUCTS', 'Tomatenprodukt', ARRAY[]::text[], 'Tomatenprodukt', ARRAY[]::text[]),
    ('TOMATO_SAUCE', 'einfache Tomatensauce', ARRAY[]::text[], 'einfache Tomatensauce', ARRAY[]::text[]),
    ('TORTILLA', 'Tortilla', ARRAY[]::text[], 'Tortilla', ARRAY[]::text[]),
    ('TRIPE', 'Kutteln', ARRAY[]::text[], 'Kutteln', ARRAY[]::text[]),
    ('TROPICAL_FRUIT', 'Tropenfrucht', ARRAY[]::text[], 'Tropenfrucht', ARRAY[]::text[]),
    ('TROUT', 'Forelle', ARRAY[]::text[], 'Forelle', ARRAY[]::text[]),
    ('TROUT_ROE', 'Forellenrogen', ARRAY[]::text[], 'Forellenrogen', ARRAY[]::text[]),
    ('TRUFFLE', 'Trüffel', ARRAY[]::text[], 'Trüffel', ARRAY[]::text[]),
    ('TUNA', 'Thunfisch', ARRAY[]::text[], 'Thunfisch', ARRAY[]::text[]),
    ('TURKEY', 'Pute', ARRAY[]::text[], 'Pute', ARRAY['Truthahn']::text[]),
    ('TURKEY_BREAST', 'Putenbrust', ARRAY[]::text[], 'Putenbrust', ARRAY[]::text[]),
    ('TURKEY_MINCE', 'Putenhack', ARRAY[]::text[], 'Putenhack', ARRAY['Putenhackfleisch']::text[]),
    ('TURMERIC', 'Kurkuma', ARRAY[]::text[], 'Kurkuma', ARRAY[]::text[]),
    ('TURNIP', 'Speiserübe', ARRAY[]::text[], 'Speiserübe', ARRAY[]::text[]),
    ('TURRON', 'Turrón', ARRAY[]::text[], 'Turrón', ARRAY[]::text[]),
    ('TVP', 'Sojagranulat', ARRAY[]::text[], 'Texturiertes Sojaprotein', ARRAY['Sojafleisch']::text[]),
    ('TWAROG', 'Twaróg', ARRAY[]::text[], 'Twaróg', ARRAY[]::text[]),
    ('UBE', 'Ube', ARRAY[]::text[], 'Ube', ARRAY[]::text[]),
    ('UDON', 'Udon', ARRAY[]::text[], 'Udon', ARRAY[]::text[]),
    ('VANILLA', 'Vanille', ARRAY[]::text[], 'Vanille', ARRAY[]::text[]),
    ('VEAL', 'Kalbfleisch', ARRAY[]::text[], 'Kalbfleisch', ARRAY[]::text[]),
    ('VEAL_CHEEK', 'Kalbsbäckchen', ARRAY[]::text[], 'Kalbsbäckchen', ARRAY['Kalbsbacken']::text[]),
    ('VEAL_CHOP', 'Kalbskotelett', ARRAY[]::text[], 'Kalbskotelett', ARRAY[]::text[]),
    ('VEAL_CUTLET', 'Kalbsschnitzel', ARRAY[]::text[], 'Kalbsschnitzel', ARRAY[]::text[]),
    ('VEAL_GOULASH', 'Kalbsgulasch', ARRAY[]::text[], 'Kalbsgulasch', ARRAY[]::text[]),
    ('VEAL_LIVER', 'Kalbsleber', ARRAY[]::text[], 'Kalbsleber', ARRAY[]::text[]),
    ('VEAL_LUNG', 'Kalbslunge', ARRAY[]::text[], 'Kalbslunge', ARRAY[]::text[]),
    ('VEAL_MINCE', 'Kalbshackfleisch', ARRAY[]::text[], 'Kalbshackfleisch', ARRAY['Kalbshack']::text[]),
    ('VEAL_ROAST', 'Kalbsbraten', ARRAY[]::text[], 'Kalbsbraten', ARRAY[]::text[]),
    ('VEAL_SHANK', 'Kalbshaxe', ARRAY[]::text[], 'Kalbshaxe', ARRAY[]::text[]),
    ('VEAL_STEAK', 'Kalbssteak', ARRAY[]::text[], 'Kalbssteak', ARRAY[]::text[]),
    ('VEAL_STRIPS', 'Kalbsgeschnetzeltes', ARRAY[]::text[], 'Kalbsgeschnetzeltes', ARRAY[]::text[]),
    ('VEAL_SWEETBREAD', 'Kalbsbries', ARRAY[]::text[], 'Kalbsbries', ARRAY[]::text[]),
    ('VEGETABLES', 'Gemüse', ARRAY[]::text[], 'Gemüse', ARRAY[]::text[]),
    ('VEGETABLE_STOCK', 'Gemüsebrühe', ARRAY[]::text[], 'Gemüsebrühe', ARRAY[]::text[]),
    ('VENDACE', 'Kleine Maräne (Muikku)', ARRAY[]::text[], 'Kleine Maräne', ARRAY['Muikku']::text[]),
    ('VENISON', 'Hirschfleisch', ARRAY[]::text[], 'Hirschfleisch', ARRAY[]::text[]),
    ('VIETNAMESE_CORIANDER', 'vietnamesischer Koriander', ARRAY[]::text[], 'vietnamesischer Koriander', ARRAY['Rau răm']::text[]),
    ('VIETNAMESE_SOYBEAN_PASTE', 'Tương oder vietnamesische Sojabohnenpaste', ARRAY[]::text[], 'Tương', ARRAY[]::text[]),
    ('VIILI', 'Viili', ARRAY[]::text[], 'Viili', ARRAY[]::text[]),
    ('VINEGAR', 'Essig', ARRAY[]::text[], 'Essig', ARRAY[]::text[]),
    ('WAFFLES', 'Waffel', ARRAY[]::text[], 'Waffel', ARRAY[]::text[]),
    ('WAKAME', 'Wakame', ARRAY[]::text[], 'Wakame', ARRAY[]::text[]),
    ('WALNUT', 'Walnüsse', ARRAY[]::text[], 'Walnüsse', ARRAY[]::text[]),
    ('WATERCRESS', 'Brunnenkresse', ARRAY[]::text[], 'Brunnenkresse', ARRAY[]::text[]),
    ('WATERMELON', 'Wassermelone', ARRAY[]::text[], 'Wassermelone', ARRAY[]::text[]),
    ('WATER_CHESTNUT', 'Wasserkastanien', ARRAY[]::text[], 'Wasserkastanien', ARRAY[]::text[]),
    ('WATER_SPINACH', 'Wasserspinat oder Kangkong', ARRAY[]::text[], 'Wasserspinat', ARRAY['Kangkong']::text[]),
    ('WHEAT_FLOUR', 'Weizenmehl', ARRAY[]::text[], 'Weizenmehl', ARRAY[]::text[]),
    ('WHEAT_NOODLES', 'Weizennudeln', ARRAY[]::text[], 'Weizennudeln', ARRAY[]::text[]),
    ('WHEAT_PASTA', 'Weizenpasta', ARRAY[]::text[], 'Weizenpasta', ARRAY[]::text[]),
    ('WHISKY', 'Whisky', ARRAY[]::text[], 'Whisky', ARRAY['Whiskey']::text[]),
    ('WHITE_ASPARAGUS', 'weißer Spargel', ARRAY[]::text[], 'weißer Spargel', ARRAY[]::text[]),
    ('WHITE_BEANS', 'weiße Bohnen', ARRAY[]::text[], 'weiße Bohnen', ARRAY[]::text[]),
    ('WHITE_CABBAGE', 'Weißkohl', ARRAY[]::text[], 'Weißkohl', ARRAY['Weißkraut']::text[]),
    ('WHITE_CHAMPIGNON', 'weiße Champignons', ARRAY[]::text[], 'weiße Champignons', ARRAY[]::text[]),
    ('WHITE_CHOCOLATE', 'weiße Schokolade', ARRAY[]::text[], 'weiße Schokolade', ARRAY[]::text[]),
    ('WHITE_FISH', 'weißfleischiger Fisch', ARRAY[]::text[], 'weißfleischiger Fisch', ARRAY[]::text[]),
    ('WHITE_PEPPER', 'weißer Pfeffer', ARRAY[]::text[], 'weißer Pfeffer', ARRAY[]::text[]),
    ('WHITE_SAUSAGE', 'Weißwurst', ARRAY[]::text[], 'Weißwurst', ARRAY[]::text[]),
    ('WHITE_SUGAR', 'Zucker', ARRAY[]::text[], 'Zucker', ARRAY[]::text[]),
    ('WHITE_TEA', 'weißer Tee', ARRAY[]::text[], 'weißer Tee', ARRAY[]::text[]),
    ('WHITE_VINEGAR', 'Branntweinessig', ARRAY[]::text[], 'Branntweinessig', ARRAY[]::text[]),
    ('WHITE_WINE', 'Weißwein', ARRAY[]::text[], 'Weißwein', ARRAY[]::text[]),
    ('WHITE_WINE_VINEGAR', 'Weißweinessig', ARRAY[]::text[], 'Weißweinessig', ARRAY[]::text[]),
    ('WHOLEGRAIN_MUSTARD', 'körniger Senf', ARRAY[]::text[], 'körniger Senf', ARRAY[]::text[]),
    ('WIENER_SAUSAGE', 'Wiener Würstchen', ARRAY[]::text[], 'Wiener Würstchen', ARRAY[]::text[]),
    ('WILD_BOAR', 'Wildschwein', ARRAY[]::text[], 'Wildschwein', ARRAY['Wildschweinfleisch']::text[]),
    ('WILD_RICE', 'Wildreis', ARRAY[]::text[], 'Wildreis', ARRAY[]::text[]),
    ('WONTON_WRAPPERS', 'Wonton-Teigblätter', ARRAY[]::text[], 'Wonton-Teigblätter', ARRAY['Wan-Tan-Blätter']::text[]),
    ('WOOD_EAR', 'Mu-Err-Pilze', ARRAY[]::text[], 'Mu-Err-Pilze', ARRAY['Judasohr']::text[]),
    ('WORCESTERSHIRE_SAUCE', 'Worcestersauce', ARRAY[]::text[], 'Worcestersauce', ARRAY['Worcestershiresauce']::text[]),
    ('XO_SAUCE', 'XO-Sauce', ARRAY[]::text[], 'XO-Sauce', ARRAY[]::text[]),
    ('YAM', 'Yamswurzel', ARRAY[]::text[], 'Yamswurzel', ARRAY[]::text[]),
    ('YEAST_EXTRACT', 'Hefeextrakt', ARRAY[]::text[], 'Hefeextrakt', ARRAY[]::text[]),
    ('YELLOW_BELL_PEPPER', 'gelbe Paprika', ARRAY[]::text[], 'gelbe Paprika', ARRAY[]::text[]),
    ('YELLOW_LENTILS', 'gelbe Linsen', ARRAY[]::text[], 'Gelbe Linsen', ARRAY[]::text[]),
    ('YELLOW_SPLIT_PEAS', 'gelbe Schälerbsen', ARRAY[]::text[], 'gelbe Schälerbsen', ARRAY[]::text[]),
    ('YOGURT', 'Joghurt', ARRAY[]::text[], 'Joghurt', ARRAY[]::text[]),
    ('YUZU', 'Yuzu', ARRAY[]::text[], 'Yuzu', ARRAY[]::text[]),
    ('ZAATAR', 'Za’atar', ARRAY[]::text[], 'Za’atar', ARRAY['Zatar']::text[]),
    ('ZUCCHINI', 'Zucchini', ARRAY[]::text[], 'Zucchini', ARRAY[]::text[]);
-- END APPROVED R3 VALUES

DO $guard$
DECLARE
    mismatches text;
    invalid_targets text;
BEGIN
    IF (SELECT count(*) FROM ingredient_name_alias_r3_review) <> 906 THEN
        RAISE EXCEPTION 'Issue #264: invalid R3 review cardinality (expected 906 concepts)';
    END IF;

    IF (SELECT count(*) FROM ingredient_name_alias_r3_review
        WHERE previous_display_name IS DISTINCT FROM target_display_name) <> 37
       OR (SELECT coalesce(sum(cardinality(target_aliases)), 0)
           FROM ingredient_name_alias_r3_review) <> 206
       OR (SELECT count(*) FROM ingredient_name_alias_r3_review
           WHERE previous_display_name IS DISTINCT FROM target_display_name
              OR previous_aliases IS DISTINCT FROM target_aliases) <> 191 THEN
        RAISE EXCEPTION 'Issue #264: invalid approved R3 target cardinality (expected 37 names / 206 aliases / 191 changed concepts)';
    END IF;

    SELECT string_agg(coalesce(ic.code, review.code), ', '
                      ORDER BY coalesce(ic.code, review.code) COLLATE "C")
    INTO mismatches
    FROM ingredient_concept ic
    FULL JOIN ingredient_name_alias_r3_review review USING (code)
    WHERE ic.code IS NULL OR review.code IS NULL;

    IF mismatches IS NOT NULL THEN
        RAISE EXCEPTION 'Issue #264: missing, renamed or new catalog codes: %', mismatches;
    END IF;

    SELECT string_agg(review.code, ', ' ORDER BY review.code COLLATE "C")
    INTO mismatches
    FROM ingredient_name_alias_r3_review review
    JOIN ingredient_concept ic USING (code)
    LEFT JOIN LATERAL (
        SELECT coalesce(
            array_agg(alias.alias_text ORDER BY lower(alias.alias_text) COLLATE "C", alias.alias_text COLLATE "C"),
            ARRAY[]::text[]
        ) AS aliases
        FROM ingredient_concept_alias alias
        WHERE alias.ingredient_concept_id = ic.id
    ) actual_aliases ON true
    WHERE ic.display_name IS DISTINCT FROM review.previous_display_name
       OR actual_aliases.aliases IS DISTINCT FROM review.previous_aliases;

    IF mismatches IS NOT NULL THEN
        RAISE EXCEPTION 'Issue #264: unknown name/alias drift for codes: %. Reconcile before migration.', mismatches;
    END IF;

    SELECT string_agg(review.code, ', ' ORDER BY review.code COLLATE "C")
    INTO invalid_targets
    FROM ingredient_name_alias_r3_review review
    WHERE btrim(review.target_display_name) = ''
       OR review.target_display_name IS DISTINCT FROM btrim(review.target_display_name)
       OR EXISTS (
            SELECT 1
            FROM unnest(review.target_aliases) alias_text
            WHERE btrim(alias_text) = ''
               OR alias_text IS DISTINCT FROM btrim(alias_text)
               OR lower(alias_text) = lower(review.target_display_name)
       )
       OR cardinality(review.target_aliases) IS DISTINCT FROM (
            SELECT count(DISTINCT lower(alias_text))::integer
            FROM unnest(review.target_aliases) alias_text
       );

    IF invalid_targets IS NOT NULL THEN
        RAISE EXCEPTION 'Issue #264: invalid normalized R3 target values for codes: %', invalid_targets;
    END IF;

    SELECT string_agg(collision, ', ' ORDER BY collision COLLATE "C")
    INTO invalid_targets
    FROM (
        SELECT left_review.code || '<->' || right_review.code || ':' || left_review.target_display_name AS collision
        FROM ingredient_name_alias_r3_review left_review
        JOIN ingredient_name_alias_r3_review right_review
          ON left_review.code < right_review.code
         AND lower(left_review.target_display_name) = lower(right_review.target_display_name)
        UNION ALL
        SELECT alias_review.code || '<->' || canonical_review.code || ':' || alias_text AS collision
        FROM ingredient_name_alias_r3_review alias_review
        CROSS JOIN LATERAL unnest(alias_review.target_aliases) alias_text
        JOIN ingredient_name_alias_r3_review canonical_review
          ON canonical_review.code <> alias_review.code
         AND lower(canonical_review.target_display_name) = lower(alias_text)
        UNION ALL
        SELECT left_review.code || '<->' || right_review.code || ':' || left_alias AS collision
        FROM ingredient_name_alias_r3_review left_review
        CROSS JOIN LATERAL unnest(left_review.target_aliases) left_alias
        JOIN ingredient_name_alias_r3_review right_review ON right_review.code > left_review.code
        CROSS JOIN LATERAL unnest(right_review.target_aliases) right_alias
        WHERE lower(left_alias) = lower(right_alias)
    ) collisions;

    IF invalid_targets IS NOT NULL THEN
        RAISE EXCEPTION 'Issue #264: unapproved cross-concept R3 target collisions: %', invalid_targets;
    END IF;

    -- Immediate canonical-name uniqueness is safe because no target name is the
    -- current canonical name of a different concept before this write.
    SELECT string_agg(target.code || '<->' || source.code, ', '
                      ORDER BY target.code COLLATE "C", source.code COLLATE "C")
    INTO invalid_targets
    FROM ingredient_name_alias_r3_review target
    JOIN ingredient_name_alias_r3_review source
      ON source.code <> target.code
     AND lower(source.previous_display_name) = lower(target.target_display_name);

    IF invalid_targets IS NOT NULL THEN
        RAISE EXCEPTION 'Issue #264: unsafe immediate canonical-name transition: %', invalid_targets;
    END IF;
END $guard$;

DO $writes$
DECLARE
    affected integer;
BEGIN
    UPDATE ingredient_concept ic
    SET display_name = review.target_display_name,
        version = ic.version + 1
    FROM ingredient_name_alias_r3_review review
    WHERE ic.code = review.code
      AND review.previous_display_name IS DISTINCT FROM review.target_display_name;
    GET DIAGNOSTICS affected = ROW_COUNT;
    IF affected <> 37 THEN
        RAISE EXCEPTION 'Issue #264: display-name write count was %, expected 37', affected;
    END IF;

    INSERT INTO ingredient_concept_alias (ingredient_concept_id, alias_text)
    SELECT ic.id, alias_text
    FROM ingredient_name_alias_r3_review review
    JOIN ingredient_concept ic USING (code)
    CROSS JOIN LATERAL unnest(review.target_aliases) alias_text;
    GET DIAGNOSTICS affected = ROW_COUNT;
    IF affected <> 206 THEN
        RAISE EXCEPTION 'Issue #264: alias write count was %, expected 206', affected;
    END IF;

    UPDATE ingredient_concept ic
    SET version = ic.version + 1
    FROM ingredient_name_alias_r3_review review
    WHERE ic.code = review.code
      AND review.previous_display_name IS NOT DISTINCT FROM review.target_display_name
      AND review.previous_aliases IS DISTINCT FROM review.target_aliases;
    GET DIAGNOSTICS affected = ROW_COUNT;
    IF affected <> 154 THEN
        RAISE EXCEPTION 'Issue #264: alias-only aggregate-version write count was %, expected 154', affected;
    END IF;
END $writes$;

DO $postcondition$
DECLARE
    mismatches text;
BEGIN
    SELECT string_agg(review.code, ', ' ORDER BY review.code COLLATE "C")
    INTO mismatches
    FROM ingredient_name_alias_r3_review review
    JOIN ingredient_concept ic USING (code)
    LEFT JOIN LATERAL (
        SELECT coalesce(
            array_agg(alias.alias_text ORDER BY lower(alias.alias_text) COLLATE "C", alias.alias_text COLLATE "C"),
            ARRAY[]::text[]
        ) AS aliases
        FROM ingredient_concept_alias alias
        WHERE alias.ingredient_concept_id = ic.id
    ) actual_aliases ON true
    WHERE ic.display_name IS DISTINCT FROM review.target_display_name
       OR actual_aliases.aliases IS DISTINCT FROM review.target_aliases;

    IF mismatches IS NOT NULL THEN
        RAISE EXCEPTION 'Issue #264: persisted R3 name/alias postcondition failed for codes: %', mismatches;
    END IF;
END $postcondition$;
