#!/usr/bin/env bash

# Compose instance lifecycle, health checks, ports and rollback behavior.

write_compose_env() {
    local destination=$1
    local image=$2
    local port=$3
    local db_password=$4
    local app_config_file=$5

    cat > "$destination" <<EOF_ENV
MISE_EN_DICE_IMAGE=$image
MISE_EN_DICE_APP_PORT=$port
MISE_EN_DICE_DB_NAME=mise_en_dice
MISE_EN_DICE_DB_USERNAME=mise_en_dice
MISE_EN_DICE_DB_PASSWORD=$db_password
MISE_EN_DICE_APP_CONFIG_FILE=$app_config_file
MISE_EN_DICE_RUNTIME_GID=$(id -g)
MISE_EN_DICE_APP_MEMORY_LIMIT=$APP_MEMORY_LIMIT
MISE_EN_DICE_POSTGRES_MEMORY_LIMIT=$POSTGRES_MEMORY_LIMIT
EOF_ENV
    chmod 0600 "$destination"
}

write_instance_application_properties() {
    local destination=$1
    local secure_cookie=$2
    local include_discord=${3:-false}

    cat "$ADMIN_PROPERTIES" > "$destination"
    # The external bot secret is deliberately production-only, never a preview or smoke input.
    if [[ $include_discord == true && -f $DISCORD_PROPERTIES ]]; then
        cat "$DISCORD_PROPERTIES" >> "$destination"
    else
        # Make preview and smoke isolation explicit even if an unrelated local property file contains this key.
        echo 'mise-en-dice.discord.enabled=false' >> "$destination"
    fi
    cat >> "$destination" <<EOF_PROPERTIES
server.servlet.session.cookie.secure=$secure_cookie
server.forward-headers-strategy=native
management.endpoint.health.show-details=never
EOF_PROPERTIES
    # The container keeps the image's fixed non-root UID and receives only the
    # deployment user's primary group as a supplementary group for this read-only mount.
    chmod 0640 "$destination"
}

write_metadata() {
    local destination=$1
    local instance_type=$2
    local instance_name=$3
    local project_name=$4
    local source_ref=$5
    local source_sha=$6
    local image=$7
    local port=$8

    : > "$destination"
    med_write_shell_assignment "$destination" INSTANCE_TYPE "$instance_type"
    med_write_shell_assignment "$destination" INSTANCE_NAME "$instance_name"
    med_write_shell_assignment "$destination" PROJECT_NAME "$project_name"
    med_write_shell_assignment "$destination" SOURCE_REF "$source_ref"
    med_write_shell_assignment "$destination" SOURCE_SHA "$source_sha"
    med_write_shell_assignment "$destination" IMAGE "$image"
    med_write_shell_assignment "$destination" PORT "$port"
    med_write_shell_assignment "$destination" DEPLOYED_AT "$(med_utc_timestamp)"
    chmod 0600 "$destination"
}

load_metadata() {
    local instance_dir=$1
    [[ -f $instance_dir/metadata ]] || med_die "Instanzmetadaten fehlen: $instance_dir/metadata"
    # shellcheck disable=SC1090
    source "$instance_dir/metadata"
}

load_compose_env() {
    local instance_dir=$1
    [[ -f $instance_dir/compose.env ]] || med_die "Compose-Konfiguration fehlt: $instance_dir/compose.env"
    # The file is generated by this script and deliberately contains shell-safe simple values only.
    # shellcheck disable=SC1090
    source "$instance_dir/compose.env"
}

compose_instance() {
    local instance_dir=$1
    shift
    load_metadata "$instance_dir"
    docker compose \
        --project-name "$PROJECT_NAME" \
        --env-file "$instance_dir/compose.env" \
        -f "$COMPOSE_FILE" \
        "$@"
}

compose_project() {
    local project_name=$1
    local compose_env=$2
    shift 2
    docker compose \
        --project-name "$project_name" \
        --env-file "$compose_env" \
        -f "$COMPOSE_FILE" \
        "$@"
}

port_is_listening() {
    local port=$1
    ss -H -ltn "sport = :$port" 2>/dev/null | grep -q .
}

port_is_reserved_by_metadata() {
    local port=$1
    local metadata
    while IFS= read -r -d '' metadata; do
        if (
            unset PORT
            # shellcheck disable=SC1090
            source "$metadata"
            [[ ${PORT:-} == "$port" ]]
        ); then
            return 0
        fi
    done < <(find "$INSTANCES_DIR" -type f -name metadata -print0 2>/dev/null)
    return 1
}

allocate_preview_port() {
    local port
    for (( port = PREVIEW_PORT_START; port <= PREVIEW_PORT_END; port++ )); do
        if ! port_is_reserved_by_metadata "$port" && ! port_is_listening "$port"; then
            printf '%s' "$port"
            return 0
        fi
    done
    med_die "Kein freier Preview-Port im Bereich $PREVIEW_PORT_START-$PREVIEW_PORT_END."
}

wait_for_health() {
    local port=$1
    local timeout_seconds=${2:-$HEALTH_TIMEOUT_SECONDS}
    local deadline=$((SECONDS + timeout_seconds))

    while (( SECONDS < deadline )); do
        if curl --fail --silent --show-error --max-time 3 \
            "http://127.0.0.1:${port}/actuator/health" >/dev/null 2>&1; then
            return 0
        fi
        sleep 2
    done
    return 1
}

verify_admin_entry() {
    local port=$1
    local status
    status=$(curl --silent --output /dev/null --write-out '%{http_code}' --max-time 5 \
        "http://127.0.0.1:${port}/admin" || true)
    [[ $status == 302 || $status == 303 ]]
}

instance_container_status() {
    local instance_dir=$1
    load_metadata "$instance_dir"
    local container_id
    container_id=$(docker compose \
        --project-name "$PROJECT_NAME" \
        --env-file "$instance_dir/compose.env" \
        -f "$COMPOSE_FILE" ps -q app 2>/dev/null || true)
    if [[ -z $container_id ]]; then
        printf 'stopped'
        return
    fi
    docker inspect --format '{{.State.Status}}{{if .State.Health}}/{{.State.Health.Status}}{{end}}' "$container_id" 2>/dev/null \
        || printf 'unknown'
}

prepare_instance_files() {
    local instance_dir=$1
    local image=$2
    local port=$3
    local secure_cookie=$4

    mkdir -p "$instance_dir"
    chmod 0750 "$instance_dir"

    local db_password
    if [[ -f $instance_dir/compose.env ]]; then
        load_compose_env "$instance_dir"
        db_password=$MISE_EN_DICE_DB_PASSWORD
    else
        db_password=$(med_random_hex 32)
    fi

    local compose_tmp properties_tmp
    compose_tmp=$(mktemp "$TEMP_DIR/compose.XXXXXX")
    properties_tmp=$(mktemp "$TEMP_DIR/application.XXXXXX")
    local include_discord=false
    [[ $secure_cookie == true ]] && include_discord=true
    write_instance_application_properties "$properties_tmp" "$secure_cookie" "$include_discord"
    write_compose_env "$compose_tmp" "$image" "$port" "$db_password" "$instance_dir/application.properties"
    mv -f "$compose_tmp" "$instance_dir/compose.env"
    mv -f "$properties_tmp" "$instance_dir/application.properties"
    chmod 0600 "$instance_dir/compose.env"
    chmod 0640 "$instance_dir/application.properties"
}

rollback_instance_files() {
    local instance_dir=$1
    local had_previous=$2

    if [[ $had_previous == true ]]; then
        mv -f "$instance_dir/compose.env.previous" "$instance_dir/compose.env"
        mv -f "$instance_dir/application.properties.previous" "$instance_dir/application.properties"
        if [[ -f $instance_dir/metadata.previous ]]; then
            mv -f "$instance_dir/metadata.previous" "$instance_dir/metadata"
        fi
        if ! compose_instance "$instance_dir" up -d --remove-orphans >/dev/null; then
            med_warn 'Der vorherige Anwendungsstand konnte nicht erneut gestartet werden. Logs und Datenbankzustand prüfen.'
            return 0
        fi
        if wait_for_health "$PORT"; then
            med_warn 'Der vorherige Anwendungsstand wurde wieder gestartet. Eine bereits ausgeführte Datenbankmigration wird dadurch nicht zurückgenommen.'
        else
            med_warn 'Auch der vorherige Anwendungsstand wurde nicht wieder gesund. Logs prüfen.'
        fi
    else
        if [[ -f $instance_dir/metadata ]]; then
            compose_instance "$instance_dir" down --volumes --remove-orphans >/dev/null 2>&1 || true
        fi
        rm -f "$instance_dir/compose.env" "$instance_dir/application.properties" "$instance_dir/metadata"
    fi
}

activate_instance() {
    local instance_dir=$1
    local instance_type=$2
    local instance_name=$3
    local project_name=$4
    local requested_ref=$5
    local sha=$6
    local image=$7
    local port=$8
    local secure_cookie=$9

    local had_previous=false previous_port=$port
    if [[ -f $instance_dir/metadata ]]; then
        had_previous=true
        load_metadata "$instance_dir"
        previous_port=$PORT
        cp -f "$instance_dir/metadata" "$instance_dir/metadata.previous"
        cp -f "$instance_dir/compose.env" "$instance_dir/compose.env.previous"
        cp -f "$instance_dir/application.properties" "$instance_dir/application.properties.previous"
    elif port_is_listening "$port"; then
        med_die "Port $port ist bereits durch einen fremden Prozess belegt."
    fi

    [[ $previous_port == "$port" ]] || med_die 'Der Port einer bestehenden Instanz darf nicht stillschweigend wechseln.'

    prepare_instance_files "$instance_dir" "$image" "$port" "$secure_cookie"
    write_metadata "$instance_dir/metadata" "$instance_type" "$instance_name" "$project_name" \
        "$requested_ref" "$sha" "$image" "$port"

    med_note "Starte Compose-Projekt $project_name ..."
    if ! compose_instance "$instance_dir" up -d --remove-orphans; then
        med_warn 'Compose konnte die Instanz nicht starten.'
        rollback_instance_files "$instance_dir" "$had_previous"
        return 1
    fi

    if ! wait_for_health "$port"; then
        med_warn "Healthcheck auf Port $port ist fehlgeschlagen."
        compose_instance "$instance_dir" ps >&2 || true
        compose_instance "$instance_dir" logs --tail 200 app postgres >&2 || true
        rollback_instance_files "$instance_dir" "$had_previous"
        return 1
    fi

    if ! verify_admin_entry "$port"; then
        med_warn 'Der geschützte Admin-Einstieg liefert keinen Redirect auf das Login.'
        rollback_instance_files "$instance_dir" "$had_previous"
        return 1
    fi
    rm -f "$instance_dir/metadata.previous" "$instance_dir/compose.env.previous" "$instance_dir/application.properties.previous"
    med_note "Instanz ist gesund: http://127.0.0.1:${port}/admin"
}

create_temporary_instance_files() {
    local instance_dir=$1
    local image=$2
    local port=$3
    mkdir -p "$instance_dir"
    chmod 0750 "$instance_dir"
    write_instance_application_properties "$instance_dir/application.properties" false false
    write_compose_env "$instance_dir/compose.env" "$image" "$port" "$(med_random_hex 32)" "$instance_dir/application.properties"
}

smoke_image() {
    local image=$1
    local sha=$2
    local port project_name smoke_dir
    port=$(allocate_preview_port)
    project_name="med-smoke-${sha:0:10}-$$"
    smoke_dir="$TEMP_DIR/$project_name"
    create_temporary_instance_files "$smoke_dir" "$image" "$port"

    med_note 'Prüfe das Image vor dem Produktionswechsel gegen eine frische PostgreSQL-Datenbank ...'
    local result=0
    compose_project "$project_name" "$smoke_dir/compose.env" up -d --remove-orphans || result=$?
    if (( result == 0 )) && ! wait_for_health "$port"; then
        result=1
    fi
    if (( result == 0 )) && ! verify_admin_entry "$port"; then
        result=1
    fi

    if (( result != 0 )); then
        compose_project "$project_name" "$smoke_dir/compose.env" logs --tail 200 app postgres >&2 || true
    fi
    compose_project "$project_name" "$smoke_dir/compose.env" down --volumes --remove-orphans >/dev/null 2>&1 || true
    rm -rf "$smoke_dir"

    (( result == 0 )) || med_die 'Der Vorab-Smoke-Test des Images ist fehlgeschlagen.'
}
