--liquibase formatted sql
--changeset venomenon328:001-catalog-schema splitStatements:false

-- Mise en Dice - catalog and generation metadata schema
-- Target: PostgreSQL 14+
--
-- This migration models the curated ingredient catalog and the metadata used
-- by the random challenge generator.

-- ---------------------------------------------------------------------------
-- Participants
-- ---------------------------------------------------------------------------

CREATE TABLE participant (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            text NOT NULL UNIQUE,
    display_name    text NOT NULL,
    active          boolean NOT NULL DEFAULT true,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_participant_display_name_ci
    ON participant (lower(display_name));

-- ---------------------------------------------------------------------------
-- Ingredient concepts and known refinements
-- ---------------------------------------------------------------------------

CREATE TABLE ingredient_concept (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    text NOT NULL UNIQUE,
    display_name            text NOT NULL,
    active                  boolean NOT NULL DEFAULT true,
    random_draw_enabled     boolean NOT NULL DEFAULT true,
    challenge_specificity   text NOT NULL,
    base_draw_weight        numeric(10, 4) NOT NULL DEFAULT 1.0000,
    novelty_level           smallint,
    curator_note            text,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_ingredient_concept_specificity
        CHECK (challenge_specificity IN ('SPECIFIC', 'OPEN')),
    CONSTRAINT ck_ingredient_concept_draw_weight
        CHECK (base_draw_weight > 0),
    CONSTRAINT ck_ingredient_concept_novelty
        CHECK (novelty_level IS NULL OR novelty_level BETWEEN 1 AND 5)
);

CREATE UNIQUE INDEX uq_ingredient_concept_display_name_ci
    ON ingredient_concept (lower(display_name));

CREATE INDEX ix_ingredient_concept_random_pool
    ON ingredient_concept (challenge_specificity, base_draw_weight)
    WHERE active AND random_draw_enabled;

CREATE TABLE ingredient_refinement (
    parent_concept_id   bigint NOT NULL REFERENCES ingredient_concept(id) ON DELETE RESTRICT,
    child_concept_id    bigint NOT NULL REFERENCES ingredient_concept(id) ON DELETE RESTRICT,
    created_at          timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (parent_concept_id, child_concept_id),
    CONSTRAINT ck_ingredient_refinement_not_self
        CHECK (parent_concept_id <> child_concept_id)
);

CREATE INDEX ix_ingredient_refinement_child
    ON ingredient_refinement (child_concept_id);

CREATE OR REPLACE FUNCTION prevent_ingredient_refinement_cycle()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    cycle_found boolean;
BEGIN
    IF TG_OP = 'UPDATE' THEN
        SELECT EXISTS (
            WITH RECURSIVE descendants(concept_id) AS (
                SELECT ir.child_concept_id
                FROM ingredient_refinement ir
                WHERE ir.parent_concept_id = NEW.child_concept_id
                  AND NOT (
                      ir.parent_concept_id = OLD.parent_concept_id
                      AND ir.child_concept_id = OLD.child_concept_id
                  )

                UNION

                SELECT ir.child_concept_id
                FROM ingredient_refinement ir
                JOIN descendants d
                  ON ir.parent_concept_id = d.concept_id
                WHERE NOT (
                    ir.parent_concept_id = OLD.parent_concept_id
                    AND ir.child_concept_id = OLD.child_concept_id
                )
            )
            SELECT 1
            FROM descendants
            WHERE concept_id = NEW.parent_concept_id
        ) INTO cycle_found;
    ELSE
        SELECT EXISTS (
            WITH RECURSIVE descendants(concept_id) AS (
                SELECT ir.child_concept_id
                FROM ingredient_refinement ir
                WHERE ir.parent_concept_id = NEW.child_concept_id

                UNION

                SELECT ir.child_concept_id
                FROM ingredient_refinement ir
                JOIN descendants d
                  ON ir.parent_concept_id = d.concept_id
            )
            SELECT 1
            FROM descendants
            WHERE concept_id = NEW.parent_concept_id
        ) INTO cycle_found;
    END IF;

    IF cycle_found THEN
        RAISE EXCEPTION 'ingredient refinement would create a cycle (% -> %)',
            NEW.parent_concept_id, NEW.child_concept_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_ingredient_refinement_no_cycle
BEFORE INSERT OR UPDATE OF parent_concept_id, child_concept_id
ON ingredient_refinement
FOR EACH ROW
EXECUTE FUNCTION prevent_ingredient_refinement_cycle();

-- ---------------------------------------------------------------------------
-- Functional roles
-- ---------------------------------------------------------------------------

CREATE TABLE functional_role (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            text NOT NULL UNIQUE,
    display_name    text NOT NULL,
    description     text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_functional_role_display_name_ci
    ON functional_role (lower(display_name));

CREATE TABLE ingredient_functional_role (
    ingredient_concept_id   bigint NOT NULL REFERENCES ingredient_concept(id) ON DELETE CASCADE,
    functional_role_id      bigint NOT NULL REFERENCES functional_role(id) ON DELETE RESTRICT,

    PRIMARY KEY (ingredient_concept_id, functional_role_id)
);

CREATE INDEX ix_ingredient_functional_role_role
    ON ingredient_functional_role (functional_role_id, ingredient_concept_id);

-- ---------------------------------------------------------------------------
-- Culinary properties
-- ---------------------------------------------------------------------------

CREATE TABLE culinary_flag (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            text NOT NULL UNIQUE,
    display_name    text NOT NULL,
    description     text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_culinary_flag_display_name_ci
    ON culinary_flag (lower(display_name));

CREATE TABLE ingredient_culinary_flag (
    ingredient_concept_id   bigint NOT NULL REFERENCES ingredient_concept(id) ON DELETE CASCADE,
    culinary_flag_id        bigint NOT NULL REFERENCES culinary_flag(id) ON DELETE RESTRICT,

    PRIMARY KEY (ingredient_concept_id, culinary_flag_id)
);

CREATE INDEX ix_ingredient_culinary_flag_flag
    ON ingredient_culinary_flag (culinary_flag_id, ingredient_concept_id);

CREATE TABLE culinary_dimension (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            text NOT NULL UNIQUE,
    display_name    text NOT NULL,
    description     text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uq_culinary_dimension_display_name_ci
    ON culinary_dimension (lower(display_name));

CREATE TABLE ingredient_culinary_dimension (
    ingredient_concept_id   bigint NOT NULL REFERENCES ingredient_concept(id) ON DELETE CASCADE,
    culinary_dimension_id   bigint NOT NULL REFERENCES culinary_dimension(id) ON DELETE RESTRICT,
    level                   smallint NOT NULL,

    PRIMARY KEY (ingredient_concept_id, culinary_dimension_id),
    CONSTRAINT ck_ingredient_culinary_dimension_level
        CHECK (level BETWEEN 1 AND 5)
);

CREATE INDEX ix_ingredient_culinary_dimension_dimension
    ON ingredient_culinary_dimension (culinary_dimension_id, level, ingredient_concept_id);

-- ---------------------------------------------------------------------------
-- Per-participant availability and seasonality
-- ---------------------------------------------------------------------------

CREATE TABLE ingredient_availability (
    ingredient_concept_id   bigint NOT NULL REFERENCES ingredient_concept(id) ON DELETE CASCADE,
    participant_id          bigint NOT NULL REFERENCES participant(id) ON DELETE RESTRICT,
    availability_level      text NOT NULL,
    updated_at              timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (ingredient_concept_id, participant_id),
    CONSTRAINT ck_ingredient_availability_level
        CHECK (availability_level IN ('EASY', 'PLANNED', 'DIFFICULT', 'UNAVAILABLE'))
);

CREATE INDEX ix_ingredient_availability_participant
    ON ingredient_availability (participant_id, availability_level, ingredient_concept_id);

CREATE TABLE ingredient_seasonality (
    ingredient_concept_id   bigint NOT NULL REFERENCES ingredient_concept(id) ON DELETE CASCADE,
    month                   smallint NOT NULL,
    weight_multiplier       numeric(8, 4) NOT NULL,

    PRIMARY KEY (ingredient_concept_id, month),
    CONSTRAINT ck_ingredient_seasonality_month
        CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_ingredient_seasonality_multiplier
        CHECK (weight_multiplier > 0)
);

-- ---------------------------------------------------------------------------
-- Curated exclusion rules
-- ---------------------------------------------------------------------------

CREATE TABLE exclusion_rule (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                text NOT NULL UNIQUE,
    display_text        text NOT NULL,
    active              boolean NOT NULL DEFAULT true,
    base_draw_weight    numeric(10, 4) NOT NULL DEFAULT 1.0000,
    curator_note        text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_exclusion_rule_draw_weight
        CHECK (base_draw_weight > 0)
);

CREATE UNIQUE INDEX uq_exclusion_rule_display_text_ci
    ON exclusion_rule (lower(display_text));

CREATE TABLE exclusion_rule_target (
    exclusion_rule_id       bigint NOT NULL REFERENCES exclusion_rule(id) ON DELETE CASCADE,
    ingredient_concept_id   bigint NOT NULL REFERENCES ingredient_concept(id) ON DELETE RESTRICT,
    include_refinements     boolean NOT NULL DEFAULT false,

    PRIMARY KEY (exclusion_rule_id, ingredient_concept_id)
);

CREATE INDEX ix_exclusion_rule_target_concept
    ON exclusion_rule_target (ingredient_concept_id, exclusion_rule_id);

-- ---------------------------------------------------------------------------
-- Generic timestamp maintenance
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_ingredient_concept_touch_updated_at
BEFORE UPDATE ON ingredient_concept
FOR EACH ROW
EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_ingredient_availability_touch_updated_at
BEFORE UPDATE ON ingredient_availability
FOR EACH ROW
EXECUTE FUNCTION touch_updated_at();

CREATE TRIGGER trg_exclusion_rule_touch_updated_at
BEFORE UPDATE ON exclusion_rule
FOR EACH ROW
EXECUTE FUNCTION touch_updated_at();