--liquibase formatted sql
--changeset venomenon328:003-administration-foundation splitStatements:false

-- Optimistic-locking and audit foundation for future catalog administration.
-- This change intentionally does not introduce an administration-user table:
-- administration identities are supplied by external configuration.

ALTER TABLE ingredient_concept
    ADD COLUMN version bigint NOT NULL DEFAULT 0;

ALTER TABLE exclusion_rule
    ADD COLUMN version bigint NOT NULL DEFAULT 0;

CREATE TABLE catalog_audit_entry (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_group_id uuid NOT NULL,
    actor_key       text NOT NULL,
    entity_type     text NOT NULL,
    entity_id       bigint NOT NULL,
    action          text NOT NULL,
    before_state    jsonb,
    after_state     jsonb,
    payload_version smallint NOT NULL DEFAULT 1,
    occurred_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ix_catalog_audit_entry_entity_occurred_at
    ON catalog_audit_entry (entity_type, entity_id, occurred_at DESC);

CREATE INDEX ix_catalog_audit_entry_actor_occurred_at
    ON catalog_audit_entry (actor_key, occurred_at DESC);

CREATE INDEX ix_catalog_audit_entry_change_group
    ON catalog_audit_entry (change_group_id);
