--liquibase formatted sql
--changeset venomenon328:004-persisted-candidate-generation splitStatements:false

-- Phase 9D: detach generator ownership from curation and persist replayable batches.
-- Published changesets remain untouched. Existing curation/candidate/challenge rows are
-- migrated in place and retain their historical curation link.

ALTER TABLE generation_attempt DROP CONSTRAINT ck_generation_attempt_status;
ALTER TABLE generation_attempt DROP CONSTRAINT ck_generation_attempt_completion;

ALTER TABLE generation_attempt
    ADD COLUMN effective_date date,
    ADD COLUMN season_month smallint,
    ADD COLUMN attempt_seed bigint,
    ADD COLUMN rng_algorithm text,
    ADD COLUMN configuration_version text,
    ADD COLUMN canonical_payload_version integer,
    ADD COLUMN exclusion_rule_id bigint REFERENCES exclusion_rule(id) ON DELETE RESTRICT,
    ADD COLUMN exclusion_text_snapshot text,
    ADD COLUMN operation_token uuid,
    ADD COLUMN lease_expires_at timestamptz,
    ADD COLUMN failure_reason_code text,
    ADD COLUMN failure_detail text;

UPDATE generation_attempt
SET status = 'GENERATED'
WHERE status = 'SUCCEEDED';

-- Pre-9D in-flight attempts have neither a frozen context nor enough persisted input
-- to resume deterministically. Retain them as explicit technical failures instead of
-- silently regenerating them from current catalog state. Existing failures receive a
-- stable reason required by the new lifecycle.
UPDATE generation_attempt
SET status = 'FAILED',
    completed_at = COALESCE(completed_at, now()),
    failure_reason_code = 'CONTEXT_SNAPSHOT_INVALID',
    failure_detail = 'Legacy pending attempt has no replayable Phase-9D context snapshot'
WHERE status = 'PENDING';

UPDATE generation_attempt
SET failure_reason_code = 'TECHNICAL_GENERATION_FAILURE',
    failure_detail = COALESCE(failure_detail, 'Legacy technical generation failure')
WHERE status = 'FAILED' AND failure_reason_code IS NULL;

ALTER TABLE generation_attempt
    ADD CONSTRAINT ck_generation_attempt_status
        CHECK (status IN ('PENDING', 'CONTEXT_READY', 'GENERATED', 'EXHAUSTED', 'FAILED')),
    ADD CONSTRAINT ck_generation_attempt_completion
        CHECK (
            (status IN ('PENDING', 'CONTEXT_READY') AND completed_at IS NULL)
            OR (status IN ('GENERATED', 'EXHAUSTED', 'FAILED') AND completed_at IS NOT NULL)
        ),
    ADD CONSTRAINT ck_generation_attempt_month
        CHECK (season_month IS NULL OR season_month BETWEEN 1 AND 12),
    ADD CONSTRAINT ck_generation_attempt_payload_version
        CHECK (canonical_payload_version IS NULL OR canonical_payload_version > 0),
    ADD CONSTRAINT ck_generation_attempt_exclusion_snapshot
        CHECK (
            (exclusion_rule_id IS NULL AND exclusion_text_snapshot IS NULL)
            OR (exclusion_rule_id IS NOT NULL AND exclusion_text_snapshot IS NOT NULL)
        ),
    ADD CONSTRAINT ck_generation_attempt_lease
        CHECK (
            (operation_token IS NULL AND lease_expires_at IS NULL)
            OR (operation_token IS NOT NULL AND lease_expires_at IS NOT NULL)
        ),
    ADD CONSTRAINT ck_generation_attempt_failure
        CHECK (
            (status = 'FAILED' AND failure_reason_code IS NOT NULL)
            OR (status <> 'FAILED' AND failure_reason_code IS NULL AND failure_detail IS NULL)
        );

CREATE INDEX ix_generation_attempt_stale_lease
    ON generation_attempt (lease_expires_at)
    WHERE status IN ('PENDING', 'CONTEXT_READY');

CREATE TABLE generation_context_snapshot (
    generation_attempt_id       bigint PRIMARY KEY REFERENCES generation_attempt(id) ON DELETE CASCADE,
    configuration_snapshot      jsonb NOT NULL,
    catalog_snapshot            jsonb NOT NULL,
    request_snapshot            jsonb NOT NULL,
    visible_history_snapshot    jsonb NOT NULL,
    prepared_attempt_snapshot   jsonb NOT NULL,
    context_fingerprint         text NOT NULL,
    configuration_fingerprint   text NOT NULL,
    catalog_fingerprint         text NOT NULL,
    request_fingerprint         text NOT NULL,
    history_fingerprint         text NOT NULL,
    created_at                  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ck_generation_context_fingerprints CHECK (
        context_fingerprint ~ '^[0-9a-f]{64}$'
        AND configuration_fingerprint ~ '^[0-9a-f]{64}$'
        AND catalog_fingerprint ~ '^[0-9a-f]{64}$'
        AND request_fingerprint ~ '^[0-9a-f]{64}$'
        AND history_fingerprint ~ '^[0-9a-f]{64}$'
    )
);

CREATE TABLE generation_batch (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    generation_attempt_id   bigint NOT NULL REFERENCES generation_attempt(id) ON DELETE CASCADE,
    batch_number            smallint NOT NULL,
    batch_seed              bigint,
    status                  text NOT NULL,
    legacy_migrated         boolean NOT NULL DEFAULT false,
    fallback_level          text,
    reservoir_metrics       jsonb NOT NULL DEFAULT '{}'::jsonb,
    fallback_attempts       jsonb NOT NULL DEFAULT '[]'::jsonb,
    set_evaluation          jsonb,
    diagnostics             jsonb NOT NULL DEFAULT '[]'::jsonb,
    result_snapshot         jsonb,
    set_fingerprint         text,
    created_at              timestamptz NOT NULL DEFAULT now(),
    completed_at            timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT uq_generation_batch_number UNIQUE (generation_attempt_id, batch_number),
    CONSTRAINT ck_generation_batch_number CHECK (
        batch_number > 0 AND (legacy_migrated OR batch_number BETWEEN 1 AND 2)
    ),
    CONSTRAINT ck_generation_batch_status CHECK (status IN ('GENERATED', 'EXHAUSTED')),
    CONSTRAINT ck_generation_batch_result CHECK (
        legacy_migrated
        OR (
            status = 'GENERATED'
            AND batch_seed IS NOT NULL
            AND fallback_level IN ('STRICT', 'RELAXED_1', 'RELAXED_2')
            AND set_evaluation IS NOT NULL
            AND result_snapshot IS NOT NULL
            AND set_fingerprint ~ '^[0-9a-f]{64}$'
        )
        OR (
            status = 'EXHAUSTED'
            AND batch_seed IS NOT NULL
            AND fallback_level IS NULL
            AND set_evaluation IS NULL
            AND result_snapshot IS NOT NULL
            AND set_fingerprint IS NULL
        )
    )
);

CREATE INDEX ix_generation_batch_attempt_created
    ON generation_batch (generation_attempt_id, created_at);

-- Every old curation round becomes a legacy batch. The explicit legacy marker is the
-- only exception to the new 1..2 production bound, preserving any previously legal
-- number of historical rounds without opening batch 3 for new attempts.
INSERT INTO generation_batch (
    generation_attempt_id,
    batch_number,
    status,
    legacy_migrated,
    diagnostics,
    created_at,
    completed_at
)
SELECT
    generation_attempt_id,
    row_number() OVER (PARTITION BY generation_attempt_id ORDER BY round_number, id),
    'GENERATED',
    true,
    '[]'::jsonb,
    created_at,
    COALESCE(completed_at, created_at)
FROM curation_round;

-- A pre-9D SUCCEEDED row without any curation round cannot satisfy the sharpened
-- meaning of GENERATED (at least one complete persisted batch).
UPDATE generation_attempt attempt
SET status = 'FAILED',
    failure_reason_code = 'CONTEXT_SNAPSHOT_INVALID',
    failure_detail = 'Legacy successful attempt has no persisted generation batch'
WHERE attempt.status = 'GENERATED'
  AND NOT EXISTS (
      SELECT 1 FROM generation_batch batch WHERE batch.generation_attempt_id = attempt.id
  );

ALTER TABLE challenge_candidate
    ADD COLUMN generation_batch_id bigint REFERENCES generation_batch(id) ON DELETE CASCADE,
    ADD COLUMN proposal_ordinal bigint,
    ADD COLUMN profile text,
    ADD COLUMN target_specificity smallint,
    ADD COLUMN target_novelty_band text,
    ADD COLUMN actual_novelty_band text,
    ADD COLUMN known_novelty_load smallint,
    ADD COLUMN total_score numeric(7,4),
    ADD COLUMN data_confidence numeric(7,4),
    ADD COLUMN component_scores jsonb,
    ADD COLUMN profile_slot_assignments jsonb,
    ADD COLUMN generator_reason_codes jsonb,
    ADD COLUMN generator_diagnostics jsonb,
    ADD COLUMN canonical_signature text;

UPDATE challenge_candidate candidate
SET generation_batch_id = batch.id
FROM curation_round round_row
JOIN generation_batch batch
  ON batch.generation_attempt_id = round_row.generation_attempt_id
 AND batch.batch_number = (
     SELECT ranked.batch_number
     FROM (
         SELECT id, row_number() OVER (
             PARTITION BY generation_attempt_id ORDER BY round_number, id
         ) AS batch_number
         FROM curation_round
     ) ranked
     WHERE ranked.id = round_row.id
 )
WHERE candidate.curation_round_id = round_row.id;

ALTER TABLE challenge_candidate
    ALTER COLUMN generation_batch_id SET NOT NULL,
    ALTER COLUMN curation_round_id DROP NOT NULL,
    ALTER COLUMN is_selected DROP NOT NULL,
    ALTER COLUMN is_selected DROP DEFAULT,
    DROP CONSTRAINT uq_challenge_candidate_number,
    DROP CONSTRAINT ck_challenge_candidate_number,
    ADD CONSTRAINT uq_challenge_candidate_number_per_batch
        UNIQUE (generation_batch_id, candidate_number),
    ADD CONSTRAINT ck_challenge_candidate_number
        CHECK (candidate_number > 0),
    ADD CONSTRAINT ck_challenge_candidate_profile
        CHECK (profile IS NULL OR profile IN (
            'PROTEIN_PRODUCE', 'PRODUCE_DUO', 'STARCH_ANCHORED',
            'THREE_ANCHORS', 'FLEXIBLE_BALANCED'
        )),
    ADD CONSTRAINT ck_challenge_candidate_novelty
        CHECK (
            (target_novelty_band IS NULL OR target_novelty_band IN ('FAMILIAR', 'BALANCED', 'ADVENTUROUS'))
            AND (actual_novelty_band IS NULL OR actual_novelty_band IN ('FAMILIAR', 'BALANCED', 'ADVENTUROUS'))
        ),
    ADD CONSTRAINT ck_challenge_candidate_scores
        CHECK (
            (total_score IS NULL OR total_score BETWEEN 0 AND 100)
            AND (data_confidence IS NULL OR data_confidence BETWEEN 0 AND 100)
        );

CREATE INDEX ix_challenge_candidate_batch
    ON challenge_candidate (generation_batch_id, candidate_number);

ALTER TABLE candidate_requirement
    ADD COLUMN concept_code_snapshot text,
    ADD COLUMN novelty_level_snapshot smallint,
    ADD COLUMN concept_snapshot jsonb,
    ADD COLUMN weight_evaluation_snapshot jsonb,
    ADD COLUMN generator_reason_codes jsonb;

-- `ingredient_concept.code` is a stable immutable key. Backfill only that stable identity
-- for pre-9D requirements so confirmed legacy challenges keep exact REROLL blocking;
-- never reconstruct mutable historical roles, novelty, flags or graph state from today.
UPDATE candidate_requirement requirement
SET concept_code_snapshot = concept.code
FROM ingredient_concept concept
WHERE requirement.source = 'RANDOM'
  AND requirement.ingredient_concept_id = concept.id
  AND requirement.concept_code_snapshot IS NULL;

UPDATE candidate_requirement requirement
SET concept_code_snapshot = concept.code
FROM generation_manual_requirement manual_requirement
JOIN ingredient_concept concept
  ON concept.id = manual_requirement.matched_ingredient_concept_id
WHERE requirement.source = 'MANUAL'
  AND requirement.manual_requirement_id = manual_requirement.id
  AND requirement.concept_code_snapshot IS NULL;

ALTER TABLE candidate_requirement
    DROP CONSTRAINT candidate_requirement_manual_requirement_id_fkey,
    ADD CONSTRAINT candidate_requirement_manual_requirement_id_fkey
        FOREIGN KEY (manual_requirement_id)
        REFERENCES generation_manual_requirement(id) ON DELETE CASCADE;

ALTER TABLE candidate_requirement DROP CONSTRAINT ck_candidate_requirement_specificity_snapshot;
ALTER TABLE candidate_requirement
    ADD CONSTRAINT ck_candidate_requirement_specificity_snapshot
        CHECK (
            challenge_specificity_snapshot IS NULL
            OR challenge_specificity_snapshot IN ('SPECIFIC', 'OPEN', 'UNCLASSIFIED')
        ),
    ADD CONSTRAINT ck_candidate_requirement_novelty_snapshot
        CHECK (novelty_level_snapshot IS NULL OR novelty_level_snapshot BETWEEN 1 AND 5);

-- Candidate ownership now follows candidate -> batch -> attempt. Manual references must
-- belong to that same attempt; a retained curation link is historical metadata only.
CREATE OR REPLACE FUNCTION validate_candidate_requirement_context()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    candidate_attempt_id bigint;
    manual_attempt_id bigint;
BEGIN
    SELECT batch.generation_attempt_id
      INTO candidate_attempt_id
      FROM challenge_candidate candidate
      JOIN generation_batch batch ON batch.id = candidate.generation_batch_id
     WHERE candidate.id = NEW.candidate_id;

    IF candidate_attempt_id IS NULL THEN
        RAISE EXCEPTION 'candidate % does not exist', NEW.candidate_id;
    END IF;

    IF NEW.source = 'MANUAL' THEN
        SELECT generation_attempt_id
          INTO manual_attempt_id
          FROM generation_manual_requirement
         WHERE id = NEW.manual_requirement_id;

        IF manual_attempt_id IS NULL THEN
            RAISE EXCEPTION 'manual requirement % does not exist', NEW.manual_requirement_id;
        END IF;

        IF manual_attempt_id <> candidate_attempt_id THEN
            RAISE EXCEPTION 'manual requirement % does not belong to candidate generation attempt %',
                NEW.manual_requirement_id, candidate_attempt_id;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION validate_candidate_batch_context()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    batch_attempt_id bigint;
    batch_is_legacy boolean;
    round_attempt_id bigint;
BEGIN
    SELECT generation_attempt_id, legacy_migrated
      INTO batch_attempt_id, batch_is_legacy
      FROM generation_batch
     WHERE id = NEW.generation_batch_id;

    IF batch_attempt_id IS NULL THEN
        RAISE EXCEPTION 'generation batch % does not exist', NEW.generation_batch_id;
    END IF;

    IF NOT batch_is_legacy AND NEW.candidate_number NOT BETWEEN 1 AND 12 THEN
        RAISE EXCEPTION 'generated candidate number % must be between 1 and 12', NEW.candidate_number;
    END IF;

    IF NOT batch_is_legacy AND (
        NEW.curation_round_id IS NOT NULL
        OR NEW.is_selected IS NOT NULL
        OR NEW.curator_evaluation IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'new generator candidate must not contain legacy curation state';
    END IF;

    IF NEW.curation_round_id IS NOT NULL THEN
        SELECT generation_attempt_id INTO round_attempt_id
        FROM curation_round WHERE id = NEW.curation_round_id;
        IF round_attempt_id IS DISTINCT FROM batch_attempt_id THEN
            RAISE EXCEPTION 'legacy curation round and generation batch must belong to the same attempt';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_candidate_validate_batch_context
BEFORE INSERT OR UPDATE OF generation_batch_id, curation_round_id, candidate_number, is_selected, curator_evaluation
ON challenge_candidate
FOR EACH ROW
EXECUTE FUNCTION validate_candidate_batch_context();

CREATE OR REPLACE FUNCTION assert_generation_batch_complete(target_batch_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    batch_row generation_batch%ROWTYPE;
    candidate_count integer;
    incomplete_count integer;
BEGIN
    SELECT * INTO batch_row FROM generation_batch WHERE id = target_batch_id;
    IF NOT FOUND OR batch_row.legacy_migrated THEN
        RETURN;
    END IF;

    SELECT count(*) INTO candidate_count
    FROM challenge_candidate WHERE generation_batch_id = target_batch_id;

    IF batch_row.status = 'EXHAUSTED' THEN
        IF candidate_count <> 0 THEN
            RAISE EXCEPTION 'exhausted generation batch % must not contain candidates', target_batch_id;
        END IF;
        RETURN;
    END IF;

    IF candidate_count <> 12 THEN
        RAISE EXCEPTION 'generated batch % must contain exactly twelve candidates', target_batch_id;
    END IF;

    SELECT count(*) INTO incomplete_count
    FROM challenge_candidate candidate
    WHERE candidate.generation_batch_id = target_batch_id
      AND (
          candidate.candidate_number NOT BETWEEN 1 AND 12
          OR candidate.proposal_ordinal IS NULL
          OR candidate.profile IS NULL
          OR candidate.target_specificity IS NULL
          OR candidate.target_novelty_band IS NULL
          OR candidate.actual_novelty_band IS NULL
          OR candidate.known_novelty_load IS NULL
          OR candidate.total_score IS NULL
          OR candidate.data_confidence IS NULL
          OR candidate.component_scores IS NULL
          OR candidate.profile_slot_assignments IS NULL
          OR candidate.generator_reason_codes IS NULL
          OR candidate.generator_diagnostics IS NULL
          OR candidate.canonical_signature IS NULL
          OR (SELECT count(*) FROM candidate_requirement requirement
              WHERE requirement.candidate_id = candidate.id) <> 4
      );

    IF incomplete_count <> 0 THEN
        RAISE EXCEPTION 'generated batch % contains incomplete candidate snapshots', target_batch_id;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION validate_generation_batch_complete_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM assert_generation_batch_complete(CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END);
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_generation_batch_complete
AFTER INSERT OR UPDATE ON generation_batch
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_generation_batch_complete_trigger();

CREATE OR REPLACE FUNCTION validate_candidate_batch_complete_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' OR TG_OP = 'UPDATE' THEN
        PERFORM assert_generation_batch_complete(OLD.generation_batch_id);
    END IF;
    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        PERFORM assert_generation_batch_complete(NEW.generation_batch_id);
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_candidate_batch_complete
AFTER INSERT OR UPDATE OR DELETE ON challenge_candidate
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_candidate_batch_complete_trigger();

CREATE OR REPLACE FUNCTION validate_requirement_batch_complete_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    affected_batch_id bigint;
BEGIN
    SELECT generation_batch_id INTO affected_batch_id
    FROM challenge_candidate
    WHERE id = CASE WHEN TG_OP = 'DELETE' THEN OLD.candidate_id ELSE NEW.candidate_id END;
    IF affected_batch_id IS NOT NULL THEN
        PERFORM assert_generation_batch_complete(affected_batch_id);
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_requirement_batch_complete
AFTER INSERT OR UPDATE OR DELETE ON candidate_requirement
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION validate_requirement_batch_complete_trigger();

-- Preserve legacy challenge rows, but do not allow an uncurated Phase-9D candidate to
-- become visible merely by toggling the retained pre-9D is_selected flag. Phase 10 will
-- replace this legacy gate with explicit curated-offer confirmation.
CREATE OR REPLACE FUNCTION validate_challenge_selected_candidate()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    candidate_attempt_id bigint;
    candidate_batch_is_legacy boolean;
    candidate_is_selected boolean;
    candidate_curation_round_id bigint;
    candidate_curation_status text;
BEGIN
    SELECT batch.generation_attempt_id,
           batch.legacy_migrated,
           candidate.is_selected,
           candidate.curation_round_id,
           round_row.status
      INTO candidate_attempt_id,
           candidate_batch_is_legacy,
           candidate_is_selected,
           candidate_curation_round_id,
           candidate_curation_status
      FROM challenge_candidate candidate
      JOIN generation_batch batch ON batch.id = candidate.generation_batch_id
      LEFT JOIN curation_round round_row ON round_row.id = candidate.curation_round_id
     WHERE candidate.id = NEW.selected_candidate_id;

    IF candidate_attempt_id IS NULL THEN
        RAISE EXCEPTION 'selected challenge candidate % does not exist', NEW.selected_candidate_id;
    END IF;

    IF candidate_attempt_id <> NEW.generation_attempt_id THEN
        RAISE EXCEPTION 'selected candidate % does not belong to generation attempt %',
            NEW.selected_candidate_id, NEW.generation_attempt_id;
    END IF;

    IF candidate_batch_is_legacy IS DISTINCT FROM true
       OR candidate_curation_round_id IS NULL
       OR candidate_curation_status IS DISTINCT FROM 'SELECTED'
       OR candidate_is_selected IS DISTINCT FROM true THEN
        RAISE EXCEPTION 'candidate % has no completed legacy curation; Phase-9D candidates require Phase-10 offer confirmation before visibility',
            NEW.selected_candidate_id;
    END IF;

    IF (SELECT count(*) FROM candidate_requirement WHERE candidate_id = NEW.selected_candidate_id) <> 4 THEN
        RAISE EXCEPTION 'selected candidate % must contain exactly four requirements', NEW.selected_candidate_id;
    END IF;

    RETURN NEW;
END;
$$;
