--liquibase formatted sql
--changeset venomenon328:008-offer-decision-lifecycle splitStatements:false

-- Phase 11A: transport-neutral presentation, decision, and reroll exposure lifecycle.
-- Existing challenges and legacy curation data stay readable.  New challenges are
-- authoritative only through curated_offer; legacy is_selected is never revived.

ALTER TABLE challenge
    ADD COLUMN curated_offer_id bigint REFERENCES curated_offer(id) ON DELETE RESTRICT,
    ADD CONSTRAINT uq_challenge_curated_offer UNIQUE (curated_offer_id);

-- This snapshot is intentionally taken while 008 runs: only rows that already existed
-- before the offer-decision schema may remain without the new authoritative reference.
-- A legacy-looking candidate batch is not sufficient authority for a later INSERT.
ALTER TABLE challenge
    ADD COLUMN legacy_pre_offer_decision boolean NOT NULL DEFAULT false;

UPDATE challenge
   SET legacy_pre_offer_decision = true
 WHERE curated_offer_id IS NULL;

ALTER TABLE challenge
    ADD CONSTRAINT ck_challenge_offer_authority
    CHECK (curated_offer_id IS NOT NULL OR legacy_pre_offer_decision);

CREATE TABLE reroll_offer_exposure (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_session_id    bigint NOT NULL UNIQUE REFERENCES challenge_session(id) ON DELETE RESTRICT,
    curated_offer_set_id    bigint NOT NULL UNIQUE REFERENCES curated_offer_set(id) ON DELETE RESTRICT,
    exposed_at              timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE reroll_offer_exposure_requirement (
    reroll_offer_exposure_id    bigint NOT NULL REFERENCES reroll_offer_exposure(id) ON DELETE CASCADE,
    curated_offer_id            bigint NOT NULL REFERENCES curated_offer(id) ON DELETE RESTRICT,
    challenge_candidate_id      bigint NOT NULL REFERENCES challenge_candidate(id) ON DELETE RESTRICT,
    requirement_position        smallint NOT NULL,
    source                      text NOT NULL,
    ingredient_concept_id       bigint REFERENCES ingredient_concept(id) ON DELETE RESTRICT,
    concept_code_snapshot       text,
    display_text_snapshot       text NOT NULL,

    PRIMARY KEY (reroll_offer_exposure_id, curated_offer_id, requirement_position),
    CONSTRAINT ck_reroll_offer_exposure_requirement_position CHECK (requirement_position BETWEEN 1 AND 4),
    CONSTRAINT ck_reroll_offer_exposure_requirement_source CHECK (source IN ('RANDOM', 'MANUAL')),
    CONSTRAINT ck_reroll_offer_exposure_requirement_display CHECK (btrim(display_text_snapshot) <> '')
);

CREATE INDEX ix_reroll_offer_exposure_set ON reroll_offer_exposure (curated_offer_set_id);
CREATE INDEX ix_reroll_offer_exposure_requirement_code
    ON reroll_offer_exposure_requirement (concept_code_snapshot)
    WHERE concept_code_snapshot IS NOT NULL;

CREATE OR REPLACE FUNCTION validate_curated_offer_set_decision_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'CURATED_UNPRESENTED' OR NEW.presented_at IS NOT NULL OR NEW.decided_at IS NOT NULL THEN
            RAISE EXCEPTION 'new curated offer sets must start unpresented';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.status = 'CURATED_UNPRESENTED' THEN
        IF NEW.status <> 'PRESENTED_PENDING_DECISION'
           OR NEW.presented_at IS NULL OR NEW.decided_at IS NOT NULL THEN
            RAISE EXCEPTION 'an unpresented offer set may only become presented pending decision';
        END IF;
    ELSIF OLD.status = 'PRESENTED_PENDING_DECISION' THEN
        IF NEW.status NOT IN ('CONFIRMED', 'REROLLED')
           OR NEW.presented_at IS DISTINCT FROM OLD.presented_at OR NEW.decided_at IS NULL THEN
            RAISE EXCEPTION 'a presented offer set must receive exactly one terminal decision';
        END IF;
    ELSIF NEW.status IS DISTINCT FROM OLD.status
          OR NEW.presented_at IS DISTINCT FROM OLD.presented_at
          OR NEW.decided_at IS DISTINCT FROM OLD.decided_at THEN
        RAISE EXCEPTION 'terminal curated offer decisions are immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_curated_offer_set_decision_transition
BEFORE INSERT OR UPDATE OF status, presented_at, decided_at
ON curated_offer_set
FOR EACH ROW
EXECUTE FUNCTION validate_curated_offer_set_decision_transition();

CREATE OR REPLACE FUNCTION validate_reroll_offer_exposure()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    offer_session_id bigint;
    offer_status text;
BEGIN
    SELECT attempt.challenge_session_id, offer_set.status
      INTO offer_session_id, offer_status
      FROM curated_offer_set offer_set
      JOIN generation_attempt attempt ON attempt.id = offer_set.generation_attempt_id
     WHERE offer_set.id = NEW.curated_offer_set_id;

    IF offer_session_id IS NULL OR offer_session_id <> NEW.challenge_session_id
       OR offer_status <> 'REROLLED' THEN
        RAISE EXCEPTION 'reroll exposure must belong to its rerolled presented offer set and session';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_reroll_offer_exposure_validate
BEFORE INSERT OR UPDATE OF challenge_session_id, curated_offer_set_id
ON reroll_offer_exposure
FOR EACH ROW
EXECUTE FUNCTION validate_reroll_offer_exposure();

CREATE OR REPLACE FUNCTION prevent_reroll_offer_exposure_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'reroll offer exposures are append-only';
END;
$$;

CREATE TRIGGER trg_reroll_offer_exposure_append_only
BEFORE UPDATE OR DELETE ON reroll_offer_exposure
FOR EACH ROW
EXECUTE FUNCTION prevent_reroll_offer_exposure_mutation();

CREATE OR REPLACE FUNCTION validate_reroll_offer_exposure_requirement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    exposure_offer_set_id bigint;
    offer_candidate_id bigint;
    actual_source text;
    actual_concept_id bigint;
    actual_code text;
    actual_display text;
BEGIN
    SELECT curated_offer_set_id INTO exposure_offer_set_id
      FROM reroll_offer_exposure WHERE id = NEW.reroll_offer_exposure_id;
    SELECT challenge_candidate_id INTO offer_candidate_id
      FROM curated_offer
     WHERE id = NEW.curated_offer_id AND curated_offer_set_id = exposure_offer_set_id;
    IF offer_candidate_id IS NULL OR offer_candidate_id <> NEW.challenge_candidate_id THEN
        RAISE EXCEPTION 'reroll exposure requirement must reference an offer candidate of its exposed set';
    END IF;

    SELECT source, ingredient_concept_id, concept_code_snapshot, display_text_snapshot
      INTO actual_source, actual_concept_id, actual_code, actual_display
      FROM candidate_requirement
     WHERE candidate_id = NEW.challenge_candidate_id AND position = NEW.requirement_position;
    IF actual_source IS NULL OR actual_source <> NEW.source
       OR actual_concept_id IS DISTINCT FROM NEW.ingredient_concept_id
       OR actual_code IS DISTINCT FROM NEW.concept_code_snapshot
       OR actual_display IS DISTINCT FROM NEW.display_text_snapshot THEN
        RAISE EXCEPTION 'reroll exposure requirement must copy the authoritative candidate snapshot exactly';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_reroll_offer_exposure_requirement_validate
BEFORE INSERT OR UPDATE
ON reroll_offer_exposure_requirement
FOR EACH ROW
EXECUTE FUNCTION validate_reroll_offer_exposure_requirement();

CREATE OR REPLACE FUNCTION assert_reroll_offer_exposure_complete(target_exposure_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    target_offer_set_id bigint;
    expected_count integer;
    actual_count integer;
BEGIN
    SELECT curated_offer_set_id INTO target_offer_set_id
      FROM reroll_offer_exposure WHERE id = target_exposure_id;
    IF NOT FOUND THEN
        RETURN;
    END IF;
    SELECT count(*) * 4 INTO expected_count FROM curated_offer WHERE curated_offer_set_id = target_offer_set_id;
    SELECT count(*) INTO actual_count
      FROM reroll_offer_exposure_requirement WHERE reroll_offer_exposure_id = target_exposure_id;
    IF expected_count = 0 OR actual_count <> expected_count THEN
        RAISE EXCEPTION 'reroll exposure % must contain exactly the four snapshots of every exposed offer',
            target_exposure_id;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION validate_reroll_offer_exposure_complete_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM assert_reroll_offer_exposure_complete(CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END);
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION validate_reroll_offer_exposure_requirement_complete_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM assert_reroll_offer_exposure_complete(
        CASE WHEN TG_OP = 'DELETE' THEN OLD.reroll_offer_exposure_id ELSE NEW.reroll_offer_exposure_id END
    );
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_reroll_offer_exposure_complete
AFTER INSERT OR UPDATE ON reroll_offer_exposure
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_reroll_offer_exposure_complete_trigger();

CREATE CONSTRAINT TRIGGER trg_reroll_offer_exposure_requirement_complete
AFTER INSERT OR UPDATE OR DELETE ON reroll_offer_exposure_requirement
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_reroll_offer_exposure_requirement_complete_trigger();

CREATE OR REPLACE FUNCTION validate_challenge_selected_candidate()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    candidate_attempt_id bigint;
    offer_attempt_id bigint;
    offer_candidate_id bigint;
    offer_set_status text;
BEGIN
    IF TG_OP = 'INSERT' AND NEW.legacy_pre_offer_decision THEN
        RAISE EXCEPTION 'legacy challenge marker is reserved for rows present before migration 008';
    ELSIF TG_OP = 'UPDATE'
          AND NEW.legacy_pre_offer_decision IS DISTINCT FROM OLD.legacy_pre_offer_decision THEN
        RAISE EXCEPTION 'legacy challenge marker is immutable';
    END IF;

    SELECT batch.generation_attempt_id
      INTO candidate_attempt_id
      FROM challenge_candidate candidate
      JOIN generation_batch batch ON batch.id = candidate.generation_batch_id
     WHERE candidate.id = NEW.selected_candidate_id;

    IF candidate_attempt_id IS NULL THEN
        RAISE EXCEPTION 'selected challenge candidate % does not exist', NEW.selected_candidate_id;
    END IF;
    IF candidate_attempt_id <> NEW.generation_attempt_id THEN
        RAISE EXCEPTION 'selected candidate % does not belong to generation attempt %',
            NEW.selected_candidate_id, NEW.generation_attempt_id;
    END IF;
    IF (SELECT count(*) FROM candidate_requirement WHERE candidate_id = NEW.selected_candidate_id) <> 4 THEN
        RAISE EXCEPTION 'selected candidate % must contain exactly four requirements', NEW.selected_candidate_id;
    END IF;

    IF NEW.curated_offer_id IS NULL THEN
        IF NEW.legacy_pre_offer_decision IS DISTINCT FROM true THEN
            RAISE EXCEPTION 'new challenges require a confirmed curated offer; only pre-migration legacy rows remain valid';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.legacy_pre_offer_decision THEN
        RAISE EXCEPTION 'legacy challenge marker cannot accompany a curated offer';
    END IF;

    SELECT offer_set.generation_attempt_id, offer.challenge_candidate_id, offer_set.status
      INTO offer_attempt_id, offer_candidate_id, offer_set_status
      FROM curated_offer offer
      JOIN curated_offer_set offer_set ON offer_set.id = offer.curated_offer_set_id
     WHERE offer.id = NEW.curated_offer_id;
    IF offer_attempt_id IS NULL OR offer_attempt_id <> NEW.generation_attempt_id
       OR offer_candidate_id <> NEW.selected_candidate_id OR offer_set_status <> 'CONFIRMED' THEN
        RAISE EXCEPTION 'new challenge must reference its confirmed offer and authoritative candidate';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION assert_curated_offer_decision(target_offer_set_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    target_status text;
    challenges_for_set integer;
    exposures_for_set integer;
BEGIN
    SELECT status INTO target_status FROM curated_offer_set WHERE id = target_offer_set_id;
    IF NOT FOUND THEN
        RETURN;
    END IF;
    SELECT count(*) INTO challenges_for_set
      FROM challenge challenge_row
      JOIN curated_offer offer ON offer.id = challenge_row.curated_offer_id
     WHERE offer.curated_offer_set_id = target_offer_set_id;
    SELECT count(*) INTO exposures_for_set
      FROM reroll_offer_exposure WHERE curated_offer_set_id = target_offer_set_id;
    IF target_status = 'CONFIRMED' AND (challenges_for_set <> 1 OR exposures_for_set <> 0) THEN
        RAISE EXCEPTION 'a confirmed offer set requires exactly one challenge and no reroll exposure';
    ELSIF target_status = 'REROLLED' AND (challenges_for_set <> 0 OR exposures_for_set <> 1) THEN
        RAISE EXCEPTION 'a rerolled offer set requires exactly one reroll exposure and no challenge';
    ELSIF target_status NOT IN ('CONFIRMED', 'REROLLED')
          AND (challenges_for_set <> 0 OR exposures_for_set <> 0) THEN
        RAISE EXCEPTION 'only terminal offer decisions may own a challenge or reroll exposure';
    END IF;
END;
$$;

DROP TRIGGER trg_challenge_validate_selected_candidate ON challenge;
CREATE TRIGGER trg_challenge_validate_selected_candidate
BEFORE INSERT OR UPDATE OF generation_attempt_id, selected_candidate_id, curated_offer_id, legacy_pre_offer_decision
ON challenge
FOR EACH ROW
EXECUTE FUNCTION validate_challenge_selected_candidate();

CREATE OR REPLACE FUNCTION validate_curated_offer_decision_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_offer_set_id bigint;
BEGIN
    IF TG_TABLE_NAME = 'curated_offer_set' THEN
        target_offer_set_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
    ELSIF TG_TABLE_NAME = 'reroll_offer_exposure' THEN
        target_offer_set_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.curated_offer_set_id ELSE NEW.curated_offer_set_id END;
    ELSIF TG_OP = 'DELETE' THEN
        IF OLD.curated_offer_id IS NULL THEN RETURN NULL; END IF;
        SELECT curated_offer_set_id INTO target_offer_set_id FROM curated_offer WHERE id = OLD.curated_offer_id;
    ELSIF NEW.curated_offer_id IS NULL THEN
        RETURN NULL;
    ELSE
        SELECT curated_offer_set_id INTO target_offer_set_id FROM curated_offer WHERE id = NEW.curated_offer_id;
    END IF;
    IF target_offer_set_id IS NOT NULL THEN
        PERFORM assert_curated_offer_decision(target_offer_set_id);
    END IF;
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_curated_offer_set_decision_complete
AFTER INSERT OR UPDATE ON curated_offer_set
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_curated_offer_decision_trigger();

CREATE CONSTRAINT TRIGGER trg_challenge_curated_offer_decision_complete
AFTER INSERT OR UPDATE ON challenge
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_curated_offer_decision_trigger();

CREATE CONSTRAINT TRIGGER trg_reroll_offer_exposure_decision_complete
AFTER INSERT OR UPDATE ON reroll_offer_exposure
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_curated_offer_decision_trigger();

CREATE OR REPLACE FUNCTION validate_reroll_generation_attempt()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW.attempt_type = 'REROLL' AND NOT EXISTS (
        SELECT 1 FROM reroll_offer_exposure WHERE challenge_session_id = NEW.challenge_session_id
    ) THEN
        RAISE EXCEPTION 'reroll generation attempt requires a committed rerolled offer exposure';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_generation_attempt_validate_reroll_exposure
BEFORE INSERT ON generation_attempt
FOR EACH ROW EXECUTE FUNCTION validate_reroll_generation_attempt();

CREATE OR REPLACE FUNCTION assert_reroll_attempt_input(target_attempt_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    target_session_id bigint;
    target_type text;
    target_date date;
    initial_attempt_id bigint;
    initial_date date;
    target_manuals jsonb;
    initial_manuals jsonb;
BEGIN
    SELECT challenge_session_id, attempt_type, effective_date
      INTO target_session_id, target_type, target_date
      FROM generation_attempt WHERE id = target_attempt_id;
    IF NOT FOUND OR target_type <> 'REROLL' THEN
        RETURN;
    END IF;
    SELECT id, effective_date INTO initial_attempt_id, initial_date
      FROM generation_attempt
     WHERE challenge_session_id = target_session_id AND attempt_type = 'INITIAL';
    IF initial_attempt_id IS NULL OR target_date IS DISTINCT FROM initial_date THEN
        RAISE EXCEPTION 'reroll generation input must retain the initial effective date';
    END IF;
    SELECT coalesce(jsonb_agg(jsonb_build_array(position, display_text, matched_ingredient_concept_id)
                     ORDER BY position), '[]'::jsonb)
      INTO target_manuals FROM generation_manual_requirement WHERE generation_attempt_id = target_attempt_id;
    SELECT coalesce(jsonb_agg(jsonb_build_array(position, display_text, matched_ingredient_concept_id)
                     ORDER BY position), '[]'::jsonb)
      INTO initial_manuals FROM generation_manual_requirement WHERE generation_attempt_id = initial_attempt_id;
    IF target_manuals <> initial_manuals THEN
        RAISE EXCEPTION 'reroll generation input must retain the initial manual requirements';
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION validate_reroll_generation_attempt_input_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM assert_reroll_attempt_input(CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END);
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION validate_reroll_manual_requirement_input_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    PERFORM assert_reroll_attempt_input(
        CASE WHEN TG_OP = 'DELETE' THEN OLD.generation_attempt_id ELSE NEW.generation_attempt_id END
    );
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_generation_attempt_reroll_input
AFTER INSERT OR UPDATE OR DELETE ON generation_attempt
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_reroll_generation_attempt_input_trigger();

CREATE CONSTRAINT TRIGGER trg_generation_manual_reroll_input
AFTER INSERT OR UPDATE OR DELETE ON generation_manual_requirement
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_reroll_manual_requirement_input_trigger();
