--liquibase formatted sql
--changeset venomenon328:009-challenge-voting-participation splitStatements:false

-- Phase 11B: transport-neutral participant identity, fixed electorate snapshots,
-- secret mutable votes, durable results, and challenge participation.

CREATE TABLE participant_external_identity (
    participant_id   bigint NOT NULL REFERENCES participant(id) ON DELETE RESTRICT,
    provider         text NOT NULL,
    external_subject text NOT NULL,
    linked_at        timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (provider, external_subject),
    CONSTRAINT uq_participant_external_identity_provider UNIQUE (participant_id, provider),
    CONSTRAINT ck_participant_external_identity_provider CHECK (btrim(provider) <> ''),
    CONSTRAINT ck_participant_external_identity_subject CHECK (btrim(external_subject) <> '')
);

CREATE INDEX ix_participant_external_identity_participant
    ON participant_external_identity (participant_id);

CREATE TABLE selection_electorate (
    challenge_session_id bigint NOT NULL REFERENCES challenge_session(id) ON DELETE RESTRICT,
    participant_id       bigint NOT NULL REFERENCES participant(id) ON DELETE RESTRICT,
    snapshotted_at       timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (challenge_session_id, participant_id)
);

CREATE INDEX ix_selection_electorate_participant
    ON selection_electorate (participant_id, challenge_session_id);

CREATE TABLE selection_voting_round (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_session_id    bigint NOT NULL REFERENCES challenge_session(id) ON DELETE RESTRICT,
    round_number            smallint NOT NULL,
    curated_offer_set_id    bigint NOT NULL REFERENCES curated_offer_set(id) ON DELETE RESTRICT,
    status                  text NOT NULL DEFAULT 'OPEN',
    result_option_type      text,
    result_curated_offer_id bigint REFERENCES curated_offer(id) ON DELETE RESTRICT,
    tie_break_used          boolean NOT NULL DEFAULT false,
    completed_at            timestamptz,
    apply_state             text NOT NULL DEFAULT 'PENDING',
    resulting_offer_set_id  bigint REFERENCES curated_offer_set(id) ON DELETE RESTRICT,
    apply_detail            text,
    applied_at              timestamptz,

    CONSTRAINT uq_selection_voting_round_number UNIQUE (challenge_session_id, round_number),
    CONSTRAINT uq_selection_voting_round_offer_set UNIQUE (curated_offer_set_id),
    CONSTRAINT ck_selection_voting_round_number CHECK (round_number IN (1, 2)),
    CONSTRAINT ck_selection_voting_round_status CHECK (status IN ('OPEN', 'COMPLETED')),
    CONSTRAINT ck_selection_voting_round_result_type
        CHECK (result_option_type IS NULL OR result_option_type IN ('OFFER', 'ACCEPT', 'REROLL')),
    CONSTRAINT ck_selection_voting_round_result_shape CHECK (
        (result_option_type = 'OFFER' AND result_curated_offer_id IS NOT NULL)
        OR (result_option_type IN ('ACCEPT', 'REROLL') AND result_curated_offer_id IS NULL)
        OR (result_option_type IS NULL AND result_curated_offer_id IS NULL)
    ),
    CONSTRAINT ck_selection_voting_round_apply_state CHECK (apply_state IN (
        'PENDING', 'CONFIRMED', 'REROLL_IN_PROGRESS', 'REROLL_OFFER_READY',
        'REROLL_AUTO_CONFIRM_PENDING', 'REROLL_AUTO_CONFIRMED', 'REROLL_EXHAUSTED', 'REROLL_FAILED'
    )),
    CONSTRAINT ck_selection_voting_round_completion_shape CHECK (
        (status = 'OPEN' AND completed_at IS NULL AND result_option_type IS NULL
            AND tie_break_used = false AND apply_state = 'PENDING'
            AND resulting_offer_set_id IS NULL AND apply_detail IS NULL AND applied_at IS NULL)
        OR (status = 'COMPLETED' AND completed_at IS NOT NULL AND result_option_type IS NOT NULL)
    )
);

CREATE INDEX ix_selection_voting_round_session_status
    ON selection_voting_round (challenge_session_id, status, round_number);

CREATE TABLE selection_vote (
    voting_round_id         bigint NOT NULL REFERENCES selection_voting_round(id) ON DELETE RESTRICT,
    participant_id          bigint NOT NULL REFERENCES participant(id) ON DELETE RESTRICT,
    option_type             text NOT NULL,
    curated_offer_id        bigint REFERENCES curated_offer(id) ON DELETE RESTRICT,
    voted_at                timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (voting_round_id, participant_id),
    CONSTRAINT ck_selection_vote_type CHECK (option_type IN ('OFFER', 'ACCEPT', 'REROLL')),
    CONSTRAINT ck_selection_vote_shape CHECK (
        (option_type = 'OFFER' AND curated_offer_id IS NOT NULL)
        OR (option_type IN ('ACCEPT', 'REROLL') AND curated_offer_id IS NULL)
    )
);

CREATE INDEX ix_selection_vote_participant ON selection_vote (participant_id, voting_round_id);

CREATE TABLE challenge_participation (
    challenge_id    bigint NOT NULL REFERENCES challenge(id) ON DELETE RESTRICT,
    participant_id  bigint NOT NULL REFERENCES participant(id) ON DELETE RESTRICT,
    joined_at       timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (challenge_id, participant_id)
);

CREATE INDEX ix_challenge_participation_participant ON challenge_participation (participant_id, challenge_id);

CREATE OR REPLACE FUNCTION assert_selection_voting_choice(
    target_round_id bigint,
    target_option_type text,
    target_offer_id bigint
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    target_offer_set_id bigint;
    target_round_number smallint;
    requested_count integer;
BEGIN
    SELECT voting_round.curated_offer_set_id, voting_round.round_number, offer_set.requested_offer_count
      INTO target_offer_set_id, target_round_number, requested_count
      FROM selection_voting_round voting_round
      JOIN curated_offer_set offer_set ON offer_set.id = voting_round.curated_offer_set_id
     WHERE voting_round.id = target_round_id;
    IF target_offer_set_id IS NULL THEN
        RAISE EXCEPTION 'selection voting round % does not exist', target_round_id;
    END IF;

    IF target_option_type = 'OFFER' THEN
        IF target_offer_id IS NULL OR NOT EXISTS (
            SELECT 1 FROM curated_offer
             WHERE id = target_offer_id AND curated_offer_set_id = target_offer_set_id
        ) THEN
            RAISE EXCEPTION 'vote offer must belong to its voting round offer set';
        END IF;
    ELSIF target_option_type = 'ACCEPT' THEN
        IF requested_count <> 1 THEN
            RAISE EXCEPTION 'ACCEPT is valid only for a one-offer voting round';
        END IF;
    ELSIF target_option_type = 'REROLL' THEN
        IF target_round_number <> 1 THEN
            RAISE EXCEPTION 'REROLL is valid only in selection voting round 1';
        END IF;
    ELSE
        RAISE EXCEPTION 'unknown selection vote option type %', target_option_type;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION validate_selection_voting_round()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    offer_session_id bigint;
    offer_status text;
    offer_attempt_type text;
    first_result text;
    electorate_count integer;
    vote_count integer;
BEGIN
    SELECT attempt.challenge_session_id, offer_set.status, attempt.attempt_type
      INTO offer_session_id, offer_status, offer_attempt_type
      FROM curated_offer_set offer_set
      JOIN generation_attempt attempt ON attempt.id = offer_set.generation_attempt_id
     WHERE offer_set.id = NEW.curated_offer_set_id;
    IF offer_session_id IS NULL OR offer_session_id <> NEW.challenge_session_id THEN
        RAISE EXCEPTION 'selection voting round offer set must belong to the same challenge session';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'OPEN' THEN
            RAISE EXCEPTION 'new selection voting rounds must start open';
        END IF;
        IF offer_status <> 'PRESENTED_PENDING_DECISION' THEN
            RAISE EXCEPTION 'selection voting rounds require an actually presented pending offer set';
        END IF;
        IF NEW.round_number = 2 THEN
            SELECT result_option_type INTO first_result
              FROM selection_voting_round
             WHERE challenge_session_id = NEW.challenge_session_id AND round_number = 1 AND status = 'COMPLETED';
            IF first_result IS DISTINCT FROM 'REROLL'
               OR NOT EXISTS (SELECT 1 FROM reroll_offer_exposure
                               WHERE challenge_session_id = NEW.challenge_session_id)
               OR offer_attempt_type <> 'REROLL' THEN
                RAISE EXCEPTION 'selection voting round 2 requires a persisted winning Phase-11A reroll';
            END IF;
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.status = 'OPEN' THEN
        IF NEW.curated_offer_set_id <> OLD.curated_offer_set_id
           OR NEW.challenge_session_id <> OLD.challenge_session_id
           OR NEW.round_number <> OLD.round_number THEN
            RAISE EXCEPTION 'selection voting round identity is immutable';
        END IF;
        IF NEW.status = 'COMPLETED' THEN
            SELECT count(*) INTO electorate_count
              FROM selection_electorate WHERE challenge_session_id = NEW.challenge_session_id;
            SELECT count(*) INTO vote_count FROM selection_vote WHERE voting_round_id = NEW.id;
            IF electorate_count = 0 OR vote_count <> electorate_count THEN
                RAISE EXCEPTION 'a selection voting round can complete only after every electorate member voted';
            END IF;
            PERFORM assert_selection_voting_choice(NEW.id, NEW.result_option_type, NEW.result_curated_offer_id);
        ELSIF NEW.status <> 'OPEN' THEN
            RAISE EXCEPTION 'an open selection voting round may only become completed';
        END IF;
    ELSIF NEW.status <> 'COMPLETED'
          OR NEW.challenge_session_id <> OLD.challenge_session_id
          OR NEW.round_number <> OLD.round_number
          OR NEW.curated_offer_set_id <> OLD.curated_offer_set_id
          OR NEW.result_option_type IS DISTINCT FROM OLD.result_option_type
          OR NEW.result_curated_offer_id IS DISTINCT FROM OLD.result_curated_offer_id
          OR NEW.tie_break_used IS DISTINCT FROM OLD.tie_break_used
          OR NEW.completed_at IS DISTINCT FROM OLD.completed_at THEN
        RAISE EXCEPTION 'completed selection voting round results are immutable';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_selection_voting_round_validate
BEFORE INSERT OR UPDATE ON selection_voting_round
FOR EACH ROW EXECUTE FUNCTION validate_selection_voting_round();

CREATE OR REPLACE FUNCTION validate_selection_vote()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_session_id bigint;
    round_status text;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'selection votes are not deletable';
    END IF;
    SELECT challenge_session_id, status
      INTO target_session_id, round_status
      FROM selection_voting_round WHERE id = NEW.voting_round_id;
    IF target_session_id IS NULL OR NOT EXISTS (
        SELECT 1 FROM selection_electorate
         WHERE challenge_session_id = target_session_id AND participant_id = NEW.participant_id
    ) THEN
        RAISE EXCEPTION 'selection vote participant must belong to the fixed electorate';
    END IF;
    IF round_status <> 'OPEN' THEN
        RAISE EXCEPTION 'selection votes are immutable after round completion';
    END IF;
    IF TG_OP = 'UPDATE' AND (NEW.voting_round_id <> OLD.voting_round_id
                             OR NEW.participant_id <> OLD.participant_id
                             OR NEW.voted_at IS DISTINCT FROM OLD.voted_at) THEN
        RAISE EXCEPTION 'selection vote identity and original timestamp are immutable';
    END IF;
    PERFORM assert_selection_voting_choice(NEW.voting_round_id, NEW.option_type, NEW.curated_offer_id);
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_selection_vote_validate
BEFORE INSERT OR UPDATE OR DELETE ON selection_vote
FOR EACH ROW EXECUTE FUNCTION validate_selection_vote();

CREATE OR REPLACE FUNCTION validate_challenge_participation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'UPDATE' THEN
        RAISE EXCEPTION 'challenge participation is immutable after joining';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM participant WHERE id = NEW.participant_id AND active) THEN
        RAISE EXCEPTION 'only active registered participants may join a challenge';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_challenge_participation_validate
BEFORE INSERT OR UPDATE ON challenge_participation
FOR EACH ROW EXECUTE FUNCTION validate_challenge_participation();

CREATE OR REPLACE FUNCTION prevent_selection_electorate_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'selection electorate snapshots are immutable';
END;
$$;

CREATE TRIGGER trg_selection_electorate_append_only
BEFORE UPDATE OR DELETE ON selection_electorate
FOR EACH ROW EXECUTE FUNCTION prevent_selection_electorate_mutation();

-- Once Phase 11B has snapshotted an electorate, a terminal 11A decision must be the result
-- materialized by this core. This prevents a stale direct confirm/reroll interaction from
-- bypassing an open or completed voting round while preserving the pre-11B 11A API path.
CREATE OR REPLACE FUNCTION assert_selection_authorized_offer_decision(target_offer_set_id bigint)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    target_status text;
    target_session_id bigint;
    target_offer_count integer;
    target_challenge_offer_id bigint;
    own_round record;
    source_round record;
BEGIN
    SELECT offer_set.status, attempt.challenge_session_id, offer_set.requested_offer_count
      INTO target_status, target_session_id, target_offer_count
      FROM curated_offer_set offer_set
      JOIN generation_attempt attempt ON attempt.id = offer_set.generation_attempt_id
     WHERE offer_set.id = target_offer_set_id;
    IF NOT FOUND OR target_status NOT IN ('CONFIRMED', 'REROLLED') THEN
        RETURN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM selection_electorate WHERE challenge_session_id = target_session_id) THEN
        RETURN;
    END IF;

    SELECT * INTO own_round
      FROM selection_voting_round
     WHERE curated_offer_set_id = target_offer_set_id;
    IF FOUND THEN
        IF own_round.status <> 'COMPLETED' THEN
            RAISE EXCEPTION 'a presented offer set with an electorate requires a completed voting round decision';
        END IF;
        IF target_status = 'REROLLED' THEN
            IF own_round.result_option_type <> 'REROLL' THEN
                RAISE EXCEPTION 'only a persisted REROLL voting result may reroll its offer set';
            END IF;
            RETURN;
        END IF;
        SELECT curated_offer_id INTO target_challenge_offer_id
          FROM challenge
         WHERE curated_offer_id IN (SELECT id FROM curated_offer WHERE curated_offer_set_id = target_offer_set_id);
        IF own_round.result_option_type = 'OFFER'
           AND own_round.result_curated_offer_id = target_challenge_offer_id THEN
            RETURN;
        END IF;
        IF own_round.result_option_type = 'ACCEPT' AND own_round.round_number = 1 AND target_offer_count = 1 THEN
            RETURN;
        END IF;
        RAISE EXCEPTION 'only the persisted winning offer or ACCEPT result may confirm its offer set';
    END IF;

    SELECT * INTO source_round
      FROM selection_voting_round
     WHERE resulting_offer_set_id = target_offer_set_id
       AND result_option_type = 'REROLL'
     ORDER BY round_number DESC
     LIMIT 1;
    IF target_status = 'CONFIRMED' AND FOUND
       AND source_round.apply_state IN ('REROLL_AUTO_CONFIRM_PENDING', 'REROLL_AUTO_CONFIRMED')
       AND target_offer_count = 1 THEN
        RETURN;
    END IF;
    RAISE EXCEPTION 'an electorate session offer decision must be authorized by the voting core';
END;
$$;

CREATE OR REPLACE FUNCTION validate_selection_authorized_offer_decision_trigger()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    target_offer_set_id bigint;
BEGIN
    IF TG_TABLE_NAME = 'curated_offer_set' THEN
        target_offer_set_id := NEW.id;
    ELSE
        SELECT curated_offer_set_id INTO target_offer_set_id
          FROM curated_offer WHERE id = NEW.curated_offer_id;
    END IF;
    PERFORM assert_selection_authorized_offer_decision(target_offer_set_id);
    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER trg_selection_offer_set_decision_authorized
AFTER INSERT OR UPDATE ON curated_offer_set
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_selection_authorized_offer_decision_trigger();

CREATE CONSTRAINT TRIGGER trg_selection_challenge_decision_authorized
AFTER INSERT OR UPDATE ON challenge
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION validate_selection_authorized_offer_decision_trigger();
